# **CREATED PYSPIDERS DATA SET**

In [1]:
import pandas as pd
import numpy as np

In [11]:
n=30000

In [12]:
Student_Name = ['Stud_'+str(i).zfill(5) for i in range(1,n+1)]

In [26]:
pd.DataFrame(Student_Name,columns=['Student Name'])

      Student Name
0       Stud_00001
1       Stud_00002
2       Stud_00003
3       Stud_00004
4       Stud_00005
...            ...
29995   Stud_29996
29996   Stud_29997
29997   Stud_29998
29998   Stud_29999
29999   Stud_30000

[30000 rows x 1 columns]

In [ ]:
Phone_Num = np.random.randint(6000000000,9999999999,n,dtype=np.int64)

In [28]:
pd.DataFrame(Phone_Num,columns=['Phone Number'])

       Phone Number
0        6633812187
1        8268566422
2        6713245593
3        9033992219
4        6117831905
...             ...
29995    6836367122
29996    7240584616
29997    8626614297
29998    8047150629
29999    7235331199

[30000 rows x 1 columns]

In [20]:
Email_ID = [i+'@gmail.com' for i in Student_Name]

In [29]:
pd.DataFrame(Email_ID,columns=['Email ID'])

                   Email ID
0      Stud_00001@gmail.com
1      Stud_00002@gmail.com
2      Stud_00003@gmail.com
3      Stud_00004@gmail.com
4      Stud_00005@gmail.com
...                     ...
29995  Stud_29996@gmail.com
29996  Stud_29997@gmail.com
29997  Stud_29998@gmail.com
29998  Stud_29999@gmail.com
29999  Stud_30000@gmail.com

[30000 rows x 1 columns]

In [22]:
Admission_Type = np.random.choice(['INC','PAID'],n)

In [30]:
pd.DataFrame(Admission_Type,columns=['Admission Type'])

      Admission Type
0               PAID
1               PAID
2               PAID
3               PAID
4               PAID
...              ...
29995            INC
29996           PAID
29997           PAID
29998           PAID
29999           PAID

[30000 rows x 1 columns]

In [31]:
Tenth_Percentage = np.round(np.random.randint(60,99,n) + np.random.rand(n),2)

In [32]:
pd.DataFrame(Tenth_Percentage,columns=['Tenth Percentage'])

       Tenth Percentage
0                 64.05
1                 93.50
2                 89.52
3                 76.74
4                 64.89
...                 ...
29995             70.10
29996             66.99
29997             68.03
29998             72.68
29999             80.80

[30000 rows x 1 columns]

In [33]:
Tenth_YOP = np.random.choice([2017,2018,2019,2020],n)

In [38]:
pd.DataFrame(Tenth_YOP,columns=['Tenth YOP'])

       Tenth YOP
0           2019
1           2019
2           2019
3           2018
4           2020
...          ...
29995       2018
29996       2020
29997       2018
29998       2018
29999       2017

[30000 rows x 1 columns]

In [35]:
Twelth_Percentage = np.round(np.random.randint(60,99,n) + np.random.rand(n),2)

In [37]:
pd.DataFrame(Twelth_Percentage,columns=['Twelth Percentage'])

       Twelth Percentage
0                  82.34
1                  64.52
2                  60.00
3                  80.29
4                  83.11
...                  ...
29995              87.37
29996              97.59
29997              72.50
29998              66.90
29999              65.64

[30000 rows x 1 columns]

In [40]:
Twelth_YOP = Tenth_YOP+2

In [41]:
pd.DataFrame(Twelth_YOP,columns=['Twelth YOP'])

       Twelth YOP
0            2021
1            2021
2            2021
3            2020
4            2022
...           ...
29995        2020
29996        2022
29997        2020
29998        2020
29999        2019

[30000 rows x 1 columns]

In [42]:
Degree_Percentage = np.round(np.random.randint(60,99,n) + np.random.rand(n),2)

In [43]:
pd.DataFrame(Degree_Percentage,columns=['Degree Percentage'])

       Degree Percentage
0                  80.77
1                  93.33
2                  89.94
3                  74.94
4                  82.40
...                  ...
29995              86.46
29996              77.55
29997              60.67
29998              80.31
29999              90.72

[30000 rows x 1 columns]

In [44]:
Branches = np.random.choice(['Bsc', 'Bcom', 'BE', 'BTech', 'BBA', 'BCA'],n)

In [45]:
pd.DataFrame(Branches,columns=['Branches'])

      Branches
0          BBA
1          BCA
2           BE
3          BBA
4           BE
...        ...
29995       BE
29996       BE
29997       BE
29998      BCA
29999      BBA

[30000 rows x 1 columns]

In [46]:
Degree_YOP = []
for branch , yop in zip(Branches,Twelth_YOP):
    if branch in ['Bsc','Bcom','BBA','BCA']:
        Degree_YOP.append(yop+3)
    elif branch in ['BE','BTech']:
        Degree_YOP.append(yop+4)
Degree_YOP = np.array(Degree_YOP)

In [47]:
pd.DataFrame(Degree_YOP,columns=['Degree YOP'])

       Degree YOP
0            2024
1            2024
2            2025
3            2023
4            2026
...           ...
29995        2024
29996        2026
29997        2024
29998        2023
29999        2022

[30000 rows x 1 columns]

In [48]:
Master_Stream = np.random.choice(['ME','MTech','MCA',None],n)

In [51]:
pd.DataFrame(Master_Stream,columns=['Master Stream'])

      Master Stream
0               MCA
1             MTech
2                ME
3              None
4              None
...             ...
29995          None
29996            ME
29997           MCA
29998            ME
29999          None

[30000 rows x 1 columns]

In [53]:
Master_Degree_Percentage = []
for i in Master_Stream:
    if i!=None:
        Master_Degree_Percentage.append(np.random.randint(35,99))
    else:
        Master_Degree_Percentage.append(np.nan)
Master_Degree_Percentage = np.array(Master_Degree_Percentage)

In [54]:
pd.DataFrame(Master_Degree_Percentage,columns=['Master Degree Percentage'])

       Master Degree Percentage
0                          82.0
1                          54.0
2                          66.0
3                           NaN
4                           NaN
...                         ...
29995                       NaN
29996                      53.0
29997                      62.0
29998                      95.0
29999                       NaN

[30000 rows x 1 columns]

In [60]:
out = []
for i,j in zip(Master_Stream,Degree_YOP):
    if i in ['ME','MTech','MCA']:
        out.append(j+2)
    else:
        out.append(np.nan)
Master_YOP = np.array(out)

In [61]:
pd.DataFrame(Master_YOP,columns=['Master YOP'])

       Master YOP
0          2026.0
1          2026.0
2          2027.0
3             NaN
4             NaN
...           ...
29995         NaN
29996      2028.0
29997      2026.0
29998      2025.0
29999         NaN

[30000 rows x 1 columns]

In [56]:
Courses_Taken = np.random.choice(['Python FullStack Development','Python Data Analytics','Python Data Science','Python Selenium'],n)

In [57]:
pd.DataFrame(Courses_Taken,columns=['Courses Taken'])

                      Courses Taken
0                   Python Selenium
1               Python Data Science
2               Python Data Science
3      Python FullStack Development
4                   Python Selenium
...                             ...
29995  Python FullStack Development
29996               Python Selenium
29997  Python FullStack Development
29998           Python Data Science
29999         Python Data Analytics

[30000 rows x 1 columns]

In [58]:
Status_Of_Placement = np.random.choice(['Placed','Not Placed'],n)

In [59]:
pd.DataFrame(Status_Of_Placement,columns=['Status Of Placement'])

      Status Of Placement
0              Not Placed
1                  Placed
2              Not Placed
3                  Placed
4                  Placed
...                   ...
29995          Not Placed
29996          Not Placed
29997          Not Placed
29998          Not Placed
29999          Not Placed

[30000 rows x 1 columns]

In [64]:
Pyspider_Dataset = pd.DataFrame({
    'Student Name': Student_Name,
    'Phone Number' : Phone_Num,
    'Email ID': Email_ID,
    'Admission Type' : Admission_Type,
    'Courses Taken':Courses_Taken,
    'Tenth YOP': Tenth_YOP,
    'Tenth Percentage':Tenth_Percentage,
    'Twelth YOP':Twelth_YOP,
    'Twelth Percentage':Twelth_Percentage,
    'Degree Yop':Degree_YOP,
    'Degree Stream':Branches,
    'Degree Percentage':Degree_Percentage,
    'Masters Degree YOP':Master_YOP,
    'Masters Degree Stream':Master_Stream,
    'Masters Degree Percentage':Master_Degree_Percentage,
})

In [65]:
Pyspider_Dataset

,Student Name,Phone Number,Email ID,Admission Type,Courses Taken,Tenth YOP,Tenth Percentage,Twelth YOP,Twelth Percentage,Degree Yop,Degree Stream,Degree Percentage,Masters Degree YOP,Masters Degree Stream,Masters Degree Percentage
0,Stud_00001,6633812187,Stud_00001@gmail.com,PAID,Python Selenium,2019,64.05,2021,82.34,2024,BBA,80.77,2026.0,MCA,82.0
1,Stud_00002,8268566422,Stud_00002@gmail.com,PAID,Python Data Science,2019,93.50,2021,64.52,2024,BCA,93.33,2026.0,MTech,54.0
2,Stud_00003,6713245593,Stud_00003@gmail.com,PAID,Python Data Science,2019,89.52,2021,60.00,2025,BE,89.94,2027.0,ME,66.0
3,Stud_00004,9033992219,Stud_00004@gmail.com,PAID,Python FullStack Development,2018,76.74,2020,80.29,2023,BBA,74.94,NaN,None,NaN
4,Stud_00005,6117831905,Stud_00005@gmail.com,PAID,Python Selenium,2020,64.89,2022,83.11,2026,BE,82.40,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,Stud_29996,6836367122,Stud_29996@gmail.com,INC,Python FullStack Development,2018,70.10,2020,87.37,2024,BE,86.46,NaN,None,NaN
29996,Stud_29997,7240584616,Stud_29997@gmail.com,PAID,Python Selenium,2020,66.99,2022,97.59,2026,BE,77.55,2028.0,ME,53.0
29997,Stud_29998,8626614297,Stud_29998@gmail.com,PAID,Python FullStack Development,2018,68.03,2020,72.50,2024,BE,60.67,2026.0,MCA,62.0
29998,Stud_29999,8047150629,Stud_29999@gmail.com,PAID,Python Data Science,2018,72.68,2020,66.90,2023,BCA,80.31,2025.0,ME,95.0
29999,Stud_30000,7235331199,Stud_30000@gmail.com,PAID,Python Data Analytics,2017,80.80,2019,65.64,2022,BBA,90.72,NaN,None,NaN

In [66]:
Pyspider_Dataset.to_csv("Pyspider_Dataset.csv", index=False)

In [71]:
import pandas as pd
import random
from datetime import datetime

CURRENT_YEAR = 2026

def generate_joining_date(row):
    # Step 1: Get latest education year
    if pd.notna(row['Masters Degree YOP']):
        yop = int(row['Masters Degree YOP'])
    else:
        yop = int(row['Degree Yop'])
    
    # Step 2: Fix future year issue
    if yop > CURRENT_YEAR:
        yop = CURRENT_YEAR
    
    # Step 3: Generate valid joining date
    month = random.randint(1, 12)
    day = random.randint(1, 28)
    return datetime(yop, month, day).date()

# Apply to dataset
Pyspider_Dataset['Course_Enrollment_Date'] = Pyspider_Dataset.apply(generate_joining_date, axis=1)

In [72]:
Pyspider_Dataset

,Student Name,Phone Number,Email ID,Admission Type,Courses Taken,Tenth YOP,Tenth Percentage,Twelth YOP,Twelth Percentage,Degree Yop,Degree Stream,Degree Percentage,Masters Degree YOP,Masters Degree Stream,Masters Degree Percentage,Course_Enrollment_Date
0,Stud_00001,6633812187,Stud_00001@gmail.com,PAID,Python Selenium,2019,64.05,2021,82.34,2024,BBA,80.77,2026.0,MCA,82.0,2026-09-07
1,Stud_00002,8268566422,Stud_00002@gmail.com,PAID,Python Data Science,2019,93.50,2021,64.52,2024,BCA,93.33,2026.0,MTech,54.0,2026-05-14
2,Stud_00003,6713245593,Stud_00003@gmail.com,PAID,Python Data Science,2019,89.52,2021,60.00,2025,BE,89.94,2027.0,ME,66.0,2026-09-09
3,Stud_00004,9033992219,Stud_00004@gmail.com,PAID,Python FullStack Development,2018,76.74,2020,80.29,2023,BBA,74.94,NaN,None,NaN,2023-05-13
4,Stud_00005,6117831905,Stud_00005@gmail.com,PAID,Python Selenium,2020,64.89,2022,83.11,2026,BE,82.40,NaN,None,NaN,2026-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,Stud_29996,6836367122,Stud_29996@gmail.com,INC,Python FullStack Development,2018,70.10,2020,87.37,2024,BE,86.46,NaN,None,NaN,2024-07-25
29996,Stud_29997,7240584616,Stud_29997@gmail.com,PAID,Python Selenium,2020,66.99,2022,97.59,2026,BE,77.55,2028.0,ME,53.0,2026-11-15
29997,Stud_29998,8626614297,Stud_29998@gmail.com,PAID,Python FullStack Development,2018,68.03,2020,72.50,2024,BE,60.67,2026.0,MCA,62.0,2026-02-28
29998,Stud_29999,8047150629,Stud_29999@gmail.com,PAID,Python Data Science,2018,72.68,2020,66.90,2023,BCA,80.31,2025.0,ME,95.0,2025-06-01
29999,Stud_30000,7235331199,Stud_30000@gmail.com,PAID,Python Data Analytics,2017,80.80,2019,65.64,2022,BBA,90.72,NaN,None,NaN,2022-01-04

In [73]:
Pyspider_Dataset.to_csv("Pyspider_Dataset.csv", index=False)

In [78]:
Pyspider_Dataset['Masters Degree YOP'] = Pyspider_Dataset['Masters Degree YOP'].fillna(0).astype(int)

In [79]:
Pyspider_Dataset

,Student Name,Phone Number,Email ID,Admission Type,Courses Taken,Tenth YOP,Tenth Percentage,Twelth YOP,Twelth Percentage,Degree Yop,Degree Stream,Degree Percentage,Masters Degree YOP,Masters Degree Stream,Masters Degree Percentage,Course_Enrollment_Date
0,Stud_00001,6633812187,Stud_00001@gmail.com,PAID,Python Selenium,2019,64.05,2021,82.34,2024,BBA,80.77,2026,MCA,82.0,2026-09-07
1,Stud_00002,8268566422,Stud_00002@gmail.com,PAID,Python Data Science,2019,93.50,2021,64.52,2024,BCA,93.33,2026,MTech,54.0,2026-05-14
2,Stud_00003,6713245593,Stud_00003@gmail.com,PAID,Python Data Science,2019,89.52,2021,60.00,2025,BE,89.94,2027,ME,66.0,2026-09-09
3,Stud_00004,9033992219,Stud_00004@gmail.com,PAID,Python FullStack Development,2018,76.74,2020,80.29,2023,BBA,74.94,0,None,NaN,2023-05-13
4,Stud_00005,6117831905,Stud_00005@gmail.com,PAID,Python Selenium,2020,64.89,2022,83.11,2026,BE,82.40,0,None,NaN,2026-07-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,Stud_29996,6836367122,Stud_29996@gmail.com,INC,Python FullStack Development,2018,70.10,2020,87.37,2024,BE,86.46,0,None,NaN,2024-07-25
29996,Stud_29997,7240584616,Stud_29997@gmail.com,PAID,Python Selenium,2020,66.99,2022,97.59,2026,BE,77.55,2028,ME,53.0,2026-11-15
29997,Stud_29998,8626614297,Stud_29998@gmail.com,PAID,Python FullStack Development,2018,68.03,2020,72.50,2024,BE,60.67,2026,MCA,62.0,2026-02-28
29998,Stud_29999,8047150629,Stud_29999@gmail.com,PAID,Python Data Science,2018,72.68,2020,66.90,2023,BCA,80.31,2025,ME,95.0,2025-06-01
29999,Stud_30000,7235331199,Stud_30000@gmail.com,PAID,Python Data Analytics,2017,80.80,2019,65.64,2022,BBA,90.72,0,None,NaN,2022-01-04

In [80]:
Pyspider_Dataset.to_csv("Pyspider_Dataset.csv", index=False)