# **Pandas Library**
### **Group By in Pandas**

##### **Group By :**
##### It is a DataFrame method which is used to group the records based on given columns. Group By Internally it performs boolean indexing & fetchs values based on unique values from a given columns.
##### After performing group by internally it creates dictionary where all the unique values of grouped columns act as keys and values are indexs of records.
##### **General Syntax : df.groupby('col_name')**

In [72]:
import pandas as pd
import numpy as np
df=pd.read_csv("Employee_Cleaned_Dataset.csv")
df.drop(columns='Unnamed: 0', inplace=True)
df

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

In [57]:
df.groupby('Department')

##### Multiple Column Grouping :
##### **Syntax : df.groupby(['col_name','col_name'])**

In [58]:
df.groupby(['Department','City'])

##### Group by with indexing syntax :
##### **Syntax : df.groupby('col_name')['col_name']**

In [59]:
df.groupby('Department')['Salary']

##### Group by with aggregation function :
##### **Syntax : df.groupby('col_name')['col_name'].fun()**
##### Where fun() includes sum(),count(),min(),max()

##### **Ex1. Group By Department and Calculate Total Salary**

In [60]:
df.groupby('Department')['Salary'].sum()

Department
FINANCE     153000.0
HR          155000.0
IT         1191000.0
SALES        97000.0
Name: Salary, dtype: float64

##### **Ex2. Group By Gender and Calculate Total Salary**

In [61]:
df.groupby('Gender')['Salary'].sum()

Gender
Female      102000.0
Male       1141000.0
Unknown     353000.0
Name: Salary, dtype: float64

##### **Ex3. Group By Department and Calculate Average Salary**

In [62]:
df.groupby('Department')['Salary'].mean()

Department
FINANCE     51000.000000
HR          51666.666667
IT         198500.000000
SALES       32333.333333
Name: Salary, dtype: float64

##### **Ex4. Count Employees in Each Department**

In [63]:
df.groupby('Department')['Employee Name'].count()

Department
FINANCE    3
HR         3
IT         6
SALES      3
Name: Employee Name, dtype: int64

##### **Ex5. Find Maximum Salary in Each Department**

In [64]:
df=df.groupby('Department')['Salary'].max()
s = df.to_frame()
s

               Salary
Department
FINANCE       55000.0
HR            53000.0
IT          1000000.0
SALES         47000.0

##### **Ex6. Find Minimum Salary in Each Department**

In [68]:
df.groupby('Department')['Salary'].min()

Department
FINANCE    48000.0
HR         50000.0
IT             0.0
SALES      10000.0
Name: Salary, dtype: float64

##### Apply multiple aggregation function :
##### **Syntax : df.groupby('col_name')['col_name'].agg(['fname','fname',...])**

In [20]:
df.groupby('Department')['Salary'].agg(['sum', 'mean', 'max', 'min'])

                  sum           mean        max      min
Department
FINANCE      153000.0   51000.000000    55000.0  48000.0
HR           155000.0   51666.666667    53000.0  50000.0
IT          1191000.0  198500.000000  1000000.0      0.0
SALES         97000.0   32333.333333    47000.0  10000.0

In [21]:
df.groupby('Gender')['Salary'].agg(['sum', 'mean', 'max', 'min'])

               sum      mean        max      min
Gender
Female    102000.0   51000.0    55000.0  47000.0
Male     1141000.0  228200.0  1000000.0  10000.0
Unknown   353000.0   44125.0    53000.0      0.0

##### **GroupBy multiple Departments**

In [75]:
df.groupby(['Department', 'Gender'])['Salary'].mean()

Department  Gender
FINANCE     Female      55000.000000
            Unknown     49000.000000
HR          Unknown     51666.666667
IT          Male       363666.666667
            Unknown     33333.333333
SALES       Female      47000.000000
            Male        25000.000000
Name: Salary, dtype: float64

In [76]:
df.groupby(['Department', 'Age'])['Salary'].mean()

Department  Age
FINANCE     0        55000.0
            24       48000.0
            25       50000.0
HR          0        53000.0
            25       50000.0
            65       52000.0
IT          0        46000.0
            22           0.0
            23       45000.0
            24       51000.0
            27       49000.0
            28     1000000.0
SALES       17       40000.0
            26       47000.0
            29       10000.0
Name: Salary, dtype: float64

In [77]:
df.groupby(['Gender','Department'])['Salary'].mean()

Gender   Department
Female   FINANCE        55000.000000
         SALES          47000.000000
Male     IT            363666.666667
         SALES          25000.000000
Unknown  FINANCE        49000.000000
         HR             51666.666667
         IT             33333.333333
Name: Salary, dtype: float64

In [79]:
df.groupby(['Gender','Department','City'])['Salary'].mean()

Gender   Department  City
Female   FINANCE     Mysore         55000.0
         SALES       Hubli          47000.0
Male     IT          Bangalore    1000000.0
                     Belagavi       45000.0
                     Hubli          46000.0
         SALES       Bangalore      10000.0
                     Dharwad        40000.0
Unknown  FINANCE     Dharwad        50000.0
                     Mysore         48000.0
         HR          Bangalore      50000.0
                     Belagavi       52500.0
         IT          Dharwad        49000.0
                     Hubli              0.0
                     Mysore         51000.0
Name: Salary, dtype: float64

In [81]:
df.groupby(['Gender','Department'])['Employee Name'].count()

Gender   Department
Female   FINANCE       1
         SALES         1
Male     IT            3
         SALES         2
Unknown  FINANCE       2
         HR            3
         IT            3
Name: Employee Name, dtype: int64

In [82]:
df.groupby(['Gender','City'])['Employee Name'].count()

Gender   City
Female   Hubli        1
         Mysore       1
Male     Bangalore    2
         Belagavi     1
         Dharwad      1
         Hubli        1
Unknown  Bangalore    1
         Belagavi     2
         Dharwad      2
         Hubli        1
         Mysore       2
Name: Employee Name, dtype: int64

In [80]:
df.groupby(['Gender','Department','City'])['Employee Name'].count()

Gender   Department  City
Female   FINANCE     Mysore       1
         SALES       Hubli        1
Male     IT          Bangalore    1
                     Belagavi     1
                     Hubli        1
         SALES       Bangalore    1
                     Dharwad      1
Unknown  FINANCE     Dharwad      1
                     Mysore       1
         HR          Bangalore    1
                     Belagavi     2
         IT          Dharwad      1
                     Hubli        1
                     Mysore       1
Name: Employee Name, dtype: int64

##### **Fetching all the groups :**
##### To fetch all the groups we use group by attribute.
##### **Syntax : variable = df.groupby('col')**
##### **variable.groups**
##### Here group returns dictionary where keys are unique values given column & values are row index.

In [78]:
det=df.groupby('Department')
det.groups

{'FINANCE': [2, 7, 14], 'HR': [1, 5, 10], 'IT': [0, 3, 6, 9, 12, 13], 'SALES': [4, 8, 11]}

In [69]:
det=df.groupby('Gender')
det.groups

{'Female': [2, 8], 'Male': [0, 4, 6, 11, 13], 'Unknown': [1, 3, 5, 7, 9, 10, 12, 14]}

In [70]:
det=df.groupby('City')
det.groups

{'Bangalore': [1, 6, 11], 'Belagavi': [0, 5, 10], 'Dharwad': [4, 9, 14], 'Hubli': [3, 8, 13], 'Mysore': [2, 7, 12]}

##### To fetch single group separately we use group by internal methods.
##### **Syntax : variable = df.groupby('col')**
##### **variable.get_group('key')**
##### **key:** The actual value present in the grouped column

In [87]:
det=df.groupby('City')
det.get_group('Bangalore')

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore

In [89]:
det=df.groupby('City')
det.get_group('Belagavi')

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi

In [90]:
det=df.groupby('Gender')
det.get_group('Male')

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli

In [91]:
det=df.groupby('Department')
det.get_group('IT')

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli

##### **Convert Grouped Result to DataFrame**

In [92]:
df.groupby('Department')['Salary'].mean().reset_index()

  Department         Salary
0    FINANCE   51000.000000
1         HR   51666.666667
2         IT  198500.000000
3      SALES   32333.333333