# **Pandas Library**
### **Pivot & Pivot Table**

##### **Pivot :**
##### It is used to reshape the existing  dataframe. If we have any duplicates it doesn't work. In pivot we can't use aggregate functions.
##### **Syntax : pd.pivot(data=DataFrame,index='row_column',columns='column_to_expand',values='value_column')**
##### Here for index & columns we want to provide only categorical columns.

| Parameter | Meaning                                            |
| --------- | -------------------------------------------------- |
| `data`    | The DataFrame to reshape                           |
| `index`   | Column whose values become row labels              |
| `columns` | Column whose unique values become new column names |
| `values`  | Column whose values fill the new table             |

In [3]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Aftab', 'Aftab', 'John', 'John'],
    'Subject': ['Math', 'Science', 'Math', 'Science'],
    'Marks': [90, 85, 80, 75]
})
df

    Name  Subject  Marks
0  Aftab     Math     90
1  Aftab  Science     85
2   John     Math     80
3   John  Science     75

In [4]:
pivot_df = pd.pivot(data=df,index='Name',columns='Subject',values='Marks')
pivot_df

Subject  Math  Science
Name
Aftab      90       85
John       80       75

In [7]:
pivot_df = pd.pivot(data=df,index='Name',columns='Subject')
pivot_df

        Marks
Subject  Math Science
Name
Aftab      90      85
John       80      75

#### **Before Pivot :**
| Name  | Subject | Marks |
| ----- | ------- | ----- |
| Aftab | Math    | 90    |
| Aftab | Science | 85    |
| John  | Math    | 80    |
| John  | Science | 75    |
#### **After Pivot :**
| Name  | Math | Science |
| ----- | ---- | ------- |
| Aftab | 90   | 85      |
| John  | 80   | 75      |

##### **IMPORTANT NOTE :**
##### pivot() requires that each combination of index and columns is unique.
##### If duplicate combinations exist:
##### ValueError: Index contains duplicate entries, cannot reshape
##### Use pivot_table() instead:
##### **Example : pd.pivot_table(data=df,index='Name',columns='Subject',values='Marks',aggfunc='mean')**

In [39]:
import pandas as pd
import numpy as np
df=pd.read_csv("Employee_Cleaned_Dataset.csv")
df.drop(columns='Unnamed: 0', inplace=True)
df

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

##### **Here we will get error because index should not conain any duplicate values**

In [40]:
pivot_df = pd.pivot(data=df,index='City',columns='Department',values='Salary')
pivot_df

ValueError: Index contains duplicate entries, cannot reshape

In [41]:
pivot_df = pd.pivot(data=df,index='Employee ID',columns='Department',values='Salary')
pivot_df

Department   FINANCE       HR         IT    SALES
Employee ID
101              NaN      NaN    45000.0      NaN
102              NaN  50000.0        NaN      NaN
103          55000.0      NaN        NaN      NaN
104              NaN      NaN        0.0      NaN
105              NaN      NaN        NaN  40000.0
106              NaN  52000.0        NaN      NaN
107              NaN      NaN  1000000.0      NaN
108          48000.0      NaN        NaN      NaN
109              NaN      NaN        NaN  47000.0
110              NaN      NaN    49000.0      NaN
111              NaN  53000.0        NaN      NaN
112              NaN      NaN        NaN  10000.0
113              NaN      NaN    51000.0      NaN
114              NaN      NaN    46000.0      NaN
115          50000.0      NaN        NaN      NaN

##### **Suppose if we are not specified the values it will take first unused column from the data set as values**
##### **Example :** We have used Emp ID as index, Department as Columns and values are not specified, at that time the interpreter itself takes the first unused column from the dataset i,.e Employee Name.

In [42]:
pivot_df = pd.pivot(data=df,index='Employee ID',columns='Department')
pivot_df

            Employee Name                                Age              \
Department        FINANCE         HR      IT   SALES FINANCE    HR    IT
Employee ID
101                   NaN        NaN   Aftab     NaN     NaN   NaN  23.0
102                   NaN    Rahul       NaN     NaN     NaN  25.0   NaN
103                 Priya        NaN     NaN     NaN     0.0   NaN   NaN
104                   NaN        NaN  Anjali     NaN     NaN   NaN  22.0
105                   NaN        NaN     NaN   Rohan     NaN   NaN   NaN
106                   NaN      Meena     NaN     NaN     NaN  65.0   NaN
107                   NaN        NaN   Vikas     NaN     NaN   NaN  28.0
108                 Arjun        NaN     NaN     NaN    24.0   NaN   NaN
109                   NaN        NaN     NaN   Sneha     NaN   NaN   NaN
110                   NaN        NaN   Kiran     NaN     NaN   NaN  27.0
111                   NaN      Pooja     NaN     NaN     NaN   0.0   NaN
112                   NaN        NaN     NaN  Rakesh     NaN   NaN   NaN
113                   NaN        NaN   Divya     NaN     NaN   NaN  24.0
114                   NaN        NaN   Akash     NaN     NaN   NaN   0.0
115                 Nisha        NaN     NaN     NaN    25.0   NaN   NaN

                    Gender           ... Joining Date              \
Department  SALES  FINANCE       HR  ...           IT       SALES
Employee ID                          ...
101           NaN      NaN      NaN  ...   2023-01-15         NaN
102           NaN      NaN  Unknown  ...          NaN         NaN
103           NaN   Female      NaN  ...          NaN         NaN
104           NaN      NaN      NaN  ...   2023-07-01         NaN
105          17.0      NaN      NaN  ...          NaN  2024-02-15
106           NaN      NaN  Unknown  ...          NaN         NaN
107           NaN      NaN      NaN  ...   2022-09-05         NaN
108           NaN  Unknown      NaN  ...          NaN         NaN
109          26.0      NaN      NaN  ...          NaN  2023-04-18
110           NaN      NaN      NaN  ...   2022-06-30         NaN
111           NaN      NaN  Unknown  ...          NaN         NaN
112          29.0      NaN      NaN  ...          NaN  2022-10-10
113           NaN      NaN      NaN  ...   2023-02-14         NaN
114           NaN      NaN      NaN  ...   2022-07-25         NaN
115           NaN  Unknown      NaN  ...          NaN         NaN

             Phone Number                                               City  \
Department        FINANCE            HR            IT         SALES  FINANCE
Employee ID
101                   NaN           NaN  9.876543e+09           NaN      NaN
102                   NaN  9.876543e+09           NaN           NaN      NaN
103          9.876543e+09           NaN           NaN           NaN   Mysore
104                   NaN           NaN  9.876543e+09           NaN      NaN
105                   NaN           NaN           NaN  9.876543e+09      NaN
106                   NaN  9.876543e+09           NaN           NaN      NaN
107                   NaN           NaN  9.876543e+09           NaN      NaN
108          9.876543e+09           NaN           NaN           NaN   Mysore
109                   NaN           NaN           NaN  9.876543e+09      NaN
110                   NaN           NaN  9.876543e+09           NaN      NaN
111                   NaN  0.000000e+00           NaN           NaN      NaN
112                   NaN           NaN           NaN  9.876543e+09      NaN
113                   NaN           NaN  9.876543e+09           NaN      NaN
114                   NaN           NaN  9.876543e+09           NaN      NaN
115          9.876543e+09           NaN           NaN           NaN  Dharwad


Department          HR         IT      SALES
Employee ID
101                NaN   Belagavi        NaN
102          Bangalore        NaN        NaN
103                NaN        NaN        NaN
104                NaN      Hubli        NaN
105                NaN        NaN    Dharwad
106           Belagavi        NaN        NaN
107                NaN  Bangalore        NaN
108                NaN        NaN        NaN
109                NaN        NaN      Hubli
110                NaN    Dharwad        NaN
111           Belagavi        NaN        NaN
112                NaN        NaN  Bangalore
113                NaN     Mysore        NaN
114                NaN      Hubli        NaN
115                NaN        NaN        NaN

[15 rows x 28 columns]

##### **Pivot Table :**
##### It is used to perform reshaping of existing dataframe along with aggragation function. It accepts duplicate values.
##### **Syntax : pd.pivot_table(data=DataFrame,index='categorical_column',aggfunc=['fun_name','fun_name'],fill_value=value,margins=True)**
##### **Note :** Margins=True works with count aggragation function or when we want to perform count aggregation then we use margins=True.

In [8]:
pd.pivot_table(data=df,index='Name',columns='Subject',values='Marks',aggfunc='mean')

Subject  Math  Science
Name
Aftab    90.0     85.0
John     80.0     75.0

In [9]:
df = pd.DataFrame({
    'Name': ['Aftab', 'Aftab', 'John', 'John'],
    'Subject': ['Math', 'Math', 'Science', 'Science'],
    'Marks': [90, 80, 70, 60]
})

In [10]:
df

    Name  Subject  Marks
0  Aftab     Math     90
1  Aftab     Math     80
2   John  Science     70
3   John  Science     60

##### **Example 1: Mean of values**

In [11]:
pd.pivot_table(
    data=df,
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc='mean'
)

Subject  Math  Science
Name
Aftab    85.0      NaN
John      NaN     65.0

##### **Example 2: Sum of values**

In [12]:
pd.pivot_table(
    data=df,
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc='sum'
)

Subject   Math  Science
Name
Aftab    170.0      NaN
John       NaN    130.0

##### **Example 3: Count of values**

In [13]:
pd.pivot_table(
    data=df,
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc='count'
)

Subject  Math  Science
Name
Aftab     2.0      NaN
John      NaN      2.0

##### **Example 4: Multiple Aggregation of values**

In [14]:
pd.pivot_table(
    data=df,
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc=['sum', 'mean', 'max']
)

           sum          mean           max
Subject   Math Science  Math Science  Math Science
Name
Aftab    170.0     NaN  85.0     NaN  90.0     NaN
John       NaN   130.0   NaN    65.0   NaN    70.0

##### **Example 5: Fill Null values**

In [15]:
pd.pivot_table(
    data=df,
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc='mean',
    fill_value=0
)

Subject  Math  Science
Name
Aftab    85.0      0.0
John      0.0     65.0

In [31]:
import pandas as pd
import numpy as np
df=pd.read_csv("Employee_Cleaned_Dataset.csv")
df.drop(columns='Unnamed: 0', inplace=True)
df

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

In [32]:
df.columns = df.columns.str.strip()

In [34]:
pd.pivot_table(
    data=df,
    index='Department',
    values='Salary',
    aggfunc='mean'
)

                   Salary
Department
FINANCE      51000.000000
HR           51666.666667
IT          198500.000000
SALES        32333.333333

In [35]:
pd.pivot_table(
    data=df,
    index='Department',
    values='Salary',
    aggfunc='sum'
)

               Salary
Department
FINANCE      153000.0
HR           155000.0
IT          1191000.0
SALES         97000.0

In [36]:
pd.pivot_table(
    data=df,
    index='Department',
    values='Salary',
    aggfunc=['sum', 'mean', 'max','min']
)

                  sum           mean        max      min
               Salary         Salary     Salary   Salary
Department
FINANCE      153000.0   51000.000000    55000.0  48000.0
HR           155000.0   51666.666667    53000.0  50000.0
IT          1191000.0  198500.000000  1000000.0      0.0
SALES         97000.0   32333.333333    47000.0  10000.0

In [37]:
pd.pivot_table(
    data=df,
    index='Department',
    columns='Employee ID',
    values='Salary',
    aggfunc=['sum', 'mean', 'max','min']
)

                 sum                                                      \
Employee ID      101      102      103  104      105      106        107
Department
FINANCE          NaN      NaN  55000.0  NaN      NaN      NaN        NaN
HR               NaN  50000.0      NaN  NaN      NaN  52000.0        NaN
IT           45000.0      NaN      NaN  0.0      NaN      NaN  1000000.0
SALES            NaN      NaN      NaN  NaN  40000.0      NaN        NaN

                                        ...      min                      \
Employee ID      108      109      110  ...      106        107      108
Department                              ...
FINANCE      48000.0      NaN      NaN  ...      NaN        NaN  48000.0
HR               NaN      NaN      NaN  ...  52000.0        NaN      NaN
IT               NaN      NaN  49000.0  ...      NaN  1000000.0      NaN
SALES            NaN  47000.0      NaN  ...      NaN        NaN      NaN


Employee ID      109      110      111      112      113      114      115
Department
FINANCE          NaN      NaN      NaN      NaN      NaN      NaN  50000.0
HR               NaN      NaN  53000.0      NaN      NaN      NaN      NaN
IT               NaN  49000.0      NaN      NaN  51000.0  46000.0      NaN
SALES        47000.0      NaN      NaN  10000.0      NaN      NaN      NaN

[4 rows x 60 columns]

In [38]:
pd.pivot_table(
    data=df,
    index='Department',
    columns='Employee ID',
    values='Salary',
    aggfunc=['sum', 'mean', 'max','min'],
    fill_value=0
)

                 sum                                                      \
Employee ID      101      102      103  104      105      106        107
Department
FINANCE          0.0      0.0  55000.0  0.0      0.0      0.0        0.0
HR               0.0  50000.0      0.0  0.0      0.0  52000.0        0.0
IT           45000.0      0.0      0.0  0.0      0.0      0.0  1000000.0
SALES            0.0      0.0      0.0  0.0  40000.0      0.0        0.0

                                        ...      min                      \
Employee ID      108      109      110  ...      106        107      108
Department                              ...
FINANCE      48000.0      0.0      0.0  ...      0.0        0.0  48000.0
HR               0.0      0.0      0.0  ...  52000.0        0.0      0.0
IT               0.0      0.0  49000.0  ...      0.0  1000000.0      0.0
SALES            0.0  47000.0      0.0  ...      0.0        0.0      0.0


Employee ID      109      110      111      112      113      114      115
Department
FINANCE          0.0      0.0      0.0      0.0      0.0      0.0  50000.0
HR               0.0      0.0  53000.0      0.0      0.0      0.0      0.0
IT               0.0  49000.0      0.0      0.0  51000.0  46000.0      0.0
SALES        47000.0      0.0      0.0  10000.0      0.0      0.0      0.0

[4 rows x 60 columns]

###### **pivot() vs pivot_table()**
| Feature                         | `pivot()` | `pivot_table()` |
| ------------------------------- | --------- | --------------- |
| Handles duplicates              | ❌ No      | ✅ Yes           |
| Aggregation                     | ❌ No      | ✅ Yes           |
| Functions like mean, sum, count | ❌ No      | ✅ Yes           |
| More flexible                   | ❌ No      | ✅ Yes           |