# **Pandas Library**
### **Accessing And Modifying Pandas Series()**

In [3]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,20,30,40,50],index=np.arange(5),dtype=int,name='Sales')
df.to_frame()

   Sales
0     10
1     20
2     30
3     40
4     50

#### **1 ACCESSING DATA IN SERIES :**
##### 1.1. Access by Label (Index) 
##### 1.2. Access by Position 
##### 1.3. Using .loc[]  
##### 1.4. Using .iloc[] 
##### 1.5. Access Multiple Values (Fancy Indexing) 
##### 1.6. Slicing  
##### 1.7. Boolean Indexing (Filtering) 
##### 1.8. Using .at[] (Fast single access) 
##### 1.9. Using .iat[] (Fast position access)

##### **1.1 Access by Lable/Index :** 
##### **Syntax : variable_name[index/label]**
##### We can access by given index or given label in index

In [7]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,20,30,40,50],index=np.arange(5),dtype=int,name='Sales')
df.to_frame()

   Sales
0     10
1     20
2     30
3     40
4     50

In [8]:
print(df[2])

30

In [9]:
print(df[4])

50

In [11]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,20,30,40,50],index=['L','B','D','C','A'],dtype=int,name='Sales')
df.to_frame()

   Sales
L     10
B     20
D     30
C     40
A     50

In [14]:
print(df['A'])

50

##### If the indexes are same it returns both index values

In [1]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=[1,2,1,2,3],name='Marks')
df.to_frame()

   Marks
1     76
2     65
1     59
2     58
3     63

In [2]:
df[1]

1    76
1    59
Name: Marks, dtype: int32

##### **1.2 Access by Position :** 
##### **Syntax : variable_name[position]**
##### If we have String index we can access the values based on index position(like 0,1,2,3,4 even thougjt actual indexes are in Alphabetic form)

In [18]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,20,30,40,50],index=['L','B','D','C','A'],dtype=int,name='Sales')
df.to_frame()

   Sales
L     10
B     20
D     30
C     40
A     50

In [22]:
print(df[0])

10

C:\Users\User\AppData\Local\Temp\ipykernel_3184\1138601271.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df[0])

In [23]:
print(df[4])

50

C:\Users\User\AppData\Local\Temp\ipykernel_3184\378488373.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df[4])

##### **1.3 Access by using loc[] : Location** 
##### **Syntax : variable_name.loc[row_index]**
##### **Syntax : variable_name.loc[start_row_index:end_row_index]**
##### **Syntax : variable_name.loc[start_row_index:end_row_index:step_index]**
##### We can access using location i.e, loc[] by passing row_index.
##### In Series() Only Single Row Indexing or Slicing will perform
##### **NOTE:** Start and Stop Index are inclusive

In [24]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,20,30,40,50],index=['L','B','D','C','A'],dtype=int,name='Sales')
df.to_frame()

   Sales
L     10
B     20
D     30
C     40
A     50

##### We can access or pass only one row throught indexing

In [35]:
print(df.loc['B'])

20

##### If we trying to access the multiple rows through indexing it will raise an error

In [36]:
print(df.loc['B','A'])

IndexingError: Too many indexers

##### We can access multiple rows through slicing only
##### **Note :** Here Start Index and Stop Index Both are Inclusive

In [37]:
print(df.loc['B':'A'])

B    20
D    30
C    40
A    50
Name: Sales, dtype: int64

In [38]:
print(df.loc['B':'A':2])

B    20
C    40
Name: Sales, dtype: int64

##### If we want to access any row through index or slicing , make sure that , Whatever indexing we are passed, only that indexing values we can pass inside square brackets []

In [42]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,20,30,40,50],index=[0,1,2,3,4],dtype=int,name='Sales')
df.to_frame()

   Sales
0     10
1     20
2     30
3     40
4     50

In [43]:
print(df.loc[0:4:2])

0    10
2    30
4    50
Name: Sales, dtype: int64

##### **1.4 Access by using iloc[] : Integer Location** 
##### **Syntax : variable_name.iloc[row_index]**
##### **Syntax : variable_name.iloc[start_row_index:end_row_index]**
##### **Syntax : variable_name.iloc[start_row_index:end_row_index:step_index]**
##### We can access using Integer location i.e, iloc[] by passing row_index.
##### In Series() Only Single Row Indexing or Slicing will perform
##### **NOTE:** Start is Inclusive and Stop Index is Exclusive in iloc[] and It only accepts the Integer Index or Slicing

In [45]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,20,30,40,50],index=[0,1,2,3,4],dtype=int,name='Sales')
df.to_frame()

   Sales
0     10
1     20
2     30
3     40
4     50

In [46]:
print(df.iloc[0])

10

##### **Note :** Start_index is inclusive and Stop_index is Exclusive

In [47]:
print(df.iloc[0:4])

0    10
1    20
2    30
3    40
Name: Sales, dtype: int64

In [48]:
print(df.iloc[0:6:2])

0    10
2    30
4    50
Name: Sales, dtype: int64

##### Here also I can't pass multiple index values at a time

In [49]:
print(df.iloc[0,3])

IndexingError: Too many indexers

In [53]:
import pandas as pd
import numpy as np
df = pd.Series(data=[100,200,300,400,500],index=['A','V','D','K','B'],dtype=int,name='Sales')
df.to_frame()

   Sales
A    100
V    200
D    300
K    400
B    500

##### We can pass only Integer indexes or slicers

In [51]:
print(df.iloc['A'])

TypeError: Cannot index by location index with a non-integer key

##### **Note :** even though we have passed index values as string but we can't access using string in iloc[], To access it we can make use of numeric index

In [54]:
print(df.iloc[0])

100

In [55]:
print(df.iloc[0:6])

A    100
V    200
D    300
K    400
B    500
Name: Sales, dtype: int64

In [56]:
print(df.iloc[0:6:2])

A    100
D    300
B    500
Name: Sales, dtype: int64

##### **1.5. Access Multiple Values (Fancy Indexing)**
##### **Syntax : variable_name[[index1]]**
##### **Syntax : variable_name[[index1,index2,index3]]**
##### Fancy Indexing meanse we have to pass one or multiple indexes in a list form , Based on that index It will returns an values for that index and also return column name and dtype.

In [8]:
import pandas as pd
import numpy as np
df = pd.Series(data=[100,200,300,400,500],index=[0,1,2,3,4],dtype=int,name='Sales')
df.to_frame()

   Sales
0    100
1    200
2    300
3    400
4    500

In [9]:
df[[0]]

0    100
Name: Sales, dtype: int64

In [10]:
df[[4,3,2,1,0]]

4    500
3    400
2    300
1    200
0    100
Name: Sales, dtype: int64

In [11]:
print(df[df > 200])

2    300
3    400
4    500
Name: Sales, dtype: int64

In [65]:
import pandas as pd
import numpy as np
df = pd.Series(data=[100,200,300,400,500],index=['A','B','C','D','E'],dtype=int,name='Marks')
df.to_frame()

   Marks
A    100
B    200
C    300
D    400
E    500

##### We can access using Default indexes or specified index both are performs same operation

In [67]:
df[[0,2,4]]

C:\Users\User\AppData\Local\Temp\ipykernel_3184\1897763332.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df[[0,2,4]]

A    100
C    300
E    500
Name: Marks, dtype: int64

In [66]:
df[['A','C','E']]

A    100
C    300
E    500
Name: Marks, dtype: int64

##### **1.6 Slicing**
##### **Syntax : variable_name[index]**
##### **Syntax : variable_name[start:stop]**
##### **Syntax : variable_name[start:stop:step]**
##### Slicing is used to get multiple values at a time and It returns the name and dtype
##### Slicing By Position : variable_name[1:2]
##### Slicing By Position : variable_name['A':'B']

In [68]:
import pandas as pd
import numpy as np
df = pd.Series(data=[100,200,300,400,500],index=['A','B','C','D','E'],dtype=int,name='Marks')
df.to_frame()

   Marks
A    100
B    200
C    300
D    400
E    500

In [73]:
print(df[1])
print(df['B'])

200
200

C:\Users\User\AppData\Local\Temp\ipykernel_3184\2395375108.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df[1])

In [71]:
print(df[0:5])

A    100
B    200
C    300
D    400
E    500
Name: Marks, dtype: int64

In [72]:
print(df['A':'E'])

A    100
B    200
C    300
D    400
E    500
Name: Marks, dtype: int64

In [74]:
print(df['A':'E':2])

A    100
C    300
E    500
Name: Marks, dtype: int64

##### **1.7. Boolean Indexing (Filtering)**
##### **Syntax : variable_name[condtion]
##### Based on Conditions it returns the values

In [82]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(100,1001,10),index=['A','B','C','D','E','F','G','H','I','J'],dtype=int,name='Growth')
df.to_frame()

   Growth
A     137
B     884
C     233
D     604
E     786
F     784
G     700
H     770
I     307
J     301

In [83]:
print(df[df>500])

B    884
D    604
E    786
F    784
G    700
H    770
Name: Growth, dtype: int64

In [84]:
print(df[df<500])

A    137
C    233
I    307
J    301
Name: Growth, dtype: int64

##### We can't pass multiple expression in Boolean Indexing

In [88]:
print(df[(df<300 and df>700)])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

##### **1.8 Using .at[] (Fast single access)**
##### **Syntax : variable_name.at[index]**
##### It also same as loc[] but it is used to access the element/values in faster way as compared to loc[] and Only one index we can passa at a time

In [90]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(100,1001,10),index=['A','B','C','D','E','F','G','H','I','J'],dtype=int,name='Growth')
df.to_frame()

   Growth
A     309
B     550
C     339
D     903
E     226
F     539
G     339
H     375
I     297
J     129

In [107]:
print(df['E'])

226

In [108]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(100,1001,10),index=np.arange(10),dtype=int,name='Growth')
df.to_frame()

   Growth
0     700
1     204
2     195
3     226
4     826
5     289
6     768
7     691
8     658
9     584

In [109]:
print(df[0])

700

##### With the help of time module we can check which one will access faster than other But we will not get correct output

In [96]:
import time 
start=time.time()
print(df.at['A'])
end=time.time()
print(f'Total Time {end-start}')

309
Total Time 0.0022401809692382812

In [97]:
import time 
start=time.time()
print(df.loc['A'])
end=time.time()
print(f'Total Time {end-start}')

309
Total Time 0.0014460086822509766

##### With the help of timeit module we can check which one will access faster than other

In [105]:
import timeit
stmt = "df.loc['A']"
setup = """
import pandas as pd
df = pd.Series({'A': 10, 'B': 20, 'C': 30})
"""
execution_time = timeit.timeit(stmt=stmt, setup=setup, number=100000)
print("Total Time:", execution_time)

Total Time: 1.5540738999843597

In [106]:
import timeit
stmt = "df.at['A']"
setup = """
import pandas as pd
df = pd.Series({'A': 10, 'B': 20, 'C': 30})
"""
execution_time = timeit.timeit(stmt=stmt, setup=setup, number=100000)
print("Total Time:", execution_time)

Total Time: 0.6943072000285611

##### We cannot pass multiple indexes

In [92]:
print(df.at['A','E'])

KeyError: ('A', 'E')

##### **1.9 Using .iat[] (Fast single access)**
##### **Syntax : variable_name.iat[index]**
##### It also same as iloc[] but it is used to access the element/values in faster way as compared to iloc[] and Only one index we can passa at a time

In [110]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(100,1001,10),index=['A','B','C','D','E','F','G','H','I','J'],dtype=int,name='Growth')
df.to_frame()

   Growth
A     187
B     792
C     299
D     968
E     934
F     608
G     766
H     340
I     576
J     634

In [112]:
print(df.iat['A'])

ValueError: iAt based indexing can only have integer indexers

In [113]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(100,1001,10),index=np.arange(10),dtype=int,name='Growth')
df.to_frame()

   Growth
0     244
1     163
2     236
3     163
4     215
5     945
6     339
7     332
8     789
9     105

In [114]:
print(df.iat[2])

236

In [120]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(100,1001,10),index=['A','B','C','D','E','F','G','H','I','J'],dtype=int,name='Growth')
df.to_frame()

   Growth
A     466
B     400
C     171
D     730
E     722
F     541
G     839
H     197
I     427
J     258

In [121]:
df['K']=1000
df.to_frame()

   Growth
A     466
B     400
C     171
D     730
E     722
F     541
G     839
H     197
I     427
J     258
K    1000

##### **NOTE :** When we want to work with multiple columns in Series(),First need to be concatenate the single columns to make as multiple columns(table).If we give different indexes it will take that index and returns the output
##### **Syntax : variable_name.loc[row_index,colum_name]**
##### **Syntax : variable_name.loc[row_start:row_end , colum_name_start:column_name_end]**
##### **Syntax : variable_name.loc[row_start:row_end:step , colum_name_start:column_name_end:step]**

In [136]:
import pandas as pd
import numpy as np
s1 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks1')
s2 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks2')
s3 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks3')
s4 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks4')
s5 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks5')
df = pd.concat([s1,s2,s3,s4,s5], axis=1)
df

   Marks1  Marks2  Marks3  Marks4  Marks5
1      83      86      67      90      96
2      83      83      70      81      64
3      90      54      67      95      52
4      83      95      69      85      50

In [139]:
print(df.loc[1,'Marks1'])

83

In [141]:
d=df.loc[1:4,'Marks1']
d.to_frame()

   Marks1
1      83
2      83
3      90
4      83

In [143]:
df.loc[1:4,'Marks1':'Marks2']

   Marks1  Marks2
1      83      86
2      83      83
3      90      54
4      83      95

In [144]:
df.loc[1:4,'Marks1':'Marks5']

   Marks1  Marks2  Marks3  Marks4  Marks5
1      83      86      67      90      96
2      83      83      70      81      64
3      90      54      67      95      52
4      83      95      69      85      50

In [145]:
df.loc[1:4,'Marks1':'Marks5':2]

   Marks1  Marks3  Marks5
1      83      67      96
2      83      70      64
3      90      67      52
4      83      69      50

In [146]:
df.loc[1:4:2,'Marks1':'Marks5':2]

   Marks1  Marks3  Marks5
1      83      67      96
3      90      67      52

##### **We can do with respect to i;oc[] also**

In [149]:
df.iloc[0:4:2,0:5:2]

   Marks1  Marks3  Marks5
1      83      67      96
3      90      67      52

#### **2 MODIFYING DATA IN SERIES :**
##### 2.1. Modify Single Value 
##### 2.2. Modify using .loc 
##### 2.3. Modify using .iloc 
##### 2.4. Modify Multiple Values 
##### 2.5. Modify using Condition 
##### 2.6. Add New Element 
##### 2.7. Delete Element 
##### 2.8. Replace Values 
##### 2.9. Apply Function 
##### 2.10. Modify Data Type

##### **2.1. Modify Single Value**
##### **Syntax : variable_name[index/position/label]=NewValue**

In [122]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     74
1     59
2     64
3     70
4     61

##### Here we can update values using index position.
##### **Note** : Suppose if the index is not present in the data/array/table, then by default it will add the new value to that index position

In [123]:
df[0]=100
df.to_frame()

   Marks
0    100
1     59
2     64
3     70
4     61

In [124]:
df[5]=50
df.to_frame()

   Marks
0    100
1     59
2     64
3     70
4     61
5     50

##### If we want to work with multiple columns we can merge we can do

In [133]:
import pandas as pd
import numpy as np
df1 = pd.Series(data=np.random.randint(100,1001,10),index=np.arange(10),dtype=int,name='Growth')
df2 = pd.Series(data=np.random.randint(100,1001,10),index=np.arange(10),dtype=int,name='Growth')
df3= pd.Series(data=np.random.randint(100,1001,10),index=np.arange(10),dtype=int,name='Growth')
df4 = pd.Series(data=np.random.randint(100,1001,10),index=np.arange(10),dtype=int,name='Growth')
df5 = pd.Series(data=np.random.randint(100,1001,10),index=np.arange(10),dtype=int,name='Growth')
df=pd.concat([df1,df2,df3,df4,df5],axis=1)
df

   Growth  Growth  Growth  Growth  Growth
0     770     907     308     898     121
1     992     959     795     850     395
2     325     880     540     683     900
3     221     234     107     265     774
4     319     719     154     117     662
5     500     655     696     887     905
6     789     370     422     401     129
7     319     829     788     631     990
8     622     744     488     788     744
9     892    1000     523     944     303

##### **2.2. Modify Using loc[]**
##### **Syntax : variable_name.loc[index/position/label]=NewValue**

In [159]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     67
1     72
2     66
3     65
4     74

##### With the help of indexing we can modify single data/values

In [160]:
df.loc[0]=100
df.to_frame()

   Marks
0    100
1     72
2     66
3     65
4     74

##### With the help of slicing we can modify entire data/values

In [161]:
df.loc[0:4]=100
df.to_frame()

   Marks
0    100
1    100
2    100
3    100
4    100

##### If we want to add or insert the new row we can insert it directly

In [162]:
df.loc[5]=200
df.to_frame()

   Marks
0    100
1    100
2    100
3    100
4    100
5    200

##### **2.3. Modify Using iloc[]**
##### **Syntax : variable_name.loc[index(only integer)]=NewValue**

In [163]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     78
1     67
2     77
3     79
4     72

##### With the help of indexing we can modify single data/values

In [164]:
df.iloc[0]=100
df.to_frame()

   Marks
0    100
1     67
2     77
3     79
4     72

##### With the help of slicing we can modify entire data/values

In [167]:
df.iloc[0:5]=100
df.to_frame()

   Marks
0    100
1    100
2    100
3    100
4    100

##### If we want to add or insert the new row we can't insert in iloc[], iloc[] can't be changed their target

In [166]:
df.iloc[5]=100
df.to_frame()

IndexError: iloc cannot enlarge its target object

##### **2.4. Modify Multiple Values(Fancy Indexing)**
##### **Syntax : variable_name[[index1,index2,...,indexn]=[NewValue1,NewValue2,.....NewValuen]**

In [168]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     58
1     60
2     64
3     77
4     56

In [169]:
df[[0,2,4]]=[100,200,300]
df.to_frame()

C:\Users\User\AppData\Local\Temp\ipykernel_3184\3720754042.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[100, 200, 300]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  df[[0,2,4]]=[100,200,300]

   Marks
0    100
1     60
2    200
3     77
4    300

##### **2.5. Modify Using Boolean Indexing(Filtering)**
##### **Syntax : variable_name[condition]=NewValue**
##### **Note :** The NewValue will update on entire data

In [170]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     61
1     72
2     61
3     78
4     56

In [171]:
df[df>70]=100
df.to_frame()

   Marks
0     61
1    100
2     61
3    100
4     56

##### If we want to update single value we can use == double equal to so only that value will modifies

In [172]:
df[df==61]=500
df.to_frame()

   Marks
0    500
1    100
2    500
3    100
4     56

##### **2.6. Update Using Add New Element**
##### **Syntax : variable_name[NewIndex/Position/Label]=NewValue**
##### **Note :** The NewValue will update an stores at last

In [173]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     54
1     76
2     64
3     57
4     56

In [177]:
df[5]=83
df.to_frame()

   Marks
0     54
1     76
2     64
3     57
4     56
5     83

##### **2.7 Delete Element**
##### **Syntax : var_name = variableName.drop(index/position/lable)**

In [178]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     60
1     78
2     60
3     61
4     76

In [182]:
d=df.drop(0)
d.to_frame()

   Marks
1     78
2     60
3     61
4     76

##### **2.8. Replace Values**
##### **Syntax : variable_name.replace('OldValue','NewValue')**

In [183]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     52
1     74
2     71
3     72
4     65

In [188]:
d=df.replace(72,89)
d.to_frame()

   Marks
0     52
1     74
2     71
3     89
4     65

##### **2.9. Apply Function**
##### **Syntax : variable_name.apply(operation)**

In [196]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     64
1     70
2     51
3     53
4     57

In [197]:
df=df.apply(lambda df: df + 10)
df.to_frame()

   Marks
0     74
1     80
2     61
3     63
4     67

##### **2.10. Modify Data Type**
##### **Syntax : variable_name.astype(specificDataType)**

In [201]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name="Marks")
df.to_frame()

   Marks
0     54
1     59
2     78
3     62
4     51

In [203]:
df=df.astype(dtype=float)
df.to_frame()

   Marks
0   54.0
1   59.0
2   78.0
3   62.0
4   51.0

##### Additionally If we add Null Values, By default it going to convert None to NaN(not a Number)

In [207]:
df[4]=None
df.to_frame()

   Marks
0   54.0
1   59.0
2   78.0
3   62.0
4    NaN

##### **Accesing the Series() Attributes:**

In [1]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,20,30,40,50],index=np.arange(5),dtype=int,name='Sales')
df.to_frame()

   Sales
0     10
1     20
2     30
3     40
4     50

In [2]:
print(df.name)

Sales

In [4]:
print(df.dtype)

int64

In [5]:
print(df.index)

Index([0, 1, 2, 3, 4], dtype='int64')