# **Pandas Library**
### **Conversion Methods of Pandas Series()**

#### **1. Conversion Methods**
##### 1.1 astype()
##### 1.2 tolist()
##### 1.3 to_numpy()
##### 1.4 to_dict()
##### 1.5 copy()
##### 1.6 to_frame()
##### 1.7 to_string()
##### 1.8 to_json()
##### 1.9 to_csv()

##### **1.1 astype()**
##### **Syntax : var_name.astype(dtype, copy=True, errors='raise')**
##### **Parameters:**
##### dtype → target datatype (int, float, str, etc.)
##### copy → return new object (default True)
##### errors → 'raise' or 'ignore'

In [2]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0     53
1     68
2     61
3     61
4     66

In [4]:
df.astype(dtype=float)

0    53.0
1    68.0
2    61.0
3    61.0
4    66.0
Name: Marks, dtype: float64

##### **1.2 tolist()**
##### Convert Series → Python list
##### **Syntax : var_name.tolist()** or
##### **Syntax : var_name.to_list()**

In [5]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0     54
1     73
2     54
3     73
4     52

In [6]:
df.to_list()

[54, 73, 54, 73, 52]

##### **1.3 to_numpy()**
##### Convert to numpy array
##### **Syntax : var_name.to_numpy(dtype=None, copy=False, na_value=None)**
##### dtype,copy and na_value are optional

In [9]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0     57
1     79
2     52
3     51
4     71

##### Data is converted into numpy array

In [10]:
df.to_numpy()

array([57, 79, 52, 51, 71], dtype=int32)

In [25]:
import pandas as pd
import numpy as np
df = pd.Series(data=[12,90,None,98,None],index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0   12.0
1   90.0
2    NaN
3   98.0
4    NaN

##### NaN values converted to 0 if na_value is False

In [23]:
df.to_numpy(na_value=False)

array([12., 90.,  0., 98.,  0.])

##### NaN values converted to 0 if na_value is True

In [26]:
df.to_numpy(na_value=True)

array([12., 90.,  1., 98.,  1.])

##### **1.4 to_dict()**
##### Convert to dictionary
##### **Syntax : var_name.to_dict()**

In [35]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0     51
1     74
2     72
3     58
4     74

In [42]:
df.to_dict

<bound method Series.to_dict of 0    51
1    74
2    72
3    58
4    74
Name: Marks, dtype: int32>

##### **1.5 copy()**
##### Creates copy of object
##### **Syntax : var_name.copy()**

In [43]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0     61
1     51
2     70
3     78
4     74

In [44]:
d=df.copy()

In [45]:
d.to_frame()

   Marks
0     61
1     51
2     70
3     78
4     74

In [46]:
df.to_frame()

   Marks
0     61
1     51
2     70
3     78
4     74

In [47]:
d[0]=100
d.to_frame()

   Marks
0    100
1     51
2     70
3     78
4     74

In [48]:
df.to_frame()

   Marks
0     61
1     51
2     70
3     78
4     74

##### **1.6 to_frame(name=None)()**
##### CConvert Series → DataFrame
##### **Syntax : var_name.to_frame(name=None)**

In [49]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0     70
1     53
2     63
3     61
4     54

In [50]:
df.to_frame(name='Sales')

   Sales
0     70
1     53
2     63
3     61
4     54

##### **1.7 to_string()**
##### CConvert Series → String
##### **Syntax : var_name.to_string()**

In [53]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),name='Marks')
df.to_frame()

   Marks
0     55
1     75
2     54
3     77
4     58

In [54]:
df.to_string()

'0    55\n1    75\n2    54\n3    77\n4    58'

##### **1.8 to_json()**
##### Convert to JSON format
##### **Syntax : var_name.to_json(path_or_buf=None)**

In [55]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0     50
1     56
2     53
3     63
4     72

##### If we specified the path then, We will get json form data to that file Hello_json.json file

In [59]:
df.to_json('Hello_Json.json')

##### If json file is not present , it will created a json file and stores the json data.

In [65]:
df.to_json('JSON.json')

##### **1.9 to_csv()**
##### Convert to CSV format
##### **Syntax : var_name.to_csv("data.csv", index=False)**

In [60]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(50,80,5),index=np.arange(5),name='Marks')
df.to_frame()

   Marks
0     79
1     67
2     64
3     70
4     52

In [61]:
df.to_csv()

',Marks\r\n0,79\r\n1,67\r\n2,64\r\n3,70\r\n4,52\r\n'

##### If csv file is not present , it will created a csv file and stores the csv data. By default index value is True

In [62]:
df.to_csv('data.csv')

##### If index=False means it will not store the index values in csv file

In [64]:
df.to_csv('data1.csv',index=False)