# **Pandas Library**
### **Attributes in Pandas DataFrame()**

##### 1. df.shape : Returns number of rows and columns
##### 2. df.size : Total number of elements
##### 3. df.ndim : Number of dimensions, Always 2 for DataFrame
##### 4. df.index : Row labels
##### 5. df.columns : Column labels
##### 6. df.dtypes : Data types of each column
##### 7. df.values : Returns data as NumPy array(Now prefer to_numpy())
##### 8. df.axes : List of index + columns
##### 9. df.empty : Checks if DataFrame is empty
##### 10. df.T : Transpose (rows ↔ columns)
##### 11. df.attrs : Custom metadata dictionary Syntax : df.attrs['source'] = 'HR Dataset'
##### 12. df.shape[0] : Number of rows

#### **WHAT ARE ATTRIBUTES?**
##### Attributes are **properties (no brackets `()`)** used to **inspect DataFrame structure and metadata**
##### df.shape   ✔ attribute
##### df.head()  ❌ method

##### **1. df.shape :** Returns number of rows and columns in the form of tuple.

In [1]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [2]:
df.shape

(5, 8)

##### **2. df.size :** Total number of elements

In [15]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [3]:
df.size

40

##### **3. df.ndim :** Number of dimensions, Always 2 for DataFrame

In [16]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [4]:
df.ndim

2

##### **4. df.index :** Row labels

In [17]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [5]:
df.index

Index([1, 2, 3, 4, 5], dtype='int64')

##### **5. df.columns :** Column labels

In [18]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [6]:
df.columns

Index(['Student_ID', 'Names', 'Marks1', 'Marks2', 'Marks3', 'Marks4', 'Marks5',
       'Marks6'],
      dtype='object')

##### **6. df.dtypes :** Data types of each column

In [19]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [7]:
df.dtypes

Student_ID     int64
Names         object
Marks1         int64
Marks2         int64
Marks3         int64
Marks4         int64
Marks5         int64
Marks6         int64
dtype: object

##### **7. df.values :** Returns data as NumPy array(Now prefer to_numpy())

In [20]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [8]:
df.values

array([[101, 'Aftab', 70, 50, 40, 75, 65, 70],
       [102, 'Smith', 75, 55, 45, 80, 70, 75],
       [103, 'Scott', 80, 60, 50, 85, 75, 80],
       [104, 'Bob', 85, 65, 55, 90, 80, 85],
       [105, 'Jhon', 90, 70, 60, 95, 85, 90]], dtype=object)

In [10]:
df.to_numpy()

array([[101, 'Aftab', 70, 50, 40, 75, 65, 70],
       [102, 'Smith', 75, 55, 45, 80, 70, 75],
       [103, 'Scott', 80, 60, 50, 85, 75, 80],
       [104, 'Bob', 85, 65, 55, 90, 80, 85],
       [105, 'Jhon', 90, 70, 60, 95, 85, 90]], dtype=object)

##### **8. df.axes :** List of index + columns

In [21]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [11]:
df.axes

[Index([1, 2, 3, 4, 5], dtype='int64'),
 Index(['Student_ID', 'Names', 'Marks1', 'Marks2', 'Marks3', 'Marks4', 'Marks5',
        'Marks6'],
       dtype='object')]

##### **9. df.empty :** Checks if DataFrame is empty
##### True -> If Data Frame has no rows.
##### False -> Even if data contains empty values.

In [22]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [12]:
df.empty

False

In [26]:
df1=pd.DataFrame(data=[1,2,'',3,4])

In [27]:
df1

   0
0  1
1  2
2
3  3
4  4

In [28]:
df1.empty

False

In [29]:
df2=pd.DataFrame()

In [31]:
df2

Empty DataFrame
Columns: []
Index: []

In [30]:
df2.empty

True

##### **10. df.T :** Transpose (rows ↔ columns)

In [13]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [14]:
df.T

                1      2      3    4     5
Student_ID    101    102    103  104   105
Names       Aftab  Smith  Scott  Bob  Jhon
Marks1         70     75     80   85    90
Marks2         50     55     60   65    70
Marks3         40     45     50   55    60
Marks4         75     80     85   90    95
Marks5         65     70     75   80    85
Marks6         70     75     80   85    90

##### **11. df.shape[0] :** Number of rows

In [50]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [52]:
df.shape[0]

5

##### **12. df.shape[1] :** Number of columns

In [53]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [54]:
df.shape[1]

8