# **Pandas Library**
### **Merging Multiple DataFrames**

##### **Merging Multiple DataFrames :**
##### To merge multiple DataFrames in pandas we have mainly 3 different ways.
##### 1.Concat
##### 2.Merge
##### 3.Join

In [3]:
import pandas as pd
import numpy as np
df1=pd.read_csv("Employee_Cleaned_Dataset.csv")
df1.drop(columns='Unnamed: 0', inplace=True)
df1

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

In [2]:
df2=pd.read_csv("Employee_Cleaned_Dataset.csv")
df2.drop(columns='Unnamed: 0', inplace=True)
df2

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

##### **1. Concat() :**
##### It is used to merge multiple DataFrames in both ways (row_wise,col_wise)
##### To perform concatenation we use pandas inbuilt method **concat()**
##### Concatenation has been classified into two types :
##### 1.Vertical Concatenation() - Row Wise
##### 2.Horizontal Concatenation() - Column Wise

##### **1.1 Vertical Concatenation() - Row Wise :**
##### While performing vertical concatenation, it is manadatory to check whether we have same column names in all the dataframes. If we have different column names it returns null values.
##### **Syntax : pd.concat([DataFrame1,DataFrame2....],axis=0,ignore_index=True)**

In [4]:
pd.concat([df1,df2])

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

In [5]:
pd.concat([df1,df2],axis=0)

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

In [6]:
pd.concat([df1,df2],axis=0,ignore_index=True)

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad
15,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
16,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
17,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
18,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
19,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
20,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
21,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
22,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
23,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
24,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
25,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
26,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
27,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
28,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
29,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

In [7]:
pd.concat([df1,df2],axis=0,ignore_index=False)

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

##### **1.2 Horizontal Concatenation() - Column Wise :**
##### While performing Horizontal concatenation,If we have any common column names it will create duplicates of those columns.If we have totally different column names then we go with column wise concatenation.
##### **Syntax : pd.concat([DataFrame1,DataFrame2....],axis=1,ignore_index=True)**

In [12]:
pd.concat([df1,df2],axis=1)

,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City,Employee ID,Employee Name,Age,Gender,Department,Salary,Joining Date,Phone Number,City
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

In [13]:
pd.concat([df1,df2],axis=1,ignore_index=True)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi,101,Aftab,23,Male,IT,45000.0,2023-01-15,9876543210,Belagavi
1,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore,102,Rahul,25,Unknown,HR,50000.0,2022-03-20,9876543211,Bangalore
2,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore,103,Priya,0,Female,FINANCE,55000.0,2021-05-10,9876543212,Mysore
3,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli,104,Anjali,22,Unknown,IT,0.0,2023-07-01,9876543213,Hubli
4,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad,105,Rohan,17,Male,SALES,40000.0,2024-02-15,9876543214,Dharwad
5,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi,106,Meena,65,Unknown,HR,52000.0,2020-08-11,9876543215,Belagavi
6,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore,107,Vikas,28,Male,IT,1000000.0,2022-09-05,9876543216,Bangalore
7,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore,108,Arjun,24,Unknown,FINANCE,48000.0,2021-12-01,9876543217,Mysore
8,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli,109,Sneha,26,Female,SALES,47000.0,2023-04-18,9876543218,Hubli
9,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad,110,Kiran,27,Unknown,IT,49000.0,2022-06-30,9876543219,Dharwad
10,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi,111,Pooja,0,Unknown,HR,53000.0,2021-11-20,0,Belagavi
11,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore,112,Rakesh,29,Male,SALES,10000.0,2022-10-10,9876543221,Bangalore
12,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore,113,Divya,24,Unknown,IT,51000.0,2023-02-14,9876543222,Mysore
13,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli,114,Akash,0,Male,IT,46000.0,2022-07-25,9876543223,Hubli
14,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad,115,Nisha,25,Unknown,FINANCE,50000.0,NaN,9876543224,Dharwad

##### **NOTE :**
##### When we use ignore_index=True, It returns column index instead of column names.
##### When we have duplicate columns we use :
##### a) df.T.drop_duplicates().T # Transpose
##### b) df.loc[:,~(df.columns.duplicated())] # Bitwise
##### c) Selecting columns(using fancy indexing) :
##### df=df[['col1','col2','col3']] or df=df.iloc[:,[col_index,col_index,....]]

##### **2. Merge :**
##### It is used to merge two dataframes. Merge will perform internally SQL style join operations.
##### **Syntax : pd.merge(df1,df2,on='common_column_name',how='inner/outer/left/right/cross')**
##### The default value of how is inner, If we are not providing any common column name it takes by default first common column name.

In [48]:
df1 = pd.DataFrame({
    'ID': [101, 102, 103],
    'Name': ['Aftab', 'John', 'Alice']
})
df1

    ID   Name
0  101  Aftab
1  102   John
2  103  Alice

In [47]:
df2 = pd.DataFrame({
    'ID': [102, 103, 104],
    'Salary': [50000, 60000, 70000]
})
df2

    ID  Salary
0  102   50000
1  103   60000
2  104   70000

In [19]:
pd.merge(df1, df2, on='ID')

    ID   Name  Salary
0  102   John   50000
1  103  Alice   60000

##### **Inner Join (Default)** : Returns only matching records from both DataFrames.

In [20]:
pd.merge(df1, df2, on='ID', how='inner')

    ID   Name  Salary
0  102   John   50000
1  103  Alice   60000

##### **Outer Join :** Returns all records from both DataFrames.

In [21]:
pd.merge(df1, df2, on='ID', how='outer')

    ID   Name   Salary
0  101  Aftab      NaN
1  102   John  50000.0
2  103  Alice  60000.0
3  104    NaN  70000.0

##### **Left Join :** Returns all records from the left DataFrame (df1) and matching records from df2

In [22]:
pd.merge(df1, df2, on='ID', how='left')

    ID   Name   Salary
0  101  Aftab      NaN
1  102   John  50000.0
2  103  Alice  60000.0

##### **Right Join :** Returns all records from the right DataFrame (df2) and matching records from df1.

In [23]:
pd.merge(df1, df2, on='ID', how='right')

    ID   Name  Salary
0  102   John   50000
1  103  Alice   60000
2  104    NaN   70000

##### **Cross Join :** Creates every possible combination of rows from both DataFrames.

In [25]:
pd.merge(df1, df2, how='cross')

   ID_x   Name  ID_y  Salary
0   101  Aftab   102   50000
1   101  Aftab   103   60000
2   101  Aftab   104   70000
3   102   John   102   50000
4   102   John   103   60000
5   102   John   104   70000
6   103  Alice   102   50000
7   103  Alice   103   60000
8   103  Alice   104   70000

##### **NOTE :**
##### inner → Matching rows only
##### left → All rows from left DataFrame
##### right → All rows from right DataFrame
##### outer → All rows from both DataFrames
##### cross → Cartesian product (all possible combinations)

##### **3. Join() :**
##### It is used to join dataframes based on index. Join will perform index style operation. For join internally performs left join operations.
##### **Syntax : df1.join(df2,how='inner/outer/left/right')**

In [37]:
df1 = pd.DataFrame({
    'EID': [101, 102, 103],
    'Name': ['Aftab','Priya','Alice']
})
df1

   EID   Name
0  101  Aftab
1  102  Priya
2  103  Alice

In [38]:
df2 = pd.DataFrame({
    'ID': [102, 103, 104],
    'Salary': [50000, 60000, 70000]
})
df2

    ID  Salary
0  102   50000
1  103   60000
2  104   70000

In [39]:
df1.join(df2)

   EID   Name   ID  Salary
0  101  Aftab  102   50000
1  102  Priya  103   60000
2  103  Alice  104   70000

In [40]:
df1.join(df2,how='left')

   EID   Name   ID  Salary
0  101  Aftab  102   50000
1  102  Priya  103   60000
2  103  Alice  104   70000

In [41]:
df1.join(df2,how='right')

   EID   Name   ID  Salary
0  101  Aftab  102   50000
1  102  Priya  103   60000
2  103  Alice  104   70000

In [42]:
df1.join(df2,how='inner')

   EID   Name   ID  Salary
0  101  Aftab  102   50000
1  102  Priya  103   60000
2  103  Alice  104   70000

In [43]:
df1.join(df2,how='outer')

   EID   Name   ID  Salary
0  101  Aftab  102   50000
1  102  Priya  103   60000
2  103  Alice  104   70000

In [44]:
df1.join(df2,how='cross')

   EID   Name   ID  Salary
0  101  Aftab  102   50000
1  101  Aftab  103   60000
2  101  Aftab  104   70000
3  102  Priya  102   50000
4  102  Priya  103   60000
5  102  Priya  104   70000
6  103  Alice  102   50000
7  103  Alice  103   60000
8  103  Alice  104   70000

##### **Error: ValueError:** columns overlap but no suffix specified
##### **Reason:** Two DataFrames contain one or more columns with the same name, and join() cannot determine how to rename them

In [50]:
df1

    ID   Name
0  101  Aftab
1  102   John
2  103  Alice

In [49]:
df2

    ID  Salary
0  102   50000
1  103   60000
2  104   70000

In [51]:
df1.join(df2)

ValueError: columns overlap but no suffix specified: Index(['ID'], dtype='object')

In [52]:
df1.join(df2, lsuffix='_left', rsuffix='_right')

   ID_left   Name  ID_right  Salary
0      101  Aftab       102   50000
1      102   John       103   60000
2      103  Alice       104   70000

In [53]:
df1.join(df2, lsuffix='_left', rsuffix='_right',how='left')

   ID_left   Name  ID_right  Salary
0      101  Aftab       102   50000
1      102   John       103   60000
2      103  Alice       104   70000

In [54]:
df1.join(df2, lsuffix='_left', rsuffix='_right',how='right')

   ID_left   Name  ID_right  Salary
0      101  Aftab       102   50000
1      102   John       103   60000
2      103  Alice       104   70000

In [55]:
df1.join(df2, lsuffix='_left', rsuffix='_right',how='inner')

   ID_left   Name  ID_right  Salary
0      101  Aftab       102   50000
1      102   John       103   60000
2      103  Alice       104   70000

In [56]:
df1.join(df2, lsuffix='_left', rsuffix='_right',how='outer')

   ID_left   Name  ID_right  Salary
0      101  Aftab       102   50000
1      102   John       103   60000
2      103  Alice       104   70000

In [57]:
df1.join(df2, lsuffix='_left', rsuffix='_right',how='cross')

   ID_left   Name  ID_right  Salary
0      101  Aftab       102   50000
1      101  Aftab       103   60000
2      101  Aftab       104   70000
3      102   John       102   50000
4      102   John       103   60000
5      102   John       104   70000
6      103  Alice       102   50000
7      103  Alice       103   60000
8      103  Alice       104   70000

##### **Note :**
##### join() joins DataFrames using their index by default.
##### It is similar to merge(), but simpler when joining on indexes.
##### Default value of how is 'left'.