# **Pandas Library**
### **Attributes of Pandas Series()**

#### **1. Basic Attributes/Core Attributes of Pandas Series()**
##### 1.1 var_name.index` → labels/indexes
##### 1.2 var_name.values` → data (NumPy array)
##### 1.3 var_name.dtype` → data type
##### 1.4 var_name.shape` → size (tuple)
##### 1.5 var_name.size` → number of elements
##### 1.6 var_name.ndim` → dimension (always 1)
##### 1.7 var_name.name` → name of Series
##### 1.8 var_name.axes` → list of index

#### **1. Basic Attributes/Core Attributes of Pandas Series()**
##### **1.1 var_name.index**
##### It return index number or labels or positions
##### **Syntax : var_name.index**

##### **Note 1.1 :** Suppose If we are not specify the index numbers then Series() it will take index from 0 to n-1 as a default indexs. and It return the index as (start=0,stop=n-1,step=1) Because it is default index

In [9]:
df = pd.Series(data=np.random.randint(60,90,5),name='Sales')
df.to_frame()

   Sales
0     78
1     77
2     75
3     71
4     89

In [10]:
df.index

RangeIndex(start=0, stop=5, step=1)

##### **Note 1.2 :** Suppose If we are specify the index numbers then Series() it will take index from specified index. and It return the index as Specified ( [0,1,2,3,4]) in the form of list. Because it will take from specified index

In [3]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(60,90,5),index=np.arange(5),dtype=int,name='Sales')
df.to_frame()

   Sales
0     89
1     87
2     68
3     81
4     62

In [4]:
df.index

Index([0, 1, 2, 3, 4], dtype='int64')

In [5]:
df = pd.Series(data=np.random.randint(60,90,5),index=np.random.randint(10,40,5),dtype=int,name='Sales')
df.to_frame()

    Sales
19     64
25     67
29     73
14     68
12     62

In [6]:
df.index

Index([19, 25, 29, 14, 12], dtype='int32')

##### **Note 1.3 :** Suppose If we are specify the indexs and Alphabets then Series() it will take index alphabets from specified index. and It return the index as Specified ( ['A','L','P','C','N']) in the form of list. Because it will take from specified index

In [7]:
df = pd.Series(data=np.random.randint(60,90,5),index=np.random.choice(['A','C','L','N','P'],5,replace=False),dtype=int,name='Sales')
df.to_frame()

   Sales
A     84
L     81
P     76
C     86
N     75

In [8]:
df.index

Index(['A', 'L', 'P', 'C', 'N'], dtype='object')

##### **1.2 var_name.values**
##### It return values or data
##### **Syntax : var_name.values**

In [11]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(60,90,5),index=np.arange(5),dtype=int,name='Sales')
df.to_frame()

   Sales
0     86
1     84
2     79
3     87
4     63

In [12]:
df.values

array([86, 84, 79, 87, 63])

##### **1.3 var_name.dtype**
##### It return the data type
##### **Syntax : var_name.dtype**

In [14]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(60,90,5),index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     65
1     64
2     71
3     76
4     62

In [15]:
df.dtype

dtype('int32')

##### **1.4 var_name.shape**
##### It return the size of the array/data in the form of tuple(,), i.e, 1D shape for Series()
##### **Syntax : var_name.shape**

In [16]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(60,90,5),index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     65
1     84
2     88
3     85
4     64

In [17]:
df.shape

(5,)

##### **1.5 var_name.size**
##### It return the total number of elements/data in the array/data.
##### **Syntax : var_name.size**

In [20]:
import pandas as pd
import numpy as np
df = pd.Series(data=[10,[1,2,3],4,5,6],index=np.arange(5),name='Sales')
df.to_frame()

       Sales
0         10
1  [1, 2, 3]
2          4
3          5
4          6

In [21]:
df.size

5

##### **1.6 var_name.ndim**
##### It return the dimension of array/data. In Series() dimension is always 1
##### **Syntax : var_name.ndim**

In [22]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(60,90,5),index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     72
1     70
2     82
3     63
4     61

In [23]:
df.ndim

1

##### **1.7 var_name.name**
##### It return the column name/Name of the series.
##### **Syntax : var_name.name**

In [29]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(60,90,5),index=[1,4,5,2,6],name='Sales')
df.to_frame()

   Sales
1     70
4     83
5     69
2     64
6     77

In [30]:
df.name

'Sales'

##### **1.8 var_name.axes**
##### It return the list of indexs.
##### **Syntax : var_name.axes**

In [31]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(60,90,5),index=[1,4,5,2,6],name='Sales')
df.to_frame()

   Sales
1     75
4     74
5     60
2     77
6     65

In [32]:
df.axes

[Index([1, 4, 5, 2, 6], dtype='int64')]

##### **Note :** If we want to work with Multiple Series then we must concat() them to make it Multiple Sereis().

#### **Attributes for Multiple Pandas Series()**
##### 1.1 var_name.index` → labels/indexes - It returns indexes of Multiple Series(DataFrame)
##### 1.2 var_name.values` → data (NumPy array) - It returns all the values in row and column wise (2D array form)
##### 1.3 var_name.dtypes` → data type - It returns the data types with respect to column name
##### 1.4 var_name.shape` → size (tuple) - It returns the shape of the array (no.of rows,no.of columns)
##### 1.5 var_name.size` → number of elements - It returns total number of elements
##### 1.6 var_name.ndim` → dimension (always 1) - It returns dimension of the array (2D)
##### 1.7 var_name.columns` → name of Series - It returns all the column names
##### 1.8 var_name.axes` → list of index - It returns the indexs of columns and column names.

In [35]:
import pandas as pd
import numpy as np
df1 = pd.Series(data=np.random.randint(60,90,5),index=[1,4,5,2,6],name='Sales1')
df2 = pd.Series(data=np.random.randint(60,90,5),index=[1,4,5,2,6],name='Sales2')
df3 = pd.Series(data=np.random.randint(60,90,5),index=[1,4,5,2,6],name='Sales3')
df4 = pd.Series(data=np.random.randint(60,90,5),index=[1,4,5,2,6],name='Sales4')
df5 = pd.Series(data=np.random.randint(60,90,5),index=[1,4,5,2,6],name='Sales5')
df = pd.concat([df1,df2,df3,df4,df5],axis=1)
df

   Sales1  Sales2  Sales3  Sales4  Sales5
1      87      67      77      87      83
4      76      77      63      84      88
5      81      69      73      64      70
2      75      75      71      77      84
6      68      70      81      69      63

In [36]:
df.index

Index([1, 4, 5, 2, 6], dtype='int64')

In [37]:
df.values

array([[87, 67, 77, 87, 83],
       [76, 77, 63, 84, 88],
       [81, 69, 73, 64, 70],
       [75, 75, 71, 77, 84],
       [68, 70, 81, 69, 63]], dtype=int32)

In [44]:
df.dtypes

Sales1    int32
Sales2    int32
Sales3    int32
Sales4    int32
Sales5    int32
dtype: object

In [39]:
df.shape

(5, 5)

In [40]:
df.size

25

In [41]:
df.ndim

2

In [45]:
df.columns

Index(['Sales1', 'Sales2', 'Sales3', 'Sales4', 'Sales5'], dtype='object')

In [46]:
df.axes

[Index([1, 4, 5, 2, 6], dtype='int64'),
 Index(['Sales1', 'Sales2', 'Sales3', 'Sales4', 'Sales5'], dtype='object')]

##### **NOTE :** 
##### df.index -> returns labels/indexs/position. 
##### df.axes -> returns list of indexs

#### **2. Other Important Attributes :**
##### 2.1 var_name.empty
##### 2.2 var_name.hasnans
##### 2.3 var_name.is_unique
##### 2.4 var_name.is_monotonic_increasing
##### 2.5 var_name.is_monotonic_decreasing
##### 2.6 var_name.array
##### 2.7 var_name.nbytes
##### 2.8 var_name.memory_usage()

##### **2.1 var_name.empty**
##### It will check whether the series/data will contain Empty Values/Empty Values or Not, If Yes returns True,else False.
##### **Syntax : var_name.empty**

In [60]:
import pandas as pd
import numpy as np
df = pd.Series(data=np.random.randint(60,90,5),index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     77
1     68
2     64
3     63
4     65

In [61]:
df.empty

False

##### **2.2 var_name.hasnans**
##### It will check whether the series/data will contain Null Values/Empty Values or Not, If Yes returns True,else False.
##### **Syntax : var_name.hasnans**

##### **Note :** If We have None Values in Array/Data/Values then None is converted to NaN(Not a Number) and Entire data will convert to Float.

In [62]:
import pandas as pd
import numpy as np
df = pd.Series(data=[56,None,89,68,None],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0   56.0
1    NaN
2   89.0
3   68.0
4    NaN

In [63]:
df.hasnans

True

##### **2.3 var_name.is_unique**
##### It will check whether the Data contains unique values or not, If yes returns True else false.
##### **Syntax : var_name.is_unique**

In [65]:
import pandas as pd
import numpy as np
df = pd.Series(data=[56,67,89,68,75],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     56
1     67
2     89
3     68
4     75

In [66]:
df.is_unique

True

In [67]:
import pandas as pd
import numpy as np
df = pd.Series(data=[56,67,89,75,75],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     56
1     67
2     89
3     75
4     75

In [68]:
df.is_unique

False

##### **2.4 var_name.is_monotonic_increasing**
##### It will check whether the specified data is in ascending order or not, If yes Returns True.
##### **Syntax : var_name.is_monotonic_increasing**

In [69]:
import pandas as pd
import numpy as np
df = pd.Series(data=[56,58,59,79,89],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     56
1     58
2     59
3     79
4     89

In [70]:
df.is_monotonic_increasing

True

In [71]:
import pandas as pd
import numpy as np
df = pd.Series(data=[56,67,89,68,75],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     56
1     67
2     89
3     68
4     75

In [72]:
df.is_monotonic_increasing

False

##### **2.5 var_name.is_monotonic_decreasing**
##### It will check whether the specified data is in ascending order or not, If yes Returns True.
##### **Syntax : var_name.is_monotonic_decreasing**

In [73]:
import pandas as pd
import numpy as np
df = pd.Series(data=[98,87,65,45,21],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     98
1     87
2     65
3     45
4     21

In [74]:
df.is_monotonic_decreasing

True

In [75]:
import pandas as pd
import numpy as np
df = pd.Series(data=[98,107,65,65,21],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     98
1    107
2     65
3     65
4     21

In [76]:
df.is_monotonic_decreasing

False

##### **2.6 var_name.array**
##### It reuturns the array values/data values with lenght of the array/data and data types.
##### **Syntax : var_name.array**

In [77]:
import pandas as pd
import numpy as np
df = pd.Series(data=[98,107,65,65,21],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     98
1    107
2     65
3     65
4     21

In [86]:
df.array

<NumpyExtensionArray>
[np.int64(98), np.int64(107), np.int64(65), np.int64(65), np.int64(21)]
Length: 5, dtype: int64

##### **2.7 var_name.nbytes**
##### It retunrs the total size of the array in bytes
##### **Syntax : var_name.nbytes**

In [89]:
import pandas as pd
import numpy as np
df = pd.Series(data=[998,107,65,65,21],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0    998
1    107
2     65
3     65
4     21

In [90]:
df.nbytes

40

##### **2.8 var_name.memory_usage()**
##### It return the total memory usage by each column.
##### **Syntax : var_name.memory_usage()**

In [108]:
import pandas as pd
import numpy as np
df = pd.Series(data=[98,107,65,65,21],index=np.arange(5),name='Sales')
df.to_frame()

   Sales
0     98
1    107
2     65
3     65
4     21

In [110]:
df.memory_usage()

80