# **Pandas Library**
### **Creating Objects in Pandas Series()**

#### **Pandas :** It is a python powerfull library which is used for Data Creation, Data Manipulation and Data Transformation and so on....
#### The entire pandas will works on mainly two Data Structures 1.Series() 2.DataFrame()
#### **Pandas Basic Operation :**
#### 1.Data Processing - Handling missing values
#### 2.Data Cleaning - Remove duplicates and fixed inconsistancies
#### 3.Data Transformation - Filter, sort and modify the data
#### 4.Data Visualization - Represent data graphically

#### **1. Pandas Series :** 
##### A Pandas Series is one-dimensional labeled array that is capable of holding data of any type (integer, string, float, Python objects etc.) of collection along with index and data type. 
##### A 1-dimensional labeled array,Series is nothing but the column in Excel

##### **Syntax :pd.Series(data, index, dtype)**
##### **Syntax : pd.Series(data=None, index=None, dtype=None, name=None, copy=False)**
##### **Parameters:**
##### **data** → values (list, tuple, dict, numpy array)
##### **index** → labels (optional)
##### **dtype** → data type (optional)**
##### **name** → name of the column (optional)
##### **copy=True** → It creates the copy of the original data/array/collection (optional)
##### What does copy mean? It decides whether: Pandas should use the original data or not

##### **Fundamental Things:**

##### **data** : any array or list or collection or numpy arrays.

In [2]:
import pandas as pd
pd.Series([12,10,2,30,20])

0    12
1    10
2     2
3    30
4    20
dtype: int64

In [13]:
import pandas as pd
df = pd.Series([12,10,2,30,20])
s = df.to_frame()
s

    0
0  12
1  10
2   2
3  30
4  20

##### **Index:** Index may be anything(it may be intiger of list or float of list, or any collection  or a string or any nested collection,numpy array,or random value)

In [14]:
import pandas as pd
df = pd.Series([12,10,2,30,20],index=[10,11,12,13,14])
s = df.to_frame()
s

     0
10  12
11  10
12   2
13  30
14  20

##### **dtype :** If we want to change data type I can change explicitly, Only Values data type we can change , If we want to change index data type can do with manually.
##### Or we can change index data type by explicitly with creating index values from outside the Series()

In [15]:
import pandas as pd
df = pd.Series([12,10,2,30,20],index=[10,11,12,13,14],dtype=float)
s = df.to_frame()
s

       0
10  12.0
11  10.0
12   2.0
13  30.0
14  20.0

##### **Name :** Name is used for column name to represent the column,but the column name will display the name at last of the table. Name: Marks → this is the Series name,
##### In Google collab we will get name and table in corret format like this
|         | Marks |
| ------- | ----- |
| Math    | 85    |
| Science | 90    |
| English | 78    |

In [9]:
import pandas as pd
pd.Series([12,10,2,30,20],index=[10,11,12,13,14],name='Sales')

10    12
11    10
12     2
13    30
14    20
Name: Sales, dtype: int64

In [16]:
import pandas as pd
df = pd.Series([12,10,2,30,20],index=[10,11,12,13,14],name='Sales')
s = df.to_frame()
s

    Sales
10     12
11     10
12      2
13     30
14     20

##### **Copy :** It is used to copy the original array or modifies the same array if Copy=False
| copy  | Meaning                       |
| ----- | ----------------------------- |
| False | Use same memory (if possible) |
| True  | Create new copy in memory     |

##### **Copy=True** : Means it will copies the Original data/values/collection/array,It won't affect if the original data/array will change
##### **Copy=False** : Means it will not copies the Original data/values/collection/array,It will directly affect the original data/array will change

In [32]:
import pandas as pd
import numpy as np
arr = np.random.randint(50,80,5)
df = pd.Series(arr,index=np.arange(5),name='Marks',copy=True)
print(arr)
df.to_frame()

[74 64 66 74 50]

   Marks
0     74
1     64
2     66
3     74
4     50

##### After modifying the original array or data it will not change in the Series()

In [33]:
arr[0]=100
print(arr)
df.to_frame()

[100  64  66  74  50]

   Marks
0     74
1     64
2     66
3     74
4     50

##### **Copy=False** : Means it will not copies the Original data/values/collection/array,It will directly affect the original data/array will change

In [34]:
import pandas as pd
import numpy as np
arr = np.random.randint(50,80,5)
df = pd.Series(arr,index=np.arange(5),name='Marks',copy=False)
print(arr)
df.to_frame()

[50 65 65 70 68]

   Marks
0     50
1     65
2     65
3     70
4     68

##### After modifying the original array or data it will change in the Series(), Becuase we are not copied the original array

In [35]:
arr[0]=100
print(arr)
df.to_frame()

[100  65  65  70  68]

   Marks
0    100
1     65
2     65
3     70
4     68

#### **Indetail Creating Series :**

##### We can directly pass list value inside the Series() and index will automatically generates from 0 to n(depends on length)

In [11]:
import pandas as pd
s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [16]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

##### We can create a series by String Characters

In [3]:
import numpy as np
import pandas as pd
s=pd.Series(data=['A','B','C','D','E'],index=[np.random.randint(1,10,5)])
s.to_frame()

   0
2  A
8  B
9  C
8  D
1  E

##### If we want to pass list as data we can pass list inside the Series(), Where By default index will takes place automatically from 0 to n(based on list values)

In [10]:
import pandas as pd
l=[10,20,30,40,50]
s1 = pd.Series(l)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

##### We can create numpy array inside or outside the Series() and we can generate Numeric Values

In [14]:
import pandas as pd
import numpy as np
s1 = pd.Series(np.arange(100,200,20))
s1

0    100
1    120
2    140
3    160
4    180
dtype: int64

##### If i want to genarate random values i can generate using numpy with random values

In [19]:
import pandas as pd
import numpy as np
s1 = pd.Series(np.random.randint(100,200,(10)))
s1

0    182
1    138
2    141
3    142
4    101
5    148
6    112
7    145
8    125
9    167
dtype: int32

##### **NOTE:** Series() Only works with Single 1-Dimensional Array,It will not support 2D or multidimensional arrays

In [20]:
import pandas as pd
import numpy as np
s1 = pd.Series(np.random.randint(100,200,(10,20))) 
s1

ValueError: Data must be 1-dimensional, got ndarray of shape (10, 20) instead

#### **Creating Series() :**
##### 1.1 From List
##### 1.2 Custom Index
##### 1.3 From Dictionary
##### 1.4 From Numpy Array
##### 1.5 Scalar Values

#### **1.1 Creating Series() ===> From List :**

##### We can pass list inside the Series directly or we can pass through variable by creatin list from outside the Series()

In [21]:
import pandas as pd
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [22]:
import pandas as pd
l=[10,20,30,40,50]
s = pd.Series(l)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

##### Note List means we can pass any type of collection (Homogeneous or Heterogeneous)

In [23]:
# List with Integer Data type
import pandas as pd
l=[10,20,30,40,50]
s = pd.Series(l)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [28]:
# List with Floating Data type
import pandas as pd
l=[10.00,20.90,30.90,40.67,50.98]
s = pd.Series(l)
s

0    10.00
1    20.90
2    30.90
3    40.67
4    50.98
dtype: float64

In [29]:
# List with Boolean Data type
import pandas as pd
l=[True, False, True, False]
s = pd.Series(l)
s

0     True
1    False
2     True
3    False
dtype: bool

In [30]:
# List with Complex Data type
import pandas as pd
l=[8+9j,10+5j,90+8j]
s = pd.Series(l)
s

0     8.0+ 9.0j
1    10.0+ 5.0j
2    90.0+ 8.0j
dtype: complex128

In [32]:
# List with string Data type
import pandas as pd
l=['Aftab','Shadaf','Nayab']
s = pd.Series(l)
s

0     Aftab
1    Shadaf
2     Nayab
dtype: object

In [91]:
# List with set Data type
import pandas as pd
l={'Aftab','Shadaf','Nayab'}
s = pd.Series(l)
s

TypeError: 'set' type is unordered

In [92]:
# List with set Data type
import pandas as pd
l=frozenset({'Aftab','Shadaf','Nayab'})
s = pd.Series(l)
s

TypeError: 'frozenset' type is unordered

##### **NOTE:** String,List,Tuple,Set,Frozenset,Dictionary,Range That all Multi Value Datatypes are considered as a object in Pandas.
##### If Homogeneous List - Return Single Value Datatype(Int,float,complex,boolean)
##### If Heterogeneous List - Return Multi Value Datatype(str,list,tuple,dictionary,range) but set,frozenset not supported in pandas because botha are unordered collection

##### Working with Homogeneous List (Always Returns single value data type)

In [37]:
import pandas as pd
l=[10,20,30,40,50]
s = pd.Series(l)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

##### Working with Heterogeneous List (Witout any convertion it will returns an output)

##### **Note : When we use mixed type of data it always return object data type**

In [38]:
import pandas as pd
l=[10,'Aftab',20.98,True]
s = pd.Series(l)
s

0       10
1    Aftab
2    20.98
3     True
dtype: object

##### If we want to pass list inside another we can but it will consider as a object data type(same with other nested collections)

In [40]:
import pandas as pd
l=[10,20,30,40,[100,200,300,400]]
s = pd.Series(l)
s

0                      10
1                      20
2                      30
3                      40
4    [100, 200, 300, 400]
dtype: object

##### If we want to pass tuple we can pass

In [39]:
import pandas as pd
t=(10,20,30,40)
s = pd.Series(t)
s

0    10
1    20
2    30
3    40
dtype: int64

##### **note:** If we want to pass **set** or **frozenset** we can pass but Set is unordered collection hence Pandas will not support set

In [44]:
import pandas as pd
t={10,20,30,40,40,10,20,30}
s = pd.Series(t)
s

TypeError: 'set' type is unordered

In [45]:
import pandas as pd
t=frozenset({10,20,30,40,40,10,20,30})
s = pd.Series(t)
s

TypeError: 'frozenset' type is unordered

##### We can pass range data type also because it is generating series of elements itself

In [47]:
import pandas as pd
t=range(4,10)
s = pd.Series(t)
s

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64

##### It also supports the dictionary data type, By default we will get only **values** not keys.
##### To get keys we need to use variable.keys() - returns Object
##### To get values we need to use variable.values() - returns as Single Value Datatype
##### To get items we need to use variable.items() - returns Object

In [49]:
import pandas as pd
t=dict({'A':200,'B':300,'C':800})
s = pd.Series(t)
s

A    200
B    300
C    800
dtype: int64

##### To get keys we need to use variable.keys() - returns Object

In [50]:
import pandas as pd
t=dict({'A':200,'B':300,'C':800})
s = pd.Series(t.keys())
s

0    A
1    B
2    C
dtype: object

##### To get values we need to use variable.values() - returns as Single Value Datatype

In [51]:
import pandas as pd
t=dict({'A':200,'B':300,'C':800})
s = pd.Series(t.values())
s

0    200
1    300
2    800
dtype: int64

##### To get items we need to use variable.items() - returns Object

In [52]:
import pandas as pd
t=dict({'A':200,'B':300,'C':800})
s = pd.Series(t.items())
s

0    (A, 200)
1    (B, 300)
2    (C, 800)
dtype: object

#### **1.2 Creating Series() ===> From Custom Index :**

##### If we want to speciy the index value based on our need we can do with or without index attribute.
##### Custome index means we can change index values in int,float or string according to our need 
##### For Index Attribute we can pass the string , int or boolean

##### **Normal without specifying index**

In [53]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s)

0    10
1    20
2    30
3    40
dtype: int64

##### **With specifying index**
##### In Pandas Series() We can give any order ot index (assending , descending or mixedup)
##### But Number of elements in a list/array/data must and equal to the index values

##### **It works with positional Arguements or Keyword arguements, We can specify index attribute or if we dont't want we can directly mentioned index values**

##### If we want to pass index in ascending order we can do

In [66]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,[1,2,3,4])

1    10
2    20
3    30
4    40
dtype: int64

##### If we want to pass index in descending order we can do

In [67]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,[9,8,7,6])

9    10
8    20
7    30
6    40
dtype: int64

##### If we want to pass index in ascending or decending or mixed order we can do

In [56]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,[100,500,200,10])

100    10
500    20
200    30
10     40
dtype: int64

##### If we want to pass index with int and string we can do.

In [68]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,[100,'B',200,10])

100    10
B      20
200    30
10     40
dtype: int64

##### If we want to pass index mixed order we can do.

In [59]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,index=[100,500,200,10])

100    10
500    20
200    30
10     40
dtype: int64

##### **Note:** If the lenght of list/array is not equal to the lenght of the indexes it will raise an error

In [58]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,[100,500,200])

ValueError: Length of values (4) does not match length of index (3)

##### If we want to pass index in string ascending order we can do

In [61]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,index=['A','B','C','D'])

A    10
B    20
C    30
D    40
dtype: int64

##### If we want to pass index in string descending order we can do

In [64]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,index=['D','C','B','A'])

D    10
C    20
B    30
A    40
dtype: int64

In [65]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,index=['D','K','M','A'])

D    10
K    20
M    30
A    40
dtype: int64

##### If we want to pass index in floating/complex/boolean order we can do

In [69]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,index=[11.1,11.2,11.3,11.4])

11.1    10
11.2    20
11.3    30
11.4    40
dtype: int64

In [70]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,index=[11+9j,12+9j,13+9j,14+9j])

11.0+ 9.0j    10
12.0+ 9.0j    20
13.0+ 9.0j    30
14.0+ 9.0j    40
dtype: int64

In [71]:
import pandas as pd
s = [10,20,30,40]
pd.Series(s,index=[True,False,True,False])

True     10
False    20
True     30
False    40
dtype: int64

##### **If we want to pass range as a list as index we can explicitly pass the range as index**

In [78]:
import pandas as pd
s = [10,20,30,40]
li = list(range(1,5))
pd.Series(s,index=[li])

1    10
2    20
3    30
4    40
dtype: int64

##### **If we want to pass range as a list of index with multiple time we can explicitly pass the range as index**

In [79]:
import pandas as pd
s = [10,20,30,40]
li = range(1,5)
pd.Series(s,index=[li,li,li,li])

(1, 2, 3, 4)    10
(1, 2, 3, 4)    20
(1, 2, 3, 4)    30
(1, 2, 3, 4)    40
dtype: int64

##### **If we want to pass numpy array as a list index we can explicitly pass the numpy array as index**

In [84]:
import pandas as pd
import numpy as np
s = [10,20,30,40]
li = np.arange(1,5)
pd.Series(s,index=[li])

1    10
2    20
3    30
4    40
dtype: int64

In [94]:
import pandas as pd
import numpy as np
s = [10,20,30,40]
pd.Series(s,index=[s])

10    10
20    20
30    30
40    40
dtype: int64

##### We can randomly generate the index values using random module

In [88]:
import pandas as pd
import numpy as np
s = [10,20,30,40]
li = np.random.randint(1,50,4)
pd.Series(s,index=[li])

6     10
23    20
22    30
1     40
dtype: int64

##### We can pass multiple data types of indexes

In [95]:
import pandas as pd
import numpy as np
li = np.random.randint(1,50,4)
pd.Series(li,index=[111,'AAA',1.0,True])

111     46
AAA     49
1.0     12
True    42
dtype: int32

##### **If we want to pass numpy array as a list index we can explicitly pass the numpy array as index**

In [97]:
import pandas as pd
import numpy as np
li = np.arange(4)
pd.Series(li,index=[111,'AAA',1.0,True])

111     0
AAA     1
1.0     2
True    3
dtype: int64

#### **1.3 Creating Series() ===> From Dictionary :**

##### It also supports the dictionary data type, By default we will get only **values** not keys.

In [99]:
import pandas as pd
d = {'a':100,'b':200,'c':300}
pd.Series(d)

a    100
b    200
c    300
dtype: int64

##### To get keys we need to use variable.keys() - returns Object

In [100]:
import pandas as pd
d = {'a':100,'b':200,'c':300}
pd.Series(d.keys())

0    a
1    b
2    c
dtype: object

##### To get values we need to use variable.values() - returns as Single Value Datatype

In [101]:
import pandas as pd
d = {'a':100,'b':200,'c':300}
pd.Series(d.values())

0    100
1    200
2    300
dtype: int64

##### To get items we need to use variable.items() - returns Object

In [102]:
import pandas as pd
d = {'a':100,'b':200,'c':300}
pd.Series(d.items())

0    (a, 100)
1    (b, 200)
2    (c, 300)
dtype: object

#### **1.4 Creating Series() ===> From Numpy Array :**

##### We have to make use of Numpy Creation method to generate the values

In [104]:
import numpy as np
import pandas as pd
arr = np.arange(1,10,2)
pd.Series(arr)

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [106]:
import numpy as np
import pandas as pd
arr = np.arange(1,10,2)
pd.Series(arr,np.ones(5))

1.0    1
1.0    3
1.0    5
1.0    7
1.0    9
dtype: int64

#### **1.5 Creating Series() ===> From Scalar Value :**

##### Instead of creating an array or list or collection of elements we can diretly gives a scalar value as data.But it will generates only single value.
##### To generate multiple values based on scalar value we need pass the index values.

In [107]:
import numpy as np
import pandas as pd
pd.Series(5)

0    5
dtype: int64

##### If we pass scalar values with index,same values going to repeat

In [109]:
import numpy as np
import pandas as pd
pd.Series(5,index=[np.random.randint(1,10,5)])

7    5
8    5
3    5
8    5
9    5
dtype: int64

##### If we want to change data type I can change explicitly, Only Values data type we can change , If we want to change index data type can do with manually.
##### Or we can change index data type by explicitly with creating index values from outside the Series()

In [115]:
import numpy as np
import pandas as pd
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=float)

4    5.0
4    5.0
8    5.0
2    5.0
7    5.0
dtype: float64

In [117]:
import numpy as np
import pandas as pd
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=int)

3    5
6    5
4    5
6    5
9    5
dtype: int64

In [118]:
import numpy as np
import pandas as pd
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=complex)

4    5.0+0.0j
8    5.0+0.0j
4    5.0+0.0j
9    5.0+0.0j
1    5.0+0.0j
dtype: complex128

In [119]:
import numpy as np
import pandas as pd
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=bool)

2    True
6    True
4    True
9    True
9    True
dtype: bool

In [120]:
import numpy as np
import pandas as pd
pd.Series([1,1,9,0,0],index=[np.random.randint(1,10,5)],dtype=bool)

2     True
6     True
6     True
6    False
7    False
dtype: bool

In [121]:
import numpy as np
import pandas as pd
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=str)

6    5
1    5
6    5
5    5
3    5
dtype: object

##### Except string we can't convert Multi Value Data type.

In [124]:
import numpy as np
import pandas as pd
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=list)

TypeError: dtype '<class 'list'>' not understood

In [130]:
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=tuple)

TypeError: dtype '<class 'tuple'>' not understood

In [129]:
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=set)

TypeError: dtype '<class 'set'>' not understood

In [128]:
pd.Series(5,index=[np.random.randint(1,10,5)],dtype=dict)

TypeError: dtype '<class 'dict'>' not understood

##### In Series() We Can't Perform Muliple Series time at a time , to perform Multiple Series we need to use concat, So we can pass multiple Series()

In [17]:
import pandas as pd
import numpy as np
s1 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks1')
s2 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks2')
s3 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks3')
s4 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks4')
s5 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks5')
df = pd.concat([s1,s2,s3,s4,s5], axis=1)
df

   Marks1  Marks2  Marks3  Marks4  Marks5
1      82      50      98      50      53
2      81      66      67      70      62
3      80      53      59      96      73
4      61      65      69      76      60

In [45]:
df[1:3]

   Marks1  Marks2  Marks3  Marks4  Marks5
2      76      82      82      56      81
3      54      76      92      95      63

##### **NOTE :**
##### Core Idea (Understand This Clearly)
##### Series → 1D (only one column) If we want to do with multiple columns we can use concat()
##### DataFrame → 2D (rows + columns)
##### Why Series cannot support 2D? -> A Series is designed to represent a single column only.

##### Suppose I have created data and I need to add the another row , we can add by using **variable_name[index]=value**

In [37]:
import pandas as pd
import numpy as np
s1 = pd.Series(np.random.randint(50,100,4),index=[1,2,3,4],name='Marks1')
s1.to_frame()

   Marks1
1      58
2      93
3      75
4      67

In [38]:
s1[5]=100
s1.to_frame()

   Marks1
1      58
2      93
3      75
4      67
5     100

In [39]:
s1[1]=90
s1.to_frame()

   Marks1
1      90
2      93
3      75
4      67
5     100