# **Pandas Library**
### **Creating Objects in Pandas DataFrame()**

#### **Pandas :** It is a python powerfull library which is used for Data Creation, Data Manipulation and Data Transformation and so on....
#### The entire pandas will works on mainly two Data Structures 1.Series() 2.DataFrame()
#### **Pandas Basic Operation :**
#### 1.Data Processing - Handling missing values
#### 2.Data Cleaning - Remove duplicates and fixed inconsistancies
#### 3.Data Transformation - Filter, sort and modify the data
#### 4.Data Visualization - Represent data graphically

#### **1.DataFrame()**
##### Used to create a DataFrame from different data sources like list, dictionary, NumPy array, or Series.
##### **Syntax : pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)**
##### **Parameters :**
##### data → input data (list, dict, array, Series)
##### index → row labels
##### columns → column names
##### dtype → data type
##### copy → copy data or not

#### **OR**

##### **Syntax : pd.DataFrame(data, index, columns)** 
##### **Parameters:**
##### **data:** It is a dataset from which a DataFrame is to be created. It can be a list, dictionary, scalar value, series, and arrays, etc. 
##### **index:** It is optional, by default the index of the DataFrame starts from 0 and ends at the last data value(n-1). It defines the row label explicitly. 
##### **columns:** This parameter is used to provide column names in the DataFrame. If the column name is not defined by default, it will take a value from 0 to n-1. 
##### **Returns:** DataFrame object

#### **Data Creation in DataFrame()**
##### We can create a data by using
##### 1.1 Create a Empty DataFrame.
##### 1.2 Create a DataFrame from List
##### 1.3 Create a DataFrame from Dictionary
##### 1.4 Create a DataFrame from Numpy
##### 1.5 Create a DataFrame from Seires
##### 1.6 Creating a DataFrame from a List of Dictionaries
##### 1.7 Creating a DataFrame from a Nested List
##### 1.8 Creating a DataFrame from Another DataFrame
##### 1.9 Create DataFrame from a Dictionary of Series
##### 1.10 Create DataFrame using the zip() function
##### 1.11 Create a DataFrame by Proving the Index Label Explicitly

##### **1.1 Create an Empty DataFrame**
##### Pandas Create Dataframe can be created by the DataFrame() function of the Pandas library. Just call the function with the DataFrame constructor to create a DataFrame.

In [28]:
import pandas as pd
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

##### **1.2 Create a DataFrame from List :**
##### If we have a simple list of data, we can easily create a DataFrame by passing that list to the pd.DataFrame() function.

In [3]:
import pandas as pd
l = ["Banglore","Ballari","Badami","Belagavi"]
pd.DataFrame(l)

          0
0  Banglore
1   Ballari
2    Badami
3  Belagavi

In [2]:
import pandas as pd
pd.DataFrame([1,2,3,4,5])

   0
0  1
1  2
2  3
3  4
4  5

##### **1.3 Create a DataFrame from Dictionary :**
##### Creating DataFrame from dict of ndarray/lists : We can create a DataFrame from a dictionary where the keys are column names and the values are lists or arrays.
##### -> All arrays/lists must have the same length.
##### -> If an index is provided, it must match the length of the arrays.
##### -> If no index is provided, Pandas will use a default range index (0, 1, 2, …).

In [11]:
# -> All arrays/lists must have the same length.
import pandas as pd
data = {'Name':['Aftab','Smith','Goudra','Scott','Jhon'],'Marks':[94,89,78,91,94]}
pd.DataFrame(data)

     Name  Marks
0   Aftab     94
1   Smith     89
2  Goudra     78
3   Scott     91
4    Jhon     94

In [10]:
# -> If an index is provided, it must match the length of the arrays.
import pandas as pd
import numpy as np
data = {'Name':['Aftab','Smith','Goudra','Scott','Jhon'],'Marks':[94,89,78,91,94]}
pd.DataFrame(data,index=np.arange(10,60,10))

      Name  Marks
10   Aftab     94
20   Smith     89
30  Goudra     78
40   Scott     91
50    Jhon     94

In [12]:
# -> If no index is provided, Pandas will use a default range index (0, 1, 2, …).
import pandas as pd
import numpy as np
data = {'Name':['Aftab','Smith','Goudra','Scott','Jhon'],'Marks':[94,89,78,91,94]}
pd.DataFrame(data)

     Name  Marks
0   Aftab     94
1   Smith     89
2  Goudra     78
3   Scott     91
4    Jhon     94

In [13]:
import pandas as pd
import numpy as np
pd.DataFrame({'Name':['Aftab','Smith','Goudra','Scott','Jhon'],'Marks':[94,89,78,91,94]})

     Name  Marks
0   Aftab     94
1   Smith     89
2  Goudra     78
3   Scott     91
4    Jhon     94

In [14]:
import pandas as pd
import numpy as np
pd.DataFrame({'Name':['Aftab','Smith','Goudra','Scott','Jhon'],'Marks':[94,89,78,91,94]},index=[111,222,333,444,555])

       Name  Marks
111   Aftab     94
222   Smith     89
333  Goudra     78
444   Scott     91
555    Jhon     94

##### **1.4 Create a DataFrame from Numpy :**
##### We can create a DataFrame  by using Numpy

In [23]:
import pandas as pd
import numpy as np
pd.DataFrame(np.arange(1,10,2))

   0
0  1
1  3
2  5
3  7
4  9

In [24]:
import pandas as pd
import numpy as np
pd.DataFrame(data=np.arange(1,10,2),index=np.arange(10,60,10))

    0
10  1
20  3
30  5
40  7
50  9

##### **1.5 Create a DataFrame from Seires :**
##### We can create a DataFrame by using series also, where each series treated as rows and each series elements treated as Columns

In [26]:
import pandas as pd
import numpy as np
s1=pd.Series(np.arange(10,60,10))
s2=pd.Series(np.arange(10,100+1,20))
s3=pd.Series(np.arange(100,600,100))
pd.DataFrame([s1,s2,s3])

     0    1    2    3    4
0   10   20   30   40   50
1   10   30   50   70   90
2  100  200  300  400  500

##### **1.6 Create a DataFrame from a List of Dictionaries** 
##### We can create a DataFrame using a list of dictionaries, where each dictionary represents a row. This is useful for handling structured data from APIs or JSON, and is commonly used in web scraping and API processing.
##### We are storing the data like records if we use the list of dictionary.

In [19]:
import pandas as pd
import numpy as np
data = [{'Name': 'Aftab', 'Degree': 'B.Tech', 'Score': 90},
        {'Name': 'Smith', 'Degree': 'BCA', 'Score': 84},
        {'Name': 'Jhon', 'Degree': 'B.Com', 'Score': 80} ]
pd.DataFrame(data)

    Name  Degree  Score
0  Aftab  B.Tech     90
1  Smith     BCA     84
2   Jhon   B.Com     80

In [20]:
import pandas as pd
import numpy as np
data = [{'Name': 'Aftab', 'Degree': 'B.Tech', 'Score': 90},
        {'Name': 'Smith', 'Degree': 'BCA', 'Score': 84},
        {'Name': 'Jhon', 'Degree': 'B.Com', 'Score': 80} ]
pd.DataFrame(data,index=[101,102,103])

      Name  Degree  Score
101  Aftab  B.Tech     90
102  Smith     BCA     84
103   Jhon   B.Com     80

##### If we change the any column name or the column names are mismatched by ond dictionary to another dictionary it will take that column as a new column and rest of all the values will become NaN values.

In [22]:
import pandas as pd
import numpy as np
data = [{'Name': 'Aftab', 'Course': 'B.Tech', 'Score': 90},
        {'Name': 'Smith', 'Degree': 'BCA', 'score': 84},
        {'name': 'Jhon', 'Degree': 'B.Com', 'Score': 80} ]
pd.DataFrame(data,index=[101,102,103])

      Name  Course  Score Degree  score  name
101  Aftab  B.Tech   90.0    NaN    NaN   NaN
102  Smith     NaN    NaN    BCA   84.0   NaN
103    NaN     NaN   80.0  B.Com    NaN  Jhon

##### **1.7 Creating a DataFrame from a Nested List**

In [29]:
import pandas as pd
data=[['Aftab',98],['Smith',92],['Jhon',94]]
pd.DataFrame(data)

       0   1
0  Aftab  98
1  Smith  92
2   Jhon  94

In [30]:
import pandas as pd
data=[['Aftab',98],['Smith',92],['Jhon',94]]
pd.DataFrame(data,columns=['Name','Marks'])

    Name  Marks
0  Aftab     98
1  Smith     92
2   Jhon     94

##### **1.8 Create DataFrame from a Dictionary of Series**

In [31]:
import pandas as pd
data ={'one': pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd']), 'two': pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])}
pd.DataFrame(data)

   one  two
a   10   10
b   20   20
c   30   30
d   40   40

##### **1.9 Create DataFrame using the zip() function**
##### get the list of tuples from two lists. and merge them by using zip().

In [32]:
import pandas as pd
Name = ['tom', 'krish', 'nick', 'juli']
Age = [25, 30, 26, 22]
data = list(zip(Name, Age))
pd.DataFrame(data, columns=['Name', 'Age'])

    Name  Age
0    tom   25
1  krish   30
2   nick   26
3   juli   22

##### **1.10 Create a DataFrame by Proving the Index Label Explicitly**

In [33]:
import pandas as pd
data = {'Name': ['Tom', 'Jack', 'nick', 'juli'],
        'marks': [99, 98, 95, 90]}
pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])

       Name  marks
rank1   Tom     99
rank2  Jack     98
rank3  nick     95
rank4  juli     90

##### **Index : It is used to change the default row index to specific row index**

In [37]:
import pandas as pd
import numpy as np
pd.DataFrame({'Name':['Aftab','Smith','Goudra','Scott','Jhon'],'Marks':[94,89,78,91,94]},index=[111,222,333,444,555])

       Name  Marks
111   Aftab     94
222   Smith     89
333  Goudra     78
444   Scott     91
555    Jhon     94

##### **Columns : It used to change the default column index to the specific column index**

In [36]:
import pandas as pd
import numpy as np
pd.DataFrame([['Aftab',98],['Smith',94],['Goudra',96],['Scott',89],['Jhon',89]],index=[111,222,333,444,555],columns=['Name','Marks'])

       Name  Marks
111   Aftab     98
222   Smith     94
333  Goudra     96
444   Scott     89
555    Jhon     89

##### **dtype : It is used to convert the one type of data into another type of data**

In [41]:
import pandas as pd
import numpy as np
df=pd.DataFrame([['Aftab',98],['Smith',94],['Goudra',96],['Scott',89],['Jhon',89]],index=[111,222,333,444,555],columns=['Name','Marks'])
df

       Name  Marks
111   Aftab     98
222   Smith     94
333  Goudra     96
444   Scott     89
555    Jhon     89

In [42]:
pd.DataFrame(df['Marks'],dtype=float)

     Marks
111   98.0
222   94.0
333   96.0
444   89.0
555   89.0

##### **copy : It is used to create a copy of the DataFrame, If True : It creates the copy and whatever changes we want to do we can, it will not affect the original DataFrame Series. If False : If we done any changes it directly affects to the original DataFrame**

In [43]:
import pandas as pd
import numpy as np
df=pd.DataFrame([['Aftab',98],['Smith',94],['Goudra',96],['Scott',89],['Jhon',89]],index=[111,222,333,444,555],columns=['Name','Marks'])
df

       Name  Marks
111   Aftab     98
222   Smith     94
333  Goudra     96
444   Scott     89
555    Jhon     89

In [45]:
cp=pd.DataFrame(df['Marks'],dtype=float,copy=True)
cp

     Marks
111   98.0
222   94.0
333   96.0
444   89.0
555   89.0

In [46]:
cp['Marks']=cp['Marks']=100

In [47]:
cp

     Marks
111    100
222    100
333    100
444    100
555    100