# **Pandas Library**
### **Selection and Inspection Methods of Pandas Series()**

##### **1. Preview / Viewing Data**
##### 1.1 var_name.head(n)
##### 1.2 var_name.tail(n)

##### **1.1 var_name.head(n)**
##### It returns the top n rows. By default n=5(5 values)
##### **Syntax : var_name.head(n)**
##### n is optional

In [5]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(30,70,15),index=np.arange(15),name='Marks')
s.to_frame()

    Marks
0      34
1      35
2      66
3      67
4      54
5      64
6      32
7      47
8      59
9      39
10     34
11     67
12     36
13     64
14     40

In [6]:
s.head()

0    34
1    35
2    66
3    67
4    54
Name: Marks, dtype: int32

In [7]:
s.head(10)

0    34
1    35
2    66
3    67
4    54
5    64
6    32
7    47
8    59
9    39
Name: Marks, dtype: int32

##### **1.2 var_name.tail(n)**
##### It returns the bottom n rows. By default n=5(5 values)
##### **Syntax : var_name.tail(n)**
##### n is optional

In [8]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(30,70,15),index=np.arange(15),name='Marks')
s.to_frame()

    Marks
0      43
1      57
2      47
3      53
4      45
5      54
6      55
7      60
8      36
9      53
10     64
11     45
12     42
13     33
14     41

In [9]:
s.tail()

10    64
11    45
12    42
13    33
14    41
Name: Marks, dtype: int32

In [10]:
s.tail(10)

5     54
6     55
7     60
8     36
9     53
10    64
11    45
12    42
13    33
14    41
Name: Marks, dtype: int32

##### **2. Basic Information Methods**
##### 2.1 var_name.info()
##### 2.2 var_name.describe()
##### 2.3 var_name.count()

##### **2.1 var_name.info()**
##### It returns the information about the Series(). It returns the information in such way that Index number from where to where , Series name, Not null count and dtypes with memory usage.
##### **Syntax : var_name.info()**

In [11]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(30,70,15),index=np.arange(15),name='Marks')
s.to_frame()

    Marks
0      68
1      59
2      37
3      67
4      61
5      59
6      60
7      52
8      45
9      36
10     49
11     45
12     69
13     64
14     58

In [14]:
s.info()

<class 'pandas.core.series.Series'>
Index: 15 entries, 0 to 14
Series name: Marks
Non-Null Count  Dtype
--------------  -----
15 non-null     int32
dtypes: int32(1)
memory usage: 180.0 bytes

##### **2.2 var_name.describe()**
##### It returns the statistical information includes count, mean ,standarad deviation ,min ,max, 25%,50%,75%.
##### **Syntax : var_name.describe(percentiles=None, include=None, exclude=None)**
##### percentiles ,include and exclude is optional

In [5]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(30,70,10),index=np.arange(10),name='Marks')
s.to_frame()

   Marks
0     50
1     48
2     44
3     47
4     49
5     56
6     64
7     62
8     34
9     40

##### Before Sorting the Values are : [50,48,44,47,49,56,64,62,34,40]
##### After sorting values are : [34,40,44,47,48,49,50,56,62,64] => (Index: 0 → 9)
##### Calculate 25% (Q1)
##### **Formula = (total_elements - 1) * 25%**
##### = (10 - 1) * 0.25 = 9 * 0.25 = 2.25
##### Position = 2.25
##### Index 2 → 44
##### Index 3 → 47
##### Interpolation:
##### value = 44 + (47 - 44) * 0.25
##### = 44 + 3 * 0.25
##### = 44 + 0.75
##### = 40.75
##### **25% => 44.75000**
##### **(Median) Calculate 50% (Q2)**
##### **Formula = pos = (total_elements - 1) * 50%**
##### = (10 - 1) * 0.5 = 9 * 0.5 = 4.5
##### Position = 4.5
##### Index 4 → 48
##### Index 5 → 49
##### Interpolation:
##### value = 48 + (49 - 48) * 0.5
##### = 48 + 1 * 0.5
##### = 48 + 0.5
##### = 48.50
##### **50% => 48.50000**
##### **Calculate 75% (Q3)**
##### **Formula = pos = (total_elements - 1) * 75%**
##### = (10 - 1) * 0.75 = 9 * 0.75 = 6.75
##### Position = 4.5
##### Index 6 → 50
##### Index 7 → 56
##### Interpolation:
##### value = 50 + (56 - 50) * 0.75
##### = 50 + 6 * 0.75
##### = 50 + 4.5
##### = 54.50
##### **75% => 54.50000**

In [18]:
s.describe()

count    10.00000
mean     49.40000
std       9.29994
min      34.00000
25%      44.75000
50%      48.50000
75%      54.50000
max      64.00000
Name: Marks, dtype: float64

##### We are telling Pandas to show only the 25% percentile (Q1) instead of default [0.25, 0.5, 0.75]. But pandas always shown 50% default

In [17]:
s.describe(percentiles=[0.25])

count    10.00000
mean     49.40000
std       9.29994
min      34.00000
25%      44.75000
50%      48.50000
max      64.00000
Name: Marks, dtype: float64

In [16]:
s.describe(percentiles=[0.25,0.75])

count    10.00000
mean     49.40000
std       9.29994
min      34.00000
25%      44.75000
50%      48.50000
75%      54.50000
max      64.00000
Name: Marks, dtype: float64

In [15]:
s.describe(percentiles=[0.25,0.5,0.75])

count    10.00000
mean     49.40000
std       9.29994
min      34.00000
25%      44.75000
50%      48.50000
75%      54.50000
max      64.00000
Name: Marks, dtype: float64

In [9]:
s.describe(percentiles=[0.1,0.9])

count    10.00000
mean     49.40000
std       9.29994
min      34.00000
10%      39.40000
50%      48.50000
90%      62.20000
max      64.00000
Name: Marks, dtype: float64

##### **include Parameter**
##### Purpose: It Tell Pandas which data types to include
##### Possible values:
##### 'number' → numeric data
##### 'object' → strings
##### 'category'
##### 'datetime'
##### list → ['number', 'object']
##### Output → same as normal (since Series is numeric)

##### **NOTE : For Series, include and exclude are mostly ignored / have limited effect.They are designed mainly for DataFrame, not Series**

##### Number works as normal decribe

In [36]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(30,70,7),index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0     67
1     31
2     38
3     58
4     64
5     35
6     56

In [37]:
s.describe(include='number')

count     7.000000
mean     49.857143
std      14.803474
min      31.000000
25%      36.500000
50%      56.000000
75%      61.000000
max      67.000000
Name: Marks, dtype: float64

In [38]:
s.describe(include='object') #It returns same

count     7.000000
mean     49.857143
std      14.803474
min      31.000000
25%      36.500000
50%      56.000000
75%      61.000000
max      67.000000
Name: Marks, dtype: float64

##### Object is works with string sereis that includes count,top,unique adn freq.

In [39]:
import pandas as pd
import numpy as np
s = pd.Series(data=['A','C','C','A','C','E'],index=np.arange(6),name='Marks')
s.to_frame()

  Marks
0     A
1     C
2     C
3     A
4     C
5     E

In [40]:
s.describe(include='object')

count     6
unique    3
top       C
freq      3
Name: Marks, dtype: object

In [41]:
s.describe(include='number') # It returns same

count     6
unique    3
top       C
freq      3
Name: Marks, dtype: object

In [42]:
import pandas as pd
import numpy as np
s = pd.Series(data=['A','C',98,'A',67,57],index=np.arange(6),name='Marks')
s.to_frame()

  Marks
0     A
1     C
2    98
3     A
4    67
5    57

In [43]:
s.describe(include='object') #Priority of array matters , Hence array converted to string

count     6
unique    5
top       A
freq      2
Name: Marks, dtype: object

In [45]:
s.describe(include=['number'])

count     6
unique    5
top       A
freq      2
Name: Marks, dtype: object

##### **Exclude Parameter**
##### Purpose: Tell Pandas which data types to ignore exclude Parameter. Tell Pandas which data types to ignore

In [47]:
import pandas as pd
import numpy as np
s = pd.Series(data=[58,98,68,67,57,90],index=np.arange(6),name='Marks')
s.to_frame()

   Marks
0     58
1     98
2     68
3     67
4     57
5     90

In [48]:
s.describe(exclude='number')

count     6.000000
mean     73.000000
std      17.064583
min      57.000000
25%      60.250000
50%      67.500000
75%      84.500000
max      98.000000
Name: Marks, dtype: float64

##### **2.3 var_name.count()**
##### Returns the number of non-null values in the Series.
##### **Syntax : var_name.count()**

In [49]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,30,np.nan,50,None],index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0   10.0
1   20.0
2   30.0
3    NaN
4   50.0
5    NaN

In [52]:
print(s.count())

4

In [54]:
import pandas as pd
import numpy as np
s=pd.Series(data=['A','B','C',np.nan,'D',None],index=np.arange(6),name="Sales")
s.to_frame()

  Sales
0     A
1     B
2     C
3   NaN
4     D
5  None

In [55]:
print(s.count())

4

##### **3. Multiple Selection (Fancy Indexing)**
##### 3.1 var_name[[index1,index2,index3,...]]
##### 3.2 var_name.take()

##### **3.1 var_name[[index1,index2,index3...indexn]]**
##### It always return based on label. Based on that index the values going to be return
##### **Syntax : var_name[[index1,index2,index3,...]]**

In [56]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0     56
1     62
2     52
3     76
4     75
5     78

In [57]:
s[[5,3,2,0]]

5    78
3    76
2    52
0    56
Name: Sales, dtype: int32

In [63]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=[4,9,7,0,5,2],name="Sales")
s.to_frame()

   Sales
4     44
9     50
7     46
0     50
5     54
2     51

In [65]:
s[[2,0,4]]

2    51
0    50
4    44
Name: Sales, dtype: int32

In [66]:
s[[1,0,4]] #because 1 is not present in the index, hence it always take label based index.

KeyError: '[1] not in index'

##### **3.2 var_name.take()**
##### It always returns based on position not on number.Based on that index the values going to be return
##### **Syntax : var_name.take(indices, axis=0, is_copy=None)**
##### axis and is_copy is optional

In [58]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0     70
1     47
2     51
3     60
4     61
5     70

In [60]:
s.take(indices=[1,3,0])

1    47
3    60
0    70
Name: Sales, dtype: int32

In [67]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=[9,2,4,6,7,1],name="Sales")
s.to_frame()

   Sales
9     51
2     73
4     60
6     44
7     62
1     47

In [68]:
s.take(indices=[0,1,2,3]) #because it takes based on position not a index label. hence it always take position based index.

9    51
2    73
4    60
6    44
Name: Sales, dtype: int32

In [69]:
s.take(indices=[1,2,4]) #because it takes based on position not a index label. hence it always take position based index.

2    73
4    60
7    62
Name: Sales, dtype: int32

In [61]:
s.take(indices=[1,3,0],axis=0)

1    47
3    60
0    70
Name: Sales, dtype: int32

In [62]:
s.take(indices=[1,3,0],axis=1)

ValueError: No axis named 1 for object type Series

##### **4. Filtering / Boolean Selection**
##### 4.1 var_name[condition]
##### 4.2 var_name.where()
##### 4.3 var_name.mask()
##### 4.4 var_name.isin()
##### 4.5 var_name.between()
##### 4.6 var_name.all()
##### 4.7 var_name.any()

##### **4.1 var_name[condition]**
##### Based on the given condtion we will get data/rows
##### **Syntax : var_name[condition]**

In [70]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0     51
1     57
2     79
3     67
4     51
5     76

In [71]:
s[s>60]

2    79
3    67
5    76
Name: Sales, dtype: int32

In [74]:
s[s<60]

0    51
1    57
4    51
Name: Sales, dtype: int32

##### **4.2 var_name.where()**
##### It works based on the given condition
##### **Syntax : var_name.where(condition)**
##### **Syntax : var_name.where(cond, other=np.nan, inplace=False)**
##### other and inplace are optional here
##### inplace = True -> Returns new Series, IF False Modifies original Series.

In [97]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0     59
1     71
2     70
3     51
4     75
5     44

##### If condtion fails it returnsNaN as a Default FSB(False Statement Block)

In [98]:
s.where(s>60)

0     NaN
1    71.0
2    70.0
3     NaN
4    75.0
5     NaN
Name: Sales, dtype: float64

In [99]:
s.where((s>60) and (s>6))

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

##### If the values doesn't specifies the condition the value becomes False as a parameter passed or we can pass anything instead of False also.
##### If condtion fails it returns whatever we want to specify as a FSB(False Statement Block)

In [100]:
s.where(s>60,False)

0    False
1       71
2       70
3    False
4       75
5    False
Name: Sales, dtype: object

In [101]:
s.where(s>60,True)

0    True
1      71
2      70
3    True
4      75
5    True
Name: Sales, dtype: object

In [102]:
s.where(s>60,False)

0    False
1       71
2       70
3    False
4       75
5    False
Name: Sales, dtype: object

In [103]:
s.where(s>60,'Hello')

0    Hello
1       71
2       70
3    Hello
4       75
5    Hello
Name: Sales, dtype: object

In [104]:
s.where(s>60,other=np.nan)

0     NaN
1    71.0
2    70.0
3     NaN
4    75.0
5     NaN
Name: Sales, dtype: float64

In [105]:
s.where(s>60,other=np.nan,inplace=False)

0     NaN
1    71.0
2    70.0
3     NaN
4    75.0
5     NaN
Name: Sales, dtype: float64

In [106]:
s.to_frame()

   Sales
0     59
1     71
2     70
3     51
4     75
5     44

##### If inplace=True , Directly it modifies the Original Series.

In [108]:
s.where(s>60,other=np.nan,inplace=True)
s.to_frame()

   Sales
0    NaN
1   71.0
2   70.0
3    NaN
4   75.0
5    NaN

##### **4.3 var_name.mask()**
##### It replaces values where condition is TRUE
##### **Syntax : var_name.mask(cond, other=np.nan, inplace=False)**
##### condition is manadatory, other and inplace are optional here

In [121]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0     74
1     72
2     52
3     42
4     68
5     44

##### If the Condition is True, Then TSB is going to replace with NaN as a Default TSB(True Statement Block).

In [122]:
s.mask(s>50)

0     NaN
1     NaN
2     NaN
3    42.0
4     NaN
5    44.0
Name: Sales, dtype: float64

##### If the Condition is True, Then TSB is going to replace with Specific value/string/anything as a TSB(True Statement Block).

In [123]:
s.mask(s>50,other=False)

0    False
1    False
2    False
3       42
4    False
5       44
Name: Sales, dtype: object

In [124]:
s.mask(s>50,other=True)

0    True
1    True
2    True
3      42
4    True
5      44
Name: Sales, dtype: object

In [125]:
s.mask(s>50,other='Hello')

0    Hello
1    Hello
2    Hello
3       42
4    Hello
5       44
Name: Sales, dtype: object

In [126]:
s.mask(s>50,other='Hello',inplace=False)

0    Hello
1    Hello
2    Hello
3       42
4    Hello
5       44
Name: Sales, dtype: object

In [127]:
s.to_frame()

   Sales
0     74
1     72
2     52
3     42
4     68
5     44

##### If inplace=True ->Modifies Original Series. If inplace=False -> Creates a New Series.

In [128]:
s.mask(s>50,inplace=True)
s.to_frame()

   Sales
0    NaN
1    NaN
2    NaN
3   42.0
4    NaN
5   44.0

##### **NOTE : where() and mask() Both are Same But where() return NaN for FSB and mask() return NaN for TSB**

##### **4.5 var_name.between()**
##### It returns the boolean series()
##### **Syntax var_name.between(left, right, inclusive='both')**
##### Inclusive is optional. left and right are manadatory
##### left and right both are scalar and inclusive types - 'both'(default),'left','right','neither'

In [129]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0     74
1     74
2     60
3     64
4     40
5     78

##### If the values are between 40 to 60 then all valuse satifies this condition is True rest of other values are false.

In [131]:
s.between(40,60)

0    False
1    False
2     True
3    False
4     True
5    False
Name: Sales, dtype: bool

In [132]:
s.between(40,60,inclusive='left')

0    False
1    False
2    False
3    False
4     True
5    False
Name: Sales, dtype: bool

In [133]:
s.between(40,60,inclusive='right')

0    False
1    False
2     True
3    False
4    False
5    False
Name: Sales, dtype: bool

In [135]:
s.between(40,70,inclusive='neither')

0    False
1    False
2     True
3     True
4    False
5    False
Name: Sales, dtype: bool

In [136]:
s.between(40,60,inclusive='both')

0    False
1    False
2     True
3    False
4     True
5    False
Name: Sales, dtype: bool

##### **4.6 var_name.all()**
##### Returns True if ALL values are True (or non-zero).
##### **Syntax : var_name.all(axis=0, bool_only=None, skipna=True)**
##### axis,bool_only and skipna are optional
##### **Parameters**	
##### axis-Not important for Series (always 0)
##### bool_only-Only consider boolean values (rare use) True/False
##### skipna-Ignore NaN values. True/False

In [137]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(40,80,6),index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0     74
1     48
2     58
3     55
4     53
5     58

In [139]:
print(s.all())

True

In [140]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,np.nan,None,70,50],index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0   10.0
1   20.0
2    NaN
3    NaN
4   70.0
5   50.0

In [142]:
print(s.all())

True

In [143]:
print(s.all(axis=0))

True

In [144]:
print(s.all(axis=1)) # Because axis=1 works with DataFrame

ValueError: No axis named 1 for object type Series

##### Even though we doesn't specify boolean values it will consider numbers as boolean value it self.

In [148]:
print(s.all(bool_only=True))

True

In [147]:
print(s.all(bool_only=False))

True

In [149]:
s=pd.Series(data=[True,True,1,0,False],index=[0,1,2,3,4],name="Marks")
s.to_frame()

   Marks
0   True
1   True
2      1
3      0
4  False

##### Bool_only=False => False Because in series we also contains some numerical values also.

In [157]:
print(s.all(bool_only=False))

False

##### Bool_only=True => Error Because in series we also contains some numerical values also.Which is not allowed

In [150]:
print(s.all(bool_only=True))

TypeError: Series.all does not allow bool_only=True with non-numeric dtypes.

In [158]:
s=pd.Series(data=[True,True,True,False,False],index=[0,1,2,3,4],name="Marks")
s.to_frame()

   Marks
0   True
1   True
2   True
3  False
4  False

##### If all the values in series are True, Returns True

In [155]:
print(s.all(bool_only=True))

False

##### If False means other than bool we can also have other values.

In [156]:
print(s.all(bool_only=False))

False

In [159]:
s=pd.Series(data=[True,True,True,True,True],index=[0,1,2,3,4],name="Marks")
s.to_frame()

   Marks
0   True
1   True
2   True
3   True
4   True

In [160]:
print(s.all(bool_only=True))

True

##### If False means other than bool we can also have other values.

In [161]:
print(s.all(bool_only=False))

True

In [162]:
s=pd.Series(data=[False,False,False,False,False],index=[0,1,2,3,4],name="Marks")
s.to_frame()

   Marks
0  False
1  False
2  False
3  False
4  False

In [163]:
print(s.all(bool_only=False))

False

In [164]:
print(s.all(bool_only=False))

False

##### **Skipna** - Ignore NaN values or not, If skipna=True,Then ignore none Values,If False none values are considered as false.

In [166]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,np.nan,None,70,50],index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0   10.0
1   20.0
2    NaN
3    NaN
4   70.0
5   50.0

In [168]:
print(s.all(skipna=True))

True

In [169]:
print(s.all(skipna=False))

True

##### **4.7 var_name.any()**
##### Returns True if Any values are True (or non-zero).
##### **Syntax : var_name.any(axis=0, bool_only=None, skipna=True)**
##### axis,bool_only and skipna are optional
##### **Parameters**	
##### axis-Not important for Series (always 0)
##### bool_only-Only consider boolean values (rare use) True/False
##### skipna-Ignore NaN values. True/False

In [165]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,np.nan,None,70,50],index=np.arange(6),name="Sales")
s.to_frame()

   Sales
0   10.0
1   20.0
2    NaN
3    NaN
4   70.0
5   50.0

In [170]:
print(s.any())

True

In [171]:
print(s.any(axis=0))

True

In [172]:
print(s.any(bool_only=True))

True

In [173]:
print(s.any(bool_only=False))

True

In [174]:
print(s.any(skipna=True))

True

In [175]:
print(s.any(skipna=False))

True

##### **5. Values Analysis**
##### 5.1 var_name.unique()
##### 5.2 var_name.nunique()
##### 5.3 var_name.value_counts()

##### **5.1 var_name.unique()**
##### It returns the Unique value of the array
##### **Syntax : var_name.unique()**

In [6]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.choice([10,20,30],5,p=[0.1,0.1,0.8]),index=np.arange(5),name='Marks')
s.to_frame()

   Marks
0     30
1     30
2     30
3     10
4     30

In [7]:
s.unique()

array([30, 10])

##### **5.2 var_name.nunique()**
##### It returns the number of unique elements (total length of unique elements)
##### **Syntax : var_name.nunique(dropna=True)**
##### **Parameters**
##### dropna-Ignore NaN values or not

In [11]:
import pandas as pd
import numpy as np
s = pd.Series(data=[10,20,np.nan,20,10,30,40],index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0   10.0
1   20.0
2    NaN
3   20.0
4   10.0
5   30.0
6   40.0

In [12]:
s.nunique()

4

In [13]:
s.nunique(dropna=True)

4

##### It returns the number of unique elements with NaN consider as a Unique element amoung all data
##### dropna=False , Means It also consider null/none/nan value as a unique element

In [14]:
s.nunique(dropna=False)

5

##### **5.3 var_name.value_counts()**
##### **Syntax : var_name.value_counts(normalize=False, sort=True, ascending=False, bins=None, dropna=True)**
##### **Parameters**
##### normalize-Show proportions (percentage)
##### sort-Sort values or not
##### ascending-Sort order
##### bins-Group values into ranges(it always positive)Like Numbers
##### dropna-Include/exclude NaN

##### It returns the occurance count of each data/element in the series. For example if I have [10,20,10] - It return 10 -> 2 , 20 -> 1 count of values which are similar to each other

In [29]:
import pandas as pd
import numpy as np
s = pd.Series(data=[10,20,np.nan,20,10,30,40],index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0   10.0
1   20.0
2    NaN
3   20.0
4   10.0
5   30.0
6   40.0

In [30]:
s.value_counts()

Marks
10.0    2
20.0    2
30.0    1
40.0    1
Name: count, dtype: int64

##### If we have null values it exclude the null values in the count, other than null values it will counts each data

In [32]:
s.value_counts(normalize=False)

Marks
10.0    2
20.0    2
30.0    1
40.0    1
Name: count, dtype: int64

In [33]:
import pandas as pd
import numpy as np
s = pd.Series(data=[10,20,10,20,10,30,40],index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0     10
1     20
2     10
3     20
4     10
5     30
6     40

In [34]:
s.value_counts()

Marks
10    3
20    2
30    1
40    1
Name: count, dtype: int64

In [35]:
s.value_counts(normalize=False)

Marks
10    3
20    2
30    1
40    1
Name: count, dtype: int64

##### Instead of returning the count of each data in the series, It will return the values in the form of float with proportion.
##### It returns the count of each data in the form of the percentage.

In [28]:
s.value_counts(normalize=True)

Marks
10    0.428571
20    0.285714
30    0.142857
40    0.142857
Name: proportion, dtype: float64

In [41]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(10,50,7),index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0     43
1     34
2     44
3     17
4     23
5     38
6     37

##### It is sort the Entire data and returns the sorted new Series() with count of each data/value

In [40]:
s.value_counts(normalize=False)

Marks
16    1
29    1
48    1
12    1
15    1
49    1
30    1
Name: count, dtype: int64

In [42]:
s.value_counts(sort=False)

Marks
43    1
34    1
44    1
17    1
23    1
38    1
37    1
Name: count, dtype: int64

In [62]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20,10,30,40,20,30,30],index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0     20
1     10
2     30
3     40
4     20
5     30
6     30

##### The values are not in ascending order , Instead of value it will returns the ascending order for count of each value in the Series().

In [63]:
s.value_counts(ascending=True)

Marks
10    1
40    1
20    2
30    3
Name: count, dtype: int64

##### For Descending order we uses ascending as False

In [64]:
s.value_counts(ascending=False)

Marks
30    3
20    2
10    1
40    1
Name: count, dtype: int64

In [72]:
import pandas as pd
import numpy as np
s = pd.Series(data=[10, 15, 20, 25, 30, 35, 40],index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0     10
1     15
2     20
3     25
4     30
5     35
6     40

##### It divides your data range into n equal intervals (if bins=n). Then counts how many values fall into each bin
##### Step1:find min and max in series()
##### step2:max_value-min_value=new_bin_value
##### step3:new_bin_value/n , where n is interval for dividing eqaul bins
##### step4:The values are dividing based on the range, and that many count of each value will get
##### Example = [10, 15, 20, 25, 30, 35, 40]
##### min=10 ,max=40
##### max-min=40-10=30
##### 30/3 = 10 (n=3)
##### start from min by 10 to add another 10 bins to get a proper range
##### (10,20) Instead of 10 It will take 9.96 
##### Why 9.969 instead of 10? (9.969000000000001, 20.0] Because Pandas slightly adjusts lower bound, To make sure minimum value (10) is included. It’s just a floating-point adjustment (ignore it)
 | Bin       | Values              | Count |
 | --------- | ------------------- | ----- |
 | (10 → 20] | 10, 15, 20          | 3     |
 | (20 → 30] | 25, 30, 20? depends | 3     |
 | (30 → 40] | 35, 40              | 1     |

##### start and end value is included,Here again if started from (20,30]- It will excluded 20 Because which is already in count

In [75]:
s.value_counts(bins=3)

(9.969000000000001, 20.0]    3
(20.0, 30.0]                 2
(30.0, 40.0]                 2
Name: count, dtype: int64

##### It consider entire range from 10 to 40

In [73]:
s.value_counts(bins=True)

(9.969000000000001, 40.0]    7
Name: count, dtype: int64

In [76]:
import pandas as pd
import numpy as np
s = pd.Series(data=[10, 15, np.nan, 25, 30, 35, 40],index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0   10.0
1   15.0
2    NaN
3   25.0
4   30.0
5   35.0
6   40.0

##### null values are ignored

In [77]:
s.value_counts(bins=3)

(9.969000000000001, 20.0]    2
(20.0, 30.0]                 2
(30.0, 40.0]                 2
Name: count, dtype: int64

##### If we want to consider null values in the count we uses the dropna attribute

In [85]:
import pandas as pd
import numpy as np
s = pd.Series(data=[10, np.nan, np.nan, 25, 30, 35, 40],index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0   10.0
1    NaN
2    NaN
3   25.0
4   30.0
5   35.0
6   40.0

##### dropna → controls whether NaN values are counted or ignored,NaN values are ignored, Only numeric values are binned

In [88]:
s.value_counts(bins=3,dropna=True)

(20.0, 30.0]                 2
(30.0, 40.0]                 2
(9.969000000000001, 20.0]    1
Name: count, dtype: int64

##### s.value_counts(bins=3, dropna=False) :  Wrong expectation — NaN never goes inside intervals Hence if we use bins with dropna it will not work actually ,Because bins doesnot consider intervals as NaN. hence it gives same result.

In [90]:
s.value_counts(bins=3,dropna=True)

(20.0, 30.0]                 2
(30.0, 40.0]                 2
(9.969000000000001, 20.0]    1
Name: count, dtype: int64

In [96]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, np.nan, 20, np.nan, 15, 10, 35, 40,40],index=np.arange(9),name='Marks')
s.to_frame()

   Marks
0   20.0
1    NaN
2   20.0
3    NaN
4   15.0
5   10.0
6   35.0
7   40.0
8   40.0

In [103]:
s.value_counts(normalize=False, sort=True, ascending=False, bins=None, dropna=True)

Marks
20.0    2
40.0    2
15.0    1
10.0    1
35.0    1
Name: count, dtype: int64

In [105]:
s.value_counts(normalize=False, sort=True, ascending=False, bins=None, dropna=False)

Marks
20.0    2
NaN     2
40.0    2
15.0    1
10.0    1
35.0    1
Name: count, dtype: int64

In [106]:
s.value_counts(normalize=False, sort=False, ascending=True, bins=None, dropna=True)

Marks
20.0    2
15.0    1
10.0    1
35.0    1
40.0    2
Name: count, dtype: int64

##### **6. Sorting and Ordering**
##### 6.1 var_name.sort_values()
##### 6.2 var_name.sort_index()
##### 6.3 var_name.nlargest()
##### 6.4 var_name.nsmallest()
##### 6.5 var_name.rank()

##### **6.1 var_name.sort_values()**
##### **Syntax : var_name.sort_values(axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)**
##### **Parameters**
##### ascending-Sort order (True = ascending)
##### inplac-	Modify original Series
##### kind-Sorting algorithm
##### na_position-'first' or 'last'
##### ignore_index-Reset index after sorting
##### key-Function for custom sorting

In [136]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, np.nan, 20, np.nan, 15, 10, 35, 40,40],index=np.arange(9),name='Marks')
s.to_frame()

   Marks
0   20.0
1    NaN
2   20.0
3    NaN
4   15.0
5   10.0
6   35.0
7   40.0
8   40.0

##### If we are sorted the values, and in Sereis if we have NaN/Null Values it will take NaN as last

In [137]:
s.sort_values()

5    10.0
4    15.0
2    20.0
0    20.0
6    35.0
7    40.0
8    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

##### axis=0 Means it will sort row wise as we have Series means only one column will sort in row wise, In data Frame or Multiple concat sereis we will use axis=1

In [138]:
s.sort_values(axis=0)

5    10.0
4    15.0
2    20.0
0    20.0
6    35.0
7    40.0
8    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

In [139]:
s.sort_values(axis=1)

ValueError: No axis named 1 for object type Series

##### The values are in returns in an ascending order and the NaN values are place in last

In [140]:
s.sort_values(ascending=True)

5    10.0
4    15.0
2    20.0
0    20.0
6    35.0
7    40.0
8    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

In [141]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, np.nan, 20, np.nan, 15, 10, 35, 40,40],index=np.arange(9),name='Marks')
s.to_frame()

   Marks
0   20.0
1    NaN
2   20.0
3    NaN
4   15.0
5   10.0
6   35.0
7   40.0
8   40.0

##### This is original Series

In [144]:
s.to_frame()

   Marks
5   10.0
4   15.0
2   20.0
0   20.0
6   35.0
7   40.0
8   40.0
1    NaN
3    NaN

##### This is Modified Series Where each value is going to replace with a new value

In [142]:
s1=s.sort_values(inplace=True)

In [146]:
s1.to_frame()

   Marks1
0      28
1      42
2      30
3      12
4      35
5      36
6      25
7      21
8      49

##### (kind='quicksort') It is used for sorting algorithms
##### 'quicksort' = Not stable (order may change for equal values)
##### 'mergesort'=Stable → preserves original order of duplicates,                        
##### 'heapsort'=    Works fine, Not stable, Rarely used                                                        
##### 'stable'=     Always stable, Modern recommended option

In [147]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, np.nan, 20, np.nan, 15, 10, 35, 40,40],index=np.arange(9),name='Marks')
s.to_frame()

   Marks
0   20.0
1    NaN
2   20.0
3    NaN
4   15.0
5   10.0
6   35.0
7   40.0
8   40.0

In [148]:
s.sort_values(kind='quicksort')

5    10.0
4    15.0
2    20.0
0    20.0
6    35.0
7    40.0
8    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

In [149]:
s.sort_values(kind='mergesort')

5    10.0
4    15.0
0    20.0
2    20.0
6    35.0
7    40.0
8    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

In [150]:
s.sort_values(kind='heapsort')

5    10.0
4    15.0
0    20.0
2    20.0
6    35.0
8    40.0
7    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

In [152]:
s.sort_values(kind='stable')

5    10.0
4    15.0
0    20.0
2    20.0
6    35.0
7    40.0
8    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

##### **NOTE : With quicksort (may change order) , With mergesort (preserves order)**

##### **na_position** : we have two way first and last(default), It will decide NaN at end and first

In [153]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, np.nan, 20, np.nan, 15, 10, 35, 40,40],index=np.arange(9),name='Marks')
s.to_frame()

   Marks
0   20.0
1    NaN
2   20.0
3    NaN
4   15.0
5   10.0
6   35.0
7   40.0
8   40.0

In [154]:
s.sort_values(na_position='last')

5    10.0
4    15.0
2    20.0
0    20.0
6    35.0
7    40.0
8    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

In [155]:
s.sort_values(na_position='first')

1     NaN
3     NaN
5    10.0
4    15.0
2    20.0
0    20.0
6    35.0
7    40.0
8    40.0
Name: Marks, dtype: float64

##### **ignore_index** : It is used to whether the given specific index is ignore or not
##### if ignore_index=False means it will consider specific given index and that index also sort with respect to values.

In [157]:
s.sort_values(ignore_index=False)

5    10.0
4    15.0
2    20.0
0    20.0
6    35.0
7    40.0
8    40.0
1     NaN
3     NaN
Name: Marks, dtype: float64

##### if ignore_index=True means it will not consider specific given index which are also sort with respect to values.Instead of that it will take new index values from 0 to lenght-1

In [158]:
s.sort_values(ignore_index=True)

0    10.0
1    15.0
2    20.0
3    20.0
4    35.0
5    40.0
6    40.0
7     NaN
8     NaN
Name: Marks, dtype: float64

##### **key :** It is used to Apply a function before sorting
##### Allowed → lambda, map, vectorized ops, where, Not suitable → any(), all(), filter() (they don’t return same-length Series)

In [165]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, 20, 15, 10, 35, 40,40],index=np.arange(7),name='Marks')
s.to_frame()

   Marks
0     20
1     20
2     15
3     10
4     35
5     40
6     40

In [172]:
s.sort_values(key=lambda x : abs(x))

3    10
2    15
1    20
0    20
4    35
5    40
6    40
Name: Marks, dtype: int64

##### **6.2 var_name.sort_index()**
##### It used to sort the indexes based on given specific is going to be sort
##### **Syntax : var_name.sort_index(axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)**
##### **Parameters**
#####  ascending=True/False->True-Ascending order, False-Descending
##### inplace=False/True,True-Modifies original series,False-remain same
##### kind='quicksort','mergesort','heapsort','stable'- Sorting algorithms
##### na_position='last'/'first'-If first-NaN values are placed at top(first),If last-NaN values are placed at bottom(last)
##### ignore_index=True/False- If True-Indexes are ignored(given specific indexes are ignored and new indexes arre assigned from 0 to len-1),False-Index are reamin same
##### key=It is a function (lambda)

In [175]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, 20, 15, 10, 35, 40,40],index=np.random.randint(0,10,7),name='Marks')
s.to_frame()

   Marks
6     20
9     20
9     15
2     10
4     35
4     40
7     40

In [176]:
s.sort_index()

2    10
4    35
4    40
6    20
7    40
9    20
9    15
Name: Marks, dtype: int64

In [178]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, 20, 15, 10, 35, 40,40],index=np.random.choice([0,1,2,3,4,5,6,7,8,9,10],7,replace=False),name='Marks')
s.to_frame()

    Marks
2      20
3      20
0      15
9      10
5      35
6      40
10     40

In [179]:
s.sort_index()

0     15
2     20
3     20
5     35
6     40
9     10
10    40
Name: Marks, dtype: int64

In [181]:
s.sort_index(axis=0) #axis=1 used in DataFrame

0     15
2     20
3     20
5     35
6     40
9     10
10    40
Name: Marks, dtype: int64

##### Indexes are sort in Ascending order.

In [182]:
s.sort_index(ascending=True)

0     15
2     20
3     20
5     35
6     40
9     10
10    40
Name: Marks, dtype: int64

##### Indexes are sort in descending order.

In [183]:
s.sort_index(ascending=False)

10    40
9     10
6     40
5     35
3     20
2     20
0     15
Name: Marks, dtype: int64

##### Index values are replaced/modified if it is True

In [193]:
s.sort_index(inplace=False)

0     15
2     20
3     20
5     35
6     40
9     10
10    40
Name: Marks, dtype: int64

In [194]:
s.to_frame()

    Marks
0      15
2      20
3      20
5      35
6      40
9      10
10     40

##### inplace=True  → "change original",inplace=False → "create copy"But internally:
##### inplace=True  → changes s
##### inplace=False → keeps s unchanged

In [195]:
s.sort_index(inplace=True) 
s.to_frame()

    Marks
0      15
2      20
3      20
5      35
6      40
9      10
10     40

In [196]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, 20, 15, 10, 35, 40,40],index=np.random.choice([0,1,2,3,4,5,6,7,8,9,10],7,replace=False),name='Marks')
s.to_frame()

   Marks
8     20
0     20
9     15
2     10
1     35
7     40
5     40

In [199]:
s.sort_index()

0    20
1    35
2    10
5    40
7    40
8    20
9    15
Name: Marks, dtype: int64

##### Both sort_index() and sort_index(kind='quicksort') sort index → then why is kind needed?
##### Core Answer - sort_index() what to do, kind how to do
##### Sort numbers → task, Algorithm (quick/merge) → methodYou control:
##### where sort_index() it is just sorting index as a task, But with kind='quicksort' or other is used to control the speed, stability, behavior

In [205]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, 20, 15, 10, 35, 40,40],index=[0,4,2,5,6,2,4],name='Marks')
s.to_frame()

   Marks
0     20
4     20
2     15
5     10
6     35
2     40
4     40

In [206]:
s.sort_index(kind='quicksort')

0    20
2    15
2    40
4    20
4    40
5    10
6    35
Name: Marks, dtype: int64

In [210]:
s.sort_index(kind='mergesort')

0    20
2    15
2    40
4    20
4    40
5    10
6    35
Name: Marks, dtype: int64

In [211]:
s.sort_index(kind='heapsort')

0    20
2    15
2    40
4    40
4    20
5    10
6    35
Name: Marks, dtype: int64

In [212]:
s.sort_index(kind='stable')

0    20
2    15
2    40
4    20
4    40
5    10
6    35
Name: Marks, dtype: int64

##### na_position='last' = used to place the null values at last

In [214]:
import pandas as pd
import numpy as np
s = pd.Series(data=[20, 20, 15, 10, 35, 40,40],index=[7,9,3,np.nan,None,0,1],name='Marks')
s.to_frame()

     Marks
7.0     20
9.0     20
3.0     15
NaN     10
NaN     35
0.0     40
1.0     40

In [215]:
s.sort_index(na_position='last')

0.0    40
1.0    40
3.0    15
7.0    20
9.0    20
NaN    10
NaN    35
Name: Marks, dtype: int64

##### na_position='first' = used to place the null values at first

In [216]:
s.sort_index(na_position='first')

NaN    10
NaN    35
0.0    40
1.0    40
3.0    15
7.0    20
9.0    20
Name: Marks, dtype: int64

##### Ignore_index is used to ignore the specified sorted index or not
##### If False It remains same
##### If True the specied sorted index replcae the deafult indexes

In [217]:
s.sort_index(ignore_index=False)

0.0    40
1.0    40
3.0    15
7.0    20
9.0    20
NaN    10
NaN    35
Name: Marks, dtype: int64

In [218]:
s.sort_index(ignore_index=True)

0    40
1    40
2    15
3    20
4    20
5    10
6    35
Name: Marks, dtype: int64

##### key=Function

In [219]:
s.sort_index(key=lambda x : abs(x))

0.0    40
1.0    40
3.0    15
7.0    20
9.0    20
NaN    10
NaN    35
Name: Marks, dtype: int64

##### **6.3 var_name.nlargest()**
##### It returns which are largest values among all in the Series().
##### **Syntax : var_name.nlargest(n=5, keep='first')**
##### **Parameter**
##### n-Number of top values(by default it is n=5)
##### keep-'first', 'last', 'all' occurance of values

In [226]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(50,100,7),index=np.random.randint(0,50,7),name='Marks')
s.to_frame()

    Marks
15     75
13     98
40     82
48     89
6      96
19     87
44     70

##### By default it will take n=5 and returns the top 5 largest values in series

In [227]:
s.nlargest()

13    98
6     96
48    89
19    87
40    82
Name: Marks, dtype: int32

In [228]:
s.nlargest(n=7)

13    98
6     96
48    89
19    87
40    82
15    75
44    70
Name: Marks, dtype: int32

##### **Keep** : first/last/all It is used to keep only first occurance values, last occurance values or all values.
##### Controls which duplicates to keep when multiple values are equal keep	Meaning
##### 'first'(default)=Keep first occurrences
##### 'last'=Keep last occurrences
##### 'all'=Keep ALL duplicates

In [234]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(50,70,7),index=np.random.randint(0,10,7),name='Marks')
s.to_frame()

   Marks
9     63
9     52
2     53
0     52
2     52
6     51
0     68

##### We have to observe the indexes so we will get to know that how it is working, first occurance means in series whichever values are same , we need to keep first occarnce last occurance and all occurance

In [240]:
s.nlargest(keep='first')

0    68
9    63
2    53
9    52
0    52
Name: Marks, dtype: int32

In [241]:
s.nlargest(keep='last')

0    68
9    63
2    53
2    52
0    52
Name: Marks, dtype: int32

In [238]:
s.nlargest(keep='all')

0    68
9    63
2    53
9    52
0    52
2    52
Name: Marks, dtype: int32

##### **6.4 var_name.nsmallest()**
##### It returns which are largest values among all in the Series().
##### **Syntax : var_name.nsmallest(n=5, keep='first')**
##### **Parameter**
##### n-Number of top values(by default it is n=5)
##### keep-'first', 'last', 'all' occurance of values

In [242]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(50,100,7),index=np.random.randint(0,50,7),name='Marks')
s.to_frame()

    Marks
19     52
4      98
20     87
21     53
33     55
40     60
14     69

##### By default it will take n=5 and returns the top 5 largest values in series

In [249]:
s.nsmallest()

0    50
8    55
0    58
6    58
8    62
Name: Marks, dtype: int32

In [250]:
s.nsmallest(n=7)

0    50
8    55
0    58
6    58
8    62
2    65
1    69
Name: Marks, dtype: int32

##### **Keep** : first/last/all It is used to keep only first occurance values, last occurance values or all values.
##### Controls which duplicates to keep when multiple values are equal keep	Meaning
##### 'first'(default)=Keep first occurrences
##### 'last'=Keep last occurrences
##### 'all'=Keep ALL duplicates

In [251]:
import pandas as pd
import numpy as np
s = pd.Series(data=np.random.randint(50,70,7),index=np.random.randint(0,10,7),name='Marks')
s.to_frame()

   Marks
0     65
6     54
7     58
0     67
0     52
2     58
4     64

##### We have to observe the indexes so we will get to know that how it is working, first occurance means in series whichever values are same ,awe need to keep first occarnce last occurance and all occurance

In [252]:
s.nsmallest(keep='first')

0    52
6    54
7    58
2    58
4    64
Name: Marks, dtype: int32

In [253]:
s.nsmallest(keep='last')

0    52
6    54
2    58
7    58
4    64
Name: Marks, dtype: int32

In [254]:
s.nsmallest(keep='all')

0    52
6    54
7    58
2    58
4    64
Name: Marks, dtype: int32

##### **6.5 var_name.rank()**
##### Assigns rank (position) to each value in the Series, Smaller value → smaller rank (default)
##### **Syntax : rank(axis=0, method='average', numeric_only=False, na_option='keep', ascending=True, pct=False)**
##### **Parameters**
##### method-How to rank ties or How to handle duplicate values by giving average/min/max/first/dense
##### ascending-Order of series
##### numeric_only - True  → rank only numeric data, False → include all (Series usually numeric)
##### na_option-'keep', 'top', 'bottom' , How to handle NaN values
##### pct-Return percentage rank , True → return percentage rank, False → normal rank
##### **Methods for ranking**
##### 'average'-Average rank
##### 'min'-Minimum rank
##### 'max'-Maximum rank
##### 'first'-Order-based
##### 'dense'-No gaps

In [258]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(10,30,7),index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1      12
2      14
3      16
4      29
5      25
6      10
7      19

In [259]:
s.rank()

1    2.0
2    3.0
3    4.0
4    7.0
5    6.0
6    1.0
7    5.0
Name: Sample, dtype: float64

##### It assigns the rank to the values based on smaller value get higher rank like (1).
##### If we have two values that are same, then rank is distributed by 0.5 and 0.5 , both are getting same rank.

In [261]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(10,30,7),index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1      10
2      29
3      22
4      19
5      15
6      19
7      20

In [262]:
s.rank()

1    1.0
2    7.0
3    6.0
4    3.5
5    2.0
6    3.5
7    5.0
Name: Sample, dtype: float64

##### axis=0 means row wise ranking, we used axis=0 in Series, axis=1 for Data Frame

In [263]:
s.rank(axis=0)

1    1.0
2    7.0
3    6.0
4    3.5
5    2.0
6    3.5
7    5.0
Name: Sample, dtype: float64

In [263]:
s.rank(axis=0)

1    1.0
2    7.0
3    6.0
4    3.5
5    2.0
6    3.5
7    5.0
Name: Sample, dtype: float64

##### **method** : How to rank ties or How to handle duplicate values by giving average/min/max/first/dense
##### **Methods for ranking**
##### 'average'-Average rank
##### 'min'-Minimum rank
##### 'max'-Maximum rank
##### 'first'-Order-based
##### 'dense'-No gaps

In [266]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(10,30,7),index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1      16
2      24
3      25
4      29
5      20
6      16
7      22

##### It assigns the average rank if we have two same values.

In [267]:
s.rank(method='average')

1    1.5
2    5.0
3    6.0
4    7.0
5    3.0
6    1.5
7    4.0
Name: Sample, dtype: float64

##### It assigns the minimum rank if we have two same values. Like both values get minimum rank i,e 1 (which is round figured by min the number 1.5(default rank))

In [268]:
s.rank(method='min')

1    1.0
2    5.0
3    6.0
4    7.0
5    3.0
6    1.0
7    4.0
Name: Sample, dtype: float64

##### It assigns the maximum rank if we have two same values. Like both values get maximum rank i,e 2 (which is round figured by max the number 1.5(default rank))

In [269]:
s.rank(method='max')

1    2.0
2    5.0
3    6.0
4    7.0
5    3.0
6    2.0
7    4.0
Name: Sample, dtype: float64

##### It assigns the rank the one who have first in the series that number will get 1st rank then 2nd value which are same as first one

In [270]:
s.rank(method='first')

1    1.0
2    5.0
3    6.0
4    7.0
5    3.0
6    2.0
7    4.0
Name: Sample, dtype: float64

##### dense means no gap in the rank like min max or average

In [271]:
s.rank(method='dense')

1    1.0
2    4.0
3    5.0
4    6.0
5    2.0
6    1.0
7    3.0
Name: Sample, dtype: float64

##### numeric_only: used to assigns the rank to whether numbers only or strings or other form also. If True  → rank only numeric data, else False → include all (Series usually numeric)

In [300]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(10,30,7),index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1      16
2      25
3      26
4      22
5      12
6      16
7      12

In [301]:
s.rank(numeric_only=False)

1    3.5
2    6.0
3    7.0
4    5.0
5    1.5
6    3.5
7    1.5
Name: Sample, dtype: float64

In [302]:
s.rank(numeric_only=True)

1    3.5
2    6.0
3    7.0
4    5.0
5    1.5
6    3.5
7    1.5
Name: Sample, dtype: float64

##### The uppercase letter gets highest rank than lowercase , Based on ascii value it will asigns the rank.

In [295]:
import pandas as pd
import numpy as np
s=pd.Series(data=['C','A','L','a','M','Q','B'],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

  Sample
1      C
2      A
3      L
4      a
5      M
6      Q
7      B

In [296]:
s.rank()

1    3.0
2    1.0
3    4.0
4    7.0
5    5.0
6    6.0
7    2.0
Name: Sample, dtype: float64

##### numeric_only used to ranking the value for numeric data type only , If True means it allows only numeric value, else False non numeric also allowed

In [297]:
s.rank(numeric_only=True)

TypeError: Series.rank does not allow numeric_only=True with non-numeric dtype.

In [298]:
s.rank(numeric_only=False)

1    3.0
2    1.0
3    4.0
4    7.0
5    5.0
6    6.0
7    2.0
Name: Sample, dtype: float64

##### na_option='keep'/bottom/top : It is used how to handle NaN values

In [303]:
import pandas as pd
import numpy as np
s=pd.Series(data=['C','A','L',np.nan,'M','Q','B'],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

  Sample
1      C
2      A
3      L
4    NaN
5      M
6      Q
7      B

##### Keep = Keep the NaN value as NaN only. Do not assign any rank to the NaN value

In [304]:
s.rank(na_option='keep')

1    3.0
2    1.0
3    4.0
4    NaN
5    5.0
6    6.0
7    2.0
Name: Sample, dtype: float64

##### Top = Assign the Rank to NaN value as a Top Rank that is First Rank(1).

In [305]:
s.rank(na_option='top')

1    4.0
2    2.0
3    5.0
4    1.0
5    6.0
6    7.0
7    3.0
Name: Sample, dtype: float64

##### Bottom = Assign the Rank to NaN value as a Bottom(last) Rank that is Last Rank(last rank 7).

In [306]:
s.rank(na_option='bottom')

1    3.0
2    1.0
3    4.0
4    7.0
5    5.0
6    6.0
7    2.0
Name: Sample, dtype: float64

In [307]:
import pandas as pd
import numpy as np
s=pd.Series(data=[89,34,67,np.nan,90,23,47],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    89.0
2    34.0
3    67.0
4     NaN
5    90.0
6    23.0
7    47.0

##### Keep = Keep the NaN value as NaN only. Do not assign any rank to the NaN value

In [308]:
s.rank(na_option='keep')

1    5.0
2    2.0
3    4.0
4    NaN
5    6.0
6    1.0
7    3.0
Name: Sample, dtype: float64

##### Top = Assign the Rank to NaN value as a Top Rank that is First Rank(1).

In [309]:
s.rank(na_option='top')

1    6.0
2    3.0
3    5.0
4    1.0
5    7.0
6    2.0
7    4.0
Name: Sample, dtype: float64

##### Bottom = Assign the Rank to NaN value as a Bottom(last) Rank that is Last Rank(last rank 7).

In [310]:
s.rank(na_option='bottom')

1    5.0
2    2.0
3    4.0
4    7.0
5    6.0
6    1.0
7    3.0
Name: Sample, dtype: float64

In [313]:
s.to_frame()

   Sample
1    89.0
2    34.0
3    67.0
4     NaN
5    90.0
6    23.0
7    47.0

##### Rank in ascending order

In [311]:
s.rank(ascending=True)

1    5.0
2    2.0
3    4.0
4    NaN
5    6.0
6    1.0
7    3.0
Name: Sample, dtype: float64

##### Rank in descending order

In [312]:
s.rank(ascending=False)

1    2.0
2    5.0
3    3.0
4    NaN
5    1.0
6    6.0
7    4.0
Name: Sample, dtype: float64

##### pct- Return percentage rank , True → return percentage rank, False → normal rank

In [314]:
s.to_frame()

   Sample
1    89.0
2    34.0
3    67.0
4     NaN
5    90.0
6    23.0
7    47.0

##### Step 1: Remove NaN (for ranking)
##### Step 2: Sort (ascending=True)
##### Step 3: Assign RankStep 
##### Step4: Convert to Percentage (pct=True)
##### Example : 
##### Series Data :
| Index| Value |
| -----| ----  |
| 1    | 89    |
| 2    | 34    |
| 3    | 67    |
| 4    | NaN   |
| 5    | 90    |
| 6    | 23    |
| 7    | 47    |
##### Removes NaN : 23, 34, 47, 67, 89, 90
##### Sorted in Ascending Ordder : 23 < 34 < 47 < 67 < 89 < 90
##### Assigned the Rank :
| Value | Rank |
| ----- | ---- |
| 23    | 1    |
| 34    | 2    |
| 47    | 3    |
| 67    | 4    |
| 89    | 5    |
| 90    | 6    |

##### Calculated PCT(percentage Rank) : pct rank = rank / total_count
         = rank / 6
| Index | Value | Rank | pct              |
| ----- | ----- | ---- | ---------------- |
| 1     | 89    | 5    | 5/6 = **0.8333** |
| 2     | 34    | 2    | 2/6 = **0.3333** |
| 3     | 67    | 4    | 4/6 = **0.6667** |
| 4     | NaN   | NaN  | NaN              |
| 5     | 90    | 6    | 6/6 = **1.0000** |
| 6     | 23    | 1    | 1/6 = **0.1667** |
| 7     | 47    | 3    | 3/6 = **0.5000** |

In [319]:
s.rank(pct=True)

1    0.833333
2    0.333333
3    0.666667
4         NaN
5    1.000000
6    0.166667
7    0.500000
Name: Sample, dtype: float64

In [320]:
s.rank(pct=False)

1    5.0
2    2.0
3    4.0
4    NaN
5    6.0
6    1.0
7    3.0
Name: Sample, dtype: float64

##### It assigns the rank based on ascii value...

In [287]:
ord('A')

65

In [288]:
ord('1')

49

In [289]:
import pandas as pd
import numpy as np
s=pd.Series(data=['C','A','L','1','M','Q','B'],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

  Sample
1      C
2      A
3      L
4      1
5      M
6      Q
7      B

In [290]:
s.rank()

1    4.0
2    2.0
3    5.0
4    1.0
5    6.0
6    7.0
7    3.0
Name: Sample, dtype: float64

In [291]:
import pandas as pd
import numpy as np
s=pd.Series(data=['C','A','L',1,'M','Q','B'],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

  Sample
1      C
2      A
3      L
4      1
5      M
6      Q
7      B

In [292]:
s.rank()

TypeError: '<' not supported between instances of 'int' and 'str'

##### **7. Mathematical Operations**
##### 7.1 var_name.sum()
##### 7.2 var_name.mean()
##### 7.3 var_name.median()
##### 7.4 var_name.mode()
##### 7.5 var_name.min()
##### 7.6 var_name.max()
##### 7.7 var_name.std()
##### 7.8 var_name.var()
##### 7.9 var_name.prod()
##### 7.10 var_name.cumsum()
##### 7.11 var_name.cumprod()

##### **7.1 var_name.sum()**
##### Returns the total (sum) of all values in the Series
##### **Syntax : var_name.sum(axis=None, skipna=True, numeric_only=False, min_count=0)**
##### **Parameters**
##### axis-None / 0	Series → always 0
##### skipna-True / False	Ignore NaN or not
##### numeric_only-True / False	Only numeric (Series → mostly ignored)
##### min_count-int	Minimum values required

In [3]:
import pandas as pd
import numpy as np
s=pd.Series(data=np.random.randint(30,70,7),index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1      55
2      39
3      30
4      61
5      54
6      41
7      37

In [5]:
s.sum().item()

317

In [8]:
s.sum(axis=0).item()

317

In [9]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,98,34,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    98.0
3    34.0
4    12.0
5     NaN
6    45.0
7    89.0

In [14]:
s.sum().item()

334.0

##### **Skipna** : True-Ignore NaN, False-Include NaN → result becomes NaN

In [15]:
s.sum(skipna=True).item()

334.0

In [16]:
s.sum(skipna=False).item()

nan

##### **numeric_only :** True  → only numeric values, False → include all (Series usually numeric). In Series → mostly ignored unless mixed data

In [23]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,98,34,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    98.0
3    34.0
4    12.0
5     NaN
6    45.0
7    89.0

In [24]:
s.sum(numeric_only=True).item()

334.0

In [25]:
s.sum(numeric_only=False).item()

334.0

In [26]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,98,34,12,'A',45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

  Sample
1     56
2     98
3     34
4     12
5      A
6     45
7     89

In [27]:
s.sum(numeric_only=False).item()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [28]:
s.sum(numeric_only=True).item()

TypeError: Series.sum does not allow numeric_only=True with non-numeric dtypes.

In [33]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,98,np.nan,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    98.0
3     NaN
4    12.0
5     NaN
6    45.0
7    89.0

##### **min_count** : Minimum number of non-NaN values required, If it is 0 (default)=always compute sum, else >0=require minimum valid values.
##### Why both are giving SAME answer? Because your data already satisfies: number of non-NaN values ≥ min_count.
##### Rule of min_count - If valid (non-NaN) values ≥ min_count → return sum, Else → return NaN

In [34]:
s.sum(min_count=2).item()

300.0

In [37]:
s.sum(skipna=True,min_count=5).item() #6>5 True - Sum()

300.0

In [38]:
s.sum(skipna=True,min_count=7).item() #6>7 False - NaN

nan

##### **7.2 var_name.mean()**
##### It returns the Mean value of the series.
##### **Syntax : var_name.mean(axis=None, skipna=True, numeric_only=False)**
##### **Parameters**
##### skipna-True->Ignore NaN, False->Include NaN → result NaN

In [39]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,98,np.nan,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    98.0
3     NaN
4    12.0
5     NaN
6    45.0
7    89.0

In [41]:
s.mean().item()

60.0

In [42]:
s.mean(axis=0).item()

60.0

##### If skipna=True Returns mean Else False returns NaN

In [43]:
s.mean(skipna=True).item()

60.0

In [44]:
s.mean(skipna=False).item()

nan

In [45]:
s.mean(numeric_only=False).item()

60.0

In [46]:
s.mean(numeric_only=True).item()

60.0

In [47]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,'A',np.nan,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

  Sample
1     56
2      A
3    NaN
4     12
5    NaN
6     45
7     89

In [48]:
s.mean(numeric_only=True).item()

TypeError: Series.mean does not allow numeric_only=True with non-numeric dtypes.

In [49]:
s.mean(numeric_only=False).item()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

##### **7.3 var_name.median()**
##### It returns the Median value of the series.
##### **Syntax : var_name.median(axis=None, skipna=True, numeric_only=False)**
##### step1: sort the series in ascending order.
##### step2: find the median(middle value), If series count is even - the median is average between two number, else odd - the median is that number onlu.

In [50]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,np.nan,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3     NaN
4    12.0
5     NaN
6    45.0
7    89.0

##### Odd Count Series : Where NaN values are ignored

In [52]:
s.median().item()

56.0

##### Even Count Series : Where NaN values are ignored

In [54]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,89,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3    89.0
4    12.0
5     NaN
6    45.0
7    89.0

In [55]:
s.median().item()

67.0

In [56]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,np.nan,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3     NaN
4    12.0
5     NaN
6    45.0
7    89.0

In [58]:
s.median(axis=0).item()

56.0

In [59]:
s.median(skipna=True).item()

56.0

In [61]:
s.median(skipna=False)

nan

In [62]:
s.median(numeric_only=True).item()

56.0

In [63]:
s.median(numeric_only=False).item()

56.0

##### **7.4 var_name.mode()**
##### Returns the most frequently occurring value(s) in the Series
##### **Syntax : var_name.mode(dropna=True)**
##### **Parameters**
##### dropna-True->Ignore NaN, False->Include NaN in result

In [68]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,58,np.nan,12,np.nan,56,89,89],index=[1,2,3,4,5,6,7,8],name="Sample")
s.to_frame()

   Sample
1    56.0
2    58.0
3     NaN
4    12.0
5     NaN
6    56.0
7    89.0
8    89.0

In [69]:
s.mode()

0    56.0
1    89.0
Name: Sample, dtype: float64

In [70]:
s.mode(dropna=True)

0    56.0
1    89.0
Name: Sample, dtype: float64

In [71]:
s.mode(dropna=False)

0    56.0
1    89.0
2     NaN
Name: Sample, dtype: float64

In [64]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,np.nan,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3     NaN
4    12.0
5     NaN
6    45.0
7    89.0

In [65]:
s.mode()

0    12.0
1    45.0
2    56.0
3    78.0
4    89.0
Name: Sample, dtype: float64

In [67]:
s.mode(dropna=True)

0    12.0
1    45.0
2    56.0
3    78.0
4    89.0
Name: Sample, dtype: float64

In [66]:
s.mode(dropna=False)

0   NaN
Name: Sample, dtype: float64

##### **7.5 var_name.min()**
##### It returns the minimum value in the series.
##### **Syntax : var_name.min(axis=None, skipna=True)**
##### **Parameters**
##### skipna=True-Ignore NaN
##### skipna=False-Result becomes NaN

In [73]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3    98.0
4    12.0
5     NaN
6    45.0
7    89.0

In [74]:
s.min().item()

12.0

In [75]:
s.min(axis=0).item()

12.0

In [76]:
s.min(skipna=True).item()

12.0

In [77]:
s.min(skipna=False).item()

nan

##### **7.6 var_name.max()**
##### It returns the maximum value in the series.
##### **Syntax : var_name.max(axis=None, skipna=True)**

In [78]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3    98.0
4    12.0
5     NaN
6    45.0
7    89.0

In [79]:
s.max().item()

98.0

In [80]:
s.max(axis=0).item()

98.0

In [82]:
s.max(skipna=True).item()

98.0

In [81]:
s.max(skipna=False).item()

nan

##### **7.7 var_name.std()**
##### It returns the standard deviation of the series.
##### **Syntax : var_name.std(axis=None, skipna=True, ddof=1)**
##### **Parameters**
##### skipna-True/False	Ignore NaN
##### ddof-1 (default)->Sample std, 0->Population std

In [83]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3    98.0
4    12.0
5     NaN
6    45.0
7    89.0

In [85]:
s.std().item()

31.937438845342623

In [86]:
s.std(axis=0).item()

31.937438845342623

In [87]:
s.std(skipna=True).item()

31.937438845342623

In [88]:
s.std(skipna=False).item()

nan

##### ddof = Delta Degrees of Freedom. It controls the denominator in standard deviation formula.
##### Population Standard Deviation
##### σ = √( Σ(x - mean)² / N )
##### Sample Standard Deviation
##### s = √( Σ(x - mean)² / (N - 1) )

In [90]:
s.std(ddof=0).item()

29.154759474226502

In [91]:
s.std(ddof=1).item()

31.937438845342623

##### **7.8 var_name.var()**
##### It returns the variance of the series.
##### **Syntax : var_name.var(axis=None, skipna=True, ddof=1)**

In [92]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3    98.0
4    12.0
5     NaN
6    45.0
7    89.0

In [94]:
s.var().item()

1020.0

In [95]:
s.var(axis=0).item()

1020.0

In [96]:
s.var(skipna=True).item()

1020.0

In [97]:
s.var(skipna=False).item()

nan

In [98]:
s.var(ddof=0).item()

850.0

In [99]:
s.var(ddof=1).item()

1020.0

##### **7.9 var_name.prod()**
##### It returns the product of entire series(multiplication).
##### **Syntax : var_name.prod(axis=None, skipna=True, min_count=0)**
##### **Parameters**
##### skipna-Ignore NaN
##### min_count-Minimum values required

In [100]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3    98.0
4    12.0
5     NaN
6    45.0
7    89.0

In [104]:
s.prod().item()

20572755840.0

In [105]:
s.prod(axis=0).item()

20572755840.0

In [106]:
s.prod(skipna=True).item()

20572755840.0

In [107]:
s.prod(skipna=False).item()

nan

In [108]:
s.prod(min_count=0).item()

20572755840.0

In [109]:
s.prod(min_count=8).item()

nan

In [110]:
s.prod(min_count=5).item()

20572755840.0

##### **7.10 var_name.cumsum()**
##### It returns the Computes cumulative (running) sum of values. Each value = previous total + current value
##### **Syntax : var_name.cumsum(axis=None, skipna=True)**
##### **Parameter**
##### skipna=True-Continue ignoring NaN
##### skipna=False-Stops after NaN
| Value | Cumulative Sum |
| ----- | -------------- |
| 10    | 10             |
| 20    | 10 + 20 = 30   |
| 30    | 30 + 30 = 60   |
| 40    | 60 + 40 = 100  |

In [111]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1    56.0
2    78.0
3    98.0
4    12.0
5     NaN
6    45.0
7    89.0

In [112]:
s.cumsum()

1     56.0
2    134.0
3    232.0
4    244.0
5      NaN
6    289.0
7    378.0
Name: Sample, dtype: float64

In [113]:
s.cumsum(axis=0)

1     56.0
2    134.0
3    232.0
4    244.0
5      NaN
6    289.0
7    378.0
Name: Sample, dtype: float64

In [114]:
s.cumsum(skipna=True)

1     56.0
2    134.0
3    232.0
4    244.0
5      NaN
6    289.0
7    378.0
Name: Sample, dtype: float64

##### Here if we specify tht skipna=False, It means it will not skip null values and NaN+NaN=NaN gets each time once we encountered the NaN.

In [115]:
s.cumsum(skipna=False)

1     56.0
2    134.0
3    232.0
4    244.0
5      NaN
6      NaN
7      NaN
Name: Sample, dtype: float64

##### **7.11 var_name.cumprod()**
##### It returns the Computes cumulative (running) prod of values. Each value = previous total * current value
##### **Syntax : var_name.cumprod(axis=None, skipna=True)**

In [121]:
import pandas as pd
import numpy as np
s=pd.Series(data=[6,8,9,1,np.nan,5,8],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1     6.0
2     8.0
3     9.0
4     1.0
5     NaN
6     5.0
7     8.0

In [122]:
s.cumprod()

1        6.0
2       48.0
3      432.0
4      432.0
5        NaN
6     2160.0
7    17280.0
Name: Sample, dtype: float64

In [123]:
s.cumprod(axis=0)

1        6.0
2       48.0
3      432.0
4      432.0
5        NaN
6     2160.0
7    17280.0
Name: Sample, dtype: float64

In [124]:
s.cumprod(skipna=True)

1        6.0
2       48.0
3      432.0
4      432.0
5        NaN
6     2160.0
7    17280.0
Name: Sample, dtype: float64

In [125]:
s.cumprod(skipna=False)

1      6.0
2     48.0
3    432.0
4    432.0
5      NaN
6      NaN
7      NaN
Name: Sample, dtype: float64

##### **7.12 var_name.cummin()**
##### It returns the Computes cumulative (running) min of values. Each value = min(previous total,current value)
##### **Syntax : var_name.cummin(axis=None, skipna=True)**

In [135]:
import pandas as pd
import numpy as np
s=pd.Series(data=[6,8,9,1,np.nan,5,8],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1     6.0
2     8.0
3     9.0
4     1.0
5     NaN
6     5.0
7     8.0

##### The First Vaue in Series always remains same, Because there is no privious value to compare for min. The second value compares with first value,whichever is minimum returns that value only.
##### **NOTE :** Once we get min value by comparing first and second it will consider the same value as min instead of privious one.

In [136]:
s.cummin()

1    6.0
2    6.0
3    6.0
4    1.0
5    NaN
6    1.0
7    1.0
Name: Sample, dtype: float64

In [137]:
s.cummin(skipna=True)

1    6.0
2    6.0
3    6.0
4    1.0
5    NaN
6    1.0
7    1.0
Name: Sample, dtype: float64

##### **7.13 var_name.cummax()**
##### It returns the Computes cumulative (running) max of values. Each value = max(previous total,current value)
##### Returns cumulative mximum till current position
##### **Syntax : var_name.cummax(axis=None, skipna=True)**

In [140]:
import pandas as pd
import numpy as np
s=pd.Series(data=[6,8,9,1,np.nan,5,8],index=[1,2,3,4,5,6,7],name="Sample")
s.to_frame()

   Sample
1     6.0
2     8.0
3     9.0
4     1.0
5     NaN
6     5.0
7     8.0

##### The First Vaue in Series always remains same, Because there is no privious value to compare for max. The second value compares with first value,whichever is maximum returns that value only.
##### **NOTE :** Once we get max value by comparing first and second it will consider the same value as max instead of privious one.

In [141]:
s.cummax()

1    6.0
2    8.0
3    9.0
4    9.0
5    NaN
6    9.0
7    9.0
Name: Sample, dtype: float64

In [142]:
s.cummax(skipna=True)

1    6.0
2    8.0
3    9.0
4    9.0
5    NaN
6    9.0
7    9.0
Name: Sample, dtype: float64

##### **8. Combining & Operations**
##### 8.1 var_name.add()
##### 8.2 var_name.sub()
##### 8.3 var_name.mul()
##### 8.4 var_name.div()
##### 8.5 var_name.combine()
##### 8.6 var_name.combine_first()
##### 8.7 var_name.update()
##### 8.8 var_name.concat()

##### **8.1 var_name.add()**
##### It adds the one series with other series and Even if count of both series or length of both series are not same, it will consider last value as Nan.
##### **Syntax : var_name.add(other, level=None, fill_value=None)**
##### **Parameter**
##### Other is manadatory, level and fill_value are optional.
##### other-Series / scalar(other series)
##### level-For MultiIndex
##### fill_value-Replace missing values before operation

In [30]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1     56.0     56.0
2     78.0     78.0
3     98.0     98.0
4     12.0     12.0
5      NaN      NaN
6     45.0     45.0
7     89.0     89.0

In [31]:
s.add(s1)

1    112.0
2    156.0
3    196.0
4     24.0
5      NaN
6     90.0
7    178.0
dtype: float64

In [32]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[56,78,98,np.nan,12,45,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1     56.0     56.0
2     78.0     78.0
3     98.0     98.0
4     12.0      NaN
5      NaN     12.0
6     45.0     45.0
7     89.0     89.0

In [33]:
s.add(s1)

1    112.0
2    156.0
3    196.0
4      NaN
5      NaN
6     90.0
7    178.0
dtype: float64

In [34]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[56,78,98,np.nan,45,89],index=[1,2,3,4,5,6],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1     56.0     56.0
2     78.0     78.0
3     98.0     98.0
4     12.0      NaN
5      NaN     45.0
6     45.0     89.0
7     89.0      NaN

In [139]:
s.add(s1)

1    112.0
2    156.0
3    196.0
4      NaN
5      NaN
6    134.0
7      NaN
Name: Sample, dtype: float64

In [35]:
import pandas as pd
import numpy as np
s=pd.Series(data=[56,78,98,12,np.nan,45,89],index=['A',2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[56,78,98,12,np.nan,45,89],index=['A',2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
A     56.0     56.0
2     78.0     78.0
3     98.0     98.0
4     12.0     12.0
5      NaN      NaN
6     45.0     45.0
7     89.0     89.0

##### level is used with MultiIndex, and you must pass a level name or level number that actually exists. Why level=2 is wrong here=Your Series has NORMAL index → not MultiIndex, No levels exist → only one index level

In [36]:
s.add(s1,level=1)

A    112.0
2    156.0
3    196.0
4     24.0
5      NaN
6     90.0
7    178.0
dtype: float64

In [38]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[56,78,98,12,np.nan,45,89],index=[1,2,3,4,5,6,7],name="Sample1")
s2=pd.Series(data=[56,78,98,10,12,45,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s1,s2],axis=1)

   Sample1  Sample2
1     56.0       56
2     78.0       78
3     98.0       98
4     12.0       10
5      NaN       12
6     45.0       45
7     89.0       89

In [39]:
s1.add(s2)

1    112.0
2    156.0
3    196.0
4     22.0
5      NaN
6     90.0
7    178.0
dtype: float64

##### Replaces missing values (NaN) BEFORE performing the operation. Where fill_values is filled by specific value inplace of NaN. Instead of displaying NaN it will filed by other value

In [40]:
s1.add(s2,fill_value=0)

1    112.0
2    156.0
3    196.0
4     22.0
5     12.0
6     90.0
7    178.0
dtype: float64

In [41]:
s1.add(s2,fill_value=9)

1    112.0
2    156.0
3    196.0
4     22.0
5     21.0
6     90.0
7    178.0
dtype: float64

##### **8.2 var_name.sub()**
##### It substract the one series with other series and Even if count of both series or length of both series are not same, it will consider last value as Nan.
##### **Syntax : var_name.sub(other, level=None, fill_value=None)**

In [42]:
import pandas as pd
import numpy as np
s=pd.Series(data=[96,98,78,82,np.nan,75,99],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[16,24,48,np.nan,23,44,34],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1     96.0     16.0
2     98.0     24.0
3     78.0     48.0
4     82.0      NaN
5      NaN     23.0
6     75.0     44.0
7     99.0     34.0

In [43]:
s.sub(s1)

1    80.0
2    74.0
3    30.0
4     NaN
5     NaN
6    31.0
7    65.0
dtype: float64

In [44]:
s.sub(s1,level=1)

1    80.0
2    74.0
3    30.0
4     NaN
5     NaN
6    31.0
7    65.0
dtype: float64

In [45]:
s.sub(s1,fill_value=100)

1    80.0
2    74.0
3    30.0
4   -18.0
5    77.0
6    31.0
7    65.0
dtype: float64

##### **8.3 var_name.mul()**
##### It multiplies the one series with other series and Even if count of both series or length of both series are not same, it will consider last value as Nan.
##### **Syntax : var_name.mul(other, level=None, fill_value=None)**

In [46]:
import pandas as pd
import numpy as np
s=pd.Series(data=[6,7,8,2,np.nan,4,8],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[5,5,5,np.nan,5,4,9],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1      6.0      5.0
2      7.0      5.0
3      8.0      5.0
4      2.0      NaN
5      NaN      5.0
6      4.0      4.0
7      8.0      9.0

In [47]:
s.mul(s1)

1    30.0
2    35.0
3    40.0
4     NaN
5     NaN
6    16.0
7    72.0
dtype: float64

In [48]:
s.mul(s1,level=1)

1    30.0
2    35.0
3    40.0
4     NaN
5     NaN
6    16.0
7    72.0
dtype: float64

In [49]:
s.mul(s1,fill_value=10)

1    30.0
2    35.0
3    40.0
4    20.0
5    50.0
6    16.0
7    72.0
dtype: float64

##### **8.4 var_name.div()**
##### It divides the one series with other series and Even if count of both series or length of both series are not same, it will consider last value as Nan.
##### **Syntax : var_name.div(other, level=None, fill_value=None)**

In [50]:
import pandas as pd
import numpy as np
s=pd.Series(data=[60,70,80,20,np.nan,40,80],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[5,5,5,np.nan,5,4,9],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1     60.0      5.0
2     70.0      5.0
3     80.0      5.0
4     20.0      NaN
5      NaN      5.0
6     40.0      4.0
7     80.0      9.0

In [51]:
s.div(s1)

1    12.000000
2    14.000000
3    16.000000
4          NaN
5          NaN
6    10.000000
7     8.888889
dtype: float64

In [52]:
s.div(s1,level=1)

1    12.000000
2    14.000000
3    16.000000
4          NaN
5          NaN
6    10.000000
7     8.888889
dtype: float64

In [53]:
s.div(s1,fill_value=10)

1    12.000000
2    14.000000
3    16.000000
4     2.000000
5     2.000000
6    10.000000
7     8.888889
dtype: float64

##### **8.5 var_name.combine()**
##### It combines the two series based on the given function(max,min) If We specify the function as max means in both the sereis, the value1 of both sereis compares and one which has more values.maximum values that will display in series.
##### **Syntax : var_name.combine(other, func, fill_value=None)**
##### other and func is manadatory
##### **Parameter**
##### other-Another Series
##### func-Function (like max, min)
##### fill_value-Replace missing values

In [80]:
import pandas as pd
import numpy as np
s=pd.Series(data=[26,37,28,22,23,44,85],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[45,25,45,np.nan,55,74,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1       26     45.0
2       37     25.0
3       28     45.0
4       22      NaN
5       23     55.0
6       44     74.0
7       85     89.0

1    20.0   max(10,20)
2    50.0   max(50,30)
3    60.0   max(0,60)
4    40.0   max(40,0)
5     0.0   max(0,NaN→0)

In [81]:
s.combine(s1,max)

1    45
2    37
3    45
4    22
5    55
6    74
7    89
dtype: int64

In [82]:
s.combine(s1,min)

1    26
2    25
3    28
4    22
5    23
6    44
7    85
dtype: int64

In [83]:
s.combine(s1,lambda x, y: x + y)

1     71.0
2     62.0
3     73.0
4      NaN
5     78.0
6    118.0
7    174.0
dtype: float64

In [84]:
s.combine(s1,lambda x, y: x if x > y else y)

1    45.0
2    37.0
3    45.0
4     NaN
5    55.0
6    74.0
7    89.0
dtype: float64

In [85]:
s.combine(s1,max,fill_value=100)

1    45
2    37
3    45
4    22
5    55
6    74
7    89
dtype: int64

##### At index 5 → one or both values were NaN , AND no fill_value was useds1[5] = NaN, s2[5] = somethingmax(NaN, value) → Na
##### min(NaN, value) → NaN, x + NaN → NaN

In [87]:
import pandas as pd
import numpy as np
s=pd.Series(data=[26,37,28,22,np.nan,44,85],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[45,25,45,np.nan,55,74,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1     26.0     45.0
2     37.0     25.0
3     28.0     45.0
4     22.0      NaN
5      NaN     55.0
6     44.0     74.0
7     85.0     89.0

In [88]:
s.combine(s1,min,fill_value=100)

1    26.0
2    25.0
3    28.0
4    22.0
5     NaN
6    44.0
7    85.0
dtype: float64

##### **8.6 var_name.combine_first()**
##### Fill missing (NaN) values in the current Series using values from another Series => "Use s1 first, if missing → take from s2"
##### First it will gives the current series values, If NaN is encountered then it will take the value from second series instead of fill_value.
##### **Syntax : var_name.combine_first(other)**
##### Fill missing values from another Series

In [89]:
import pandas as pd
import numpy as np
s=pd.Series(data=[26,37,28,22,23,44,85],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[45,25,45,np.nan,55,74,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1       26     45.0
2       37     25.0
3       28     45.0
4       22      NaN
5       23     55.0
6       44     74.0
7       85     89.0

In [90]:
s.combine_first(s1)

C:\Users\User\AppData\Local\Temp\ipykernel_17204\236891893.py:1: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  s.combine_first(s1)

1    26
2    37
3    28
4    22
5    23
6    44
7    85
Name: Sample1, dtype: int64

In [94]:
import pandas as pd
import numpy as np
s=pd.Series(data=[26,37,28,22,23,44,85],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[45,25,45,None,55,74,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1       26     45.0
2       37     25.0
3       28     45.0
4       22      NaN
5       23     55.0
6       44     74.0
7       85     89.0

##### Fill missing (NaN) values in the current Series using values from another Series => "Use s1 first, if missing → take from s2"
##### First it will gives the current series values, If NaN is encountered then it will take the value from second series instead of fill_value.

In [95]:
s.combine_first(s1)

C:\Users\User\AppData\Local\Temp\ipykernel_17204\236891893.py:1: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  s.combine_first(s1)

1    26
2    37
3    28
4    22
5    23
6    44
7    85
Name: Sample1, dtype: int64

In [97]:
s1.combine_first(s)

1    45.0
2    25.0
3    45.0
4    22.0
5    55.0
6    74.0
7    89.0
Name: Sample2, dtype: float64

##### **8.7 var_name.update()**
##### Updates values in the original Series using another Series. (only non-NaN values from other are used) or "Overwrite s1 values using s2 where s2 has data"
##### **Syntax : var_name.update(other)**
##### Updates original Series (inplace)

In [114]:
import pandas as pd
import numpy as np
s=pd.Series(data=[26,37,28,None,23,44,85],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[45,25,45,40,55,74,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1     26.0       45
2     37.0       25
3     28.0       45
4      NaN       40
5     23.0       55
6     44.0       74
7     85.0       89

##### What update() does (IMPORTANT)=> Replace ALL values in s with values from s1 (only if s1 value is NOT NaN)

In [116]:
s.update(s1)
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1     45.0       45
2     25.0       25
3     45.0       45
4     40.0       40
5     55.0       55
6     74.0       74
7     89.0       89

In [106]:
import pandas as pd
import numpy as np
s=pd.Series(data=[26,37,28,22,23,44,85],index=[1,2,3,4,5,6,7],name="Sample1")
s1=pd.Series(data=[45,25,45,39,55,74,89],index=[1,2,3,4,5,6,7],name="Sample2")
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1       26       45
2       37       25
3       28       45
4       22       39
5       23       55
6       44       74
7       85       89

##### Updates values in the original Series using another Series. (only non-NaN values from other are used) or "Overwrite s1 values using s2 where s2 has data"

In [107]:
s.update(s1)
pd.concat([s,s1],axis=1)

   Sample1  Sample2
1       45       45
2       25       25
3       45       45
4       39       39
5       55       55
6       74       74
7       89       89

##### **8.8 pd.concat()**
##### Combines multiple Series/DataFrames along rows or columns - "Just attach data — no calculation"
##### **Syntax : pd.concat(objs, axis=0, join='outer', ignore_index=False)**
##### **Parameter**
##### objs-list of Series
##### axis-0 → rows, 1 → columns
##### ignore_index-reset index

In [124]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[26,37,28,22,23],index=[1,2,3,4,5],name="Sample1")
s2=pd.Series(data=[45,25,45,39,55],index=[1,2,3,4,5],name="Sample2")
s3=pd.Series(data=[43,25,55,84,82],index=[1,2,3,4,5],name="Sample3")

In [125]:
s=pd.concat([s1,s2,s3])
s.to_frame()

    0
1  26
2  37
3  28
4  22
5  23
1  45
2  25
3  45
4  39
5  55
1  43
2  25
3  55
4  84
5  82

##### Axis=0 Row wise(default) , Axis=1 Column wise

In [126]:
s=pd.concat([s1,s2,s3],axis=0)
s.to_frame()

    0
1  26
2  37
3  28
4  22
5  23
1  45
2  25
3  45
4  39
5  55
1  43
2  25
3  55
4  84
5  82

##### If the axis=1 and Indexes of each series are same then it will concat the series based on indexes only (since indexes are same all values are concat with respect to index)

In [128]:
pd.concat([s1,s2,s3],axis=1)

   Sample1  Sample2  Sample3
1       26       45       43
2       37       25       25
3       28       45       55
4       22       39       84
5       23       55       82

In [131]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[26,37,28,22,23],index=[1,2,3,4,5],name="Sample1")
s2=pd.Series(data=[45,25,45,39,55],index=[6,7,8,9,10],name="Sample2")
s3=pd.Series(data=[43,25,55,84,82],index=[11,12,13,14,15],name="Sample3")

##### If the axis=1 and Indexes of each series are different from each Series, then it will concat the series based on indexes.(since indexes are different all values are concat with respect to index, and other series values are filled with NaN)
##### Example : s1 => has 5 values with 5 different indexs, s2 => has 5 values with 5 different indexs, s3 => has 5 values with 5 different indexs

In [132]:
pd.concat([s1,s2,s3],axis=1)

    Sample1  Sample2  Sample3
1      26.0      NaN      NaN
2      37.0      NaN      NaN
3      28.0      NaN      NaN
4      22.0      NaN      NaN
5      23.0      NaN      NaN
6       NaN     45.0      NaN
7       NaN     25.0      NaN
8       NaN     45.0      NaN
9       NaN     39.0      NaN
10      NaN     55.0      NaN
11      NaN      NaN     43.0
12      NaN      NaN     25.0
13      NaN      NaN     55.0
14      NaN      NaN     84.0
15      NaN      NaN     82.0

##### join Meaning =>'outer' (default) union (ALL indexes), 'inner' => intersection(COMMON indexes only)
##### join='outer' → take ALL indexes, Since all have same index → full table shown
##### NaN appears where: data is missing inside series
##### Take ALL indexes (union) : Keeps everything, Missing values → NaN

In [138]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[26,37,28,22,23],index=[1,2,3,4,5],name="Sample1")
s2=pd.Series(data=[45,25,np.nan,39,55],index=[1,2,3,4,5],name="Sample2")
s3=pd.Series(data=[43,np.nan,55,84,82],index=[1,2,3,4,5],name="Sample3")

In [139]:
pd.concat([s1,s2,s3],axis=1,join='outer')

   Sample1  Sample2  Sample3
1       26     45.0     43.0
2       37     25.0      NaN
3       28      NaN     55.0
4       22     39.0     84.0
5       23     55.0     82.0

In [140]:
pd.concat([s1,s2,s3],axis=1,join='inner')

   Sample1  Sample2  Sample3
1       26     45.0     43.0
2       37     25.0      NaN
3       28      NaN     55.0
4       22     39.0     84.0
5       23     55.0     82.0

In [146]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[26,37,28,22,55],index=[1,2,3,4,5],name="Sample1")
s2=pd.Series(data=[45,25,np.nan,39,55],index=[1,2,3,4,5],name="Sample2")
s3=pd.Series(data=[43,90,55,84,55],index=[1,2,3,4,5],name="Sample3")

##### Why it's SAME as normal concat, Because ALL your Series have the SAME index
##### Check:
##### s1 index → [1,2,3,4,5]
##### s2 index → [1,2,3,4,5]
##### s3 index → [1,2,3,4,5]
##### Key Rule : If indexes are identical:outer join == inner join == normal concat

In [147]:
pd.concat([s1,s2,s3],axis=1,join='inner')

   Sample1  Sample2  Sample3
1       26     45.0       43
2       37     25.0       90
3       28      NaN       55
4       22     39.0       84
5       55     55.0       55

##### **join :** outer = union(outer = All indexes among the series
##### inner = Intersection(inner = only COMMON indexes among the series)

In [164]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[26,37,28,22,23],index=[1,2,3,4,5],name="Sample1")
s2=pd.Series(data=[26,37,None,22,23],index=[6,2,8,4,1],name="Sample2")
s3=pd.Series(data=[26,37,28,22,23],index=[1,2,13,4,15],name="Sample3")
pd.concat([s1,s2,s3],axis=1)

    Sample1  Sample2  Sample3
1      26.0     23.0     26.0
2      37.0     37.0     37.0
3      28.0      NaN      NaN
4      22.0     22.0     22.0
5      23.0      NaN      NaN
6       NaN     26.0      NaN
8       NaN      NaN      NaN
13      NaN      NaN     28.0
15      NaN      NaN     23.0

##### inner = Intersection(inner = only COMMON indexes among the series)

In [165]:
pd.concat([s1,s2,s3],axis=1,join='inner')

   Sample1  Sample2  Sample3
1       26     23.0       26
2       37     37.0       37
4       22     22.0       22

##### outer = union(outer = All indexes among the series

In [166]:
pd.concat([s1,s2,s3],axis=1,join='outer')

    Sample1  Sample2  Sample3
1      26.0     23.0     26.0
2      37.0     37.0     37.0
3      28.0      NaN      NaN
4      22.0     22.0     22.0
5      23.0      NaN      NaN
6       NaN     26.0      NaN
8       NaN      NaN      NaN
13      NaN      NaN     28.0
15      NaN      NaN     23.0

##### ignore_index(with respect to column name) = True/False, True=Menas it will ignore assigned column name with respect to series and by deafult returns new column name from 0 to len-1, False=Means column name will remain as it is.

In [167]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[26,37,28,22,23],index=[1,2,3,4,5],name="Sample1")
s2=pd.Series(data=[26,37,None,22,23],index=[6,2,8,4,1],name="Sample2")
s3=pd.Series(data=[26,37,28,22,23],index=[1,2,13,4,15],name="Sample3")
pd.concat([s1,s2,s3],axis=1,ignore_index=True)

       0     1     2
1   26.0  23.0  26.0
2   37.0  37.0  37.0
3   28.0   NaN   NaN
4   22.0  22.0  22.0
5   23.0   NaN   NaN
6    NaN  26.0   NaN
8    NaN   NaN   NaN
13   NaN   NaN  28.0
15   NaN   NaN  23.0

In [168]:
pd.concat([s1,s2,s3],axis=1,ignore_index=False)

    Sample1  Sample2  Sample3
1      26.0     23.0     26.0
2      37.0     37.0     37.0
3      28.0      NaN      NaN
4      22.0     22.0     22.0
5      23.0      NaN      NaN
6       NaN     26.0      NaN
8       NaN      NaN      NaN
13      NaN      NaN     28.0
15      NaN      NaN     23.0

##### **9. Apply-Map-Transform Method**
##### 9.1 var_name.apply()
##### 9.2 var_name.map()
##### 9.3 var_name.transform()

##### **9.1 var_name.apply()**
##### **Syntax : var_name.apply(func, convert_dtype=True, args=(), \*\*kwargs)**
##### **Parameters**
##### func-function / lambda-Operation applied to each value/Applies a function to each element of the Series
##### convert_dtype-True / False-Try to convert result dtype
##### args-tuple-Extra arguments to function
##### **kwargs	—	Additional parameters

In [179]:
import pandas as pd
import numpy as np
s=pd.Series(data=[26,37,28,22,23],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1      26
2      37
3      28
4      22
5      23

In [180]:
s.apply(lambda x:x+x)

1    52
2    74
3    56
4    44
5    46
Name: Sample, dtype: int64

In [186]:
def add(x, y):
    return x + y
s.apply(add, args=(100,))

1    126
2    137
3    128
4    122
5    123
Name: Sample, dtype: int64

##### Try to convert result to better dtype automatically
##### Why dtype: object ?
convert_dtype=False → disables automatic type conversion 
| Setting                        | Output dtype |
| ------------------------------ | ------------ |
| `convert_dtype=True` (default) | float64      |
| `convert_dtype=False`          | object       |

In [194]:
s.to_frame()

   Sample
1      26
2      37
3      28
4      22
5      23

In [195]:
s.apply(lambda x:x/100)

1    0.26
2    0.37
3    0.28
4    0.22
5    0.23
Name: Sample, dtype: float64

In [196]:
s.apply(lambda x:x/100,convert_dtype=False)

C:\Users\User\AppData\Local\Temp\ipykernel_17204\241892386.py:1: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  s.apply(lambda x:x/100,convert_dtype=False)

1    0.26
2    0.37
3    0.28
4    0.22
5    0.23
Name: Sample, dtype: object

In [197]:
s.apply(lambda x:x/100,convert_dtype=True)

C:\Users\User\AppData\Local\Temp\ipykernel_17204\2749778580.py:1: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  s.apply(lambda x:x/100,convert_dtype=True)

1    0.26
2    0.37
3    0.28
4    0.22
5    0.23
Name: Sample, dtype: float64

##### args → extra positional arguments passed to the function

##### add(x, y)
##### → x = value from Series
##### → y = 5 (from args)

In [200]:
import pandas as pd
import numpy as np
s=pd.Series(data=[26,37,28,22,23],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1      26
2      37
3      28
4      22
5      23

In [201]:
def add(x, y):
    return x + y
s.apply(add, args=(100,))

1    126
2    137
3    128
4    122
5    123
Name: Sample, dtype: int64

##### kwargs → extra keyword arguments (named arguments)

In [204]:
import pandas as pd
import numpy as np
s=pd.Series(data=[2,3,4,5,6],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1       2
2       3
3       4
4       5
5       6

In [205]:
def add(x, p=2):
    return x**p
s.apply(add, p=4)

1      16
2      81
3     256
4     625
5    1296
Name: Sample, dtype: int64

In [206]:
def add(x, p=2):
    return x**p
s.apply(add)

1     4
2     9
3    16
4    25
5    36
Name: Sample, dtype: int64

##### **9.2 var_name.map()**
##### Maps / transforms each value in a Series using:
##### ✔ function
##### ✔ dictionary
##### ✔ another Series
##### **Syntax : var_name.map(arg, na_action=None)**
##### **Parameters**
##### arg-function / dict / Series	Mapping logic
##### na_action-None / 'ignore'	Skip NaN or not
##### Replace / transform values using: function, dictionary, another Series

In [226]:
import pandas as pd
import numpy as np
s=pd.Series(data=[2,3,4,5,6],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1       2
2       3
3       4
4       5
5       6

##### map using function

In [227]:
s.map(lambda x: x * 2)

1     4
2     6
3     8
4    10
5    12
Name: Sample, dtype: int64

In [228]:
import pandas as pd
import numpy as np
s=pd.Series(data=['A','B','C','D','E'],index=[1,2,3,4,5],name="Sample")
s.to_frame()

  Sample
1      A
2      B
3      C
4      D
5      E

##### map using dictionary

In [229]:
s.map({'A': 100, 'B': 200, 'C': 300, 'D':400,'E':500})

1    100
2    200
3    300
4    400
5    500
Name: Sample, dtype: int64

##### If key is missing then NaN

In [230]:
s.map({'A': 100, 'B': 200, 'C': 300})

1    100.0
2    200.0
3    300.0
4      NaN
5      NaN
Name: Sample, dtype: float64

In [232]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,30,np.nan,50],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1    10.0
2    20.0
3    30.0
4     NaN
5    50.0

##### None(default)=Apply function to ALL values (including NaN), 'ignore'=Skip NaN values

In [233]:
s.map(lambda x: x*2, na_action='ignore')

1     20.0
2     40.0
3     60.0
4      NaN
5    100.0
Name: Sample, dtype: float64

In [235]:
s.map(lambda x: x*2, na_action=None)

1     20.0
2     40.0
3     60.0
4      NaN
5    100.0
Name: Sample, dtype: float64

##### **9.3 var_name.transform()**
##### Applies a function to each element AND returns output of SAME SIZE as original Series
##### **Syntax** : var_name.transform(func, axis=0, *args, **kwargs)
##### **Parameters**
##### func-function
##### axis-Series → always 0
##### *args-extra arguments
##### **kwargs-extra keyword arguments
##### Apply function but output size must be SAME as input

In [236]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,30,np.nan,50],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1    10.0
2    20.0
3    30.0
4     NaN
5    50.0

In [237]:
s.transform(lambda x: x * 2)

1     20.0
2     40.0
3     60.0
4      NaN
5    100.0
Name: Sample, dtype: float64

In [239]:
s.transform(lambda x: x * 2,axis=0)

1     20.0
2     40.0
3     60.0
4      NaN
5    100.0
Name: Sample, dtype: float64

In [259]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,30,np.nan,50],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1    10.0
2    20.0
3    30.0
4     NaN
5    50.0

In [260]:
s.transform(lambda x: x).to_frame()

   Sample
1    10.0
2    20.0
3    30.0
4     NaN
5    50.0

In [261]:
def add(x, y):
    return x + y
s.transform(lambda x: add(x, 5))

1    15.0
2    25.0
3    35.0
4     NaN
5    55.0
Name: Sample, dtype: float64

##### **10. Missing Data Handling**
##### 10.1 var_name.isna() / var_name.isnull()
##### 10.2 var_name.notna() / var_name.notnull()
##### 10.3 var_name.dropna()
##### 10.4 var_name.fillna()
##### 10.5 var_name.interpolate()

##### **10.1 var_name.isna() / var_name.isnull()**
##### Returns True where value is NaN
##### **Syntax : var_name.isna() or var_name.isnull()**

In [262]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,30,np.nan,50],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1    10.0
2    20.0
3    30.0
4     NaN
5    50.0

##### If NaN/Null/None Value is their in series it returns as Boolean value True If we have NaN value

In [263]:
s.isna()

1    False
2    False
3    False
4     True
5    False
Name: Sample, dtype: bool

In [264]:
s.isnull()

1    False
2    False
3    False
4     True
5    False
Name: Sample, dtype: bool

##### **10.2 var_name.notna() / var_name.notnull()**
##### Returns True where value is NOT NaN
##### **Syntax : var_name.notna() or var_name.notnull()**

In [265]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,30,np.nan,50],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1    10.0
2    20.0
3    30.0
4     NaN
5    50.0

##### If NaN/Null/None Value is their in series, it returns as Boolean value False If we have NaN value

In [266]:
s.notna()

1     True
2     True
3     True
4    False
5     True
Name: Sample, dtype: bool

In [267]:
s.notnull()

1     True
2     True
3     True
4    False
5     True
Name: Sample, dtype: bool

##### **10.3 var_name.dropna()**
##### It will remove the NaN/Null value from the series and result returns as it is after deleting the entire row that contains the NaN
##### **Syntax : var_name.dropna(axis=0, inplace=False, how=None)**
##### **Parameters**
##### axis-0->Only option for Series
##### inplace-True / False->Modify original or return new
##### how(ignored)-Not used in Series

In [284]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,20,30,np.nan,50],index=[1,2,3,4,5],name="Sample")
s.to_frame()

   Sample
1    10.0
2    20.0
3    30.0
4     NaN
5    50.0

In [285]:
s.dropna()

1    10.0
2    20.0
3    30.0
5    50.0
Name: Sample, dtype: float64

In [286]:
s.dropna(axis=0)

1    10.0
2    20.0
3    30.0
5    50.0
Name: Sample, dtype: float64

##### inplace is used to whether modify the original array or not.
##### inplace=true : modifies the original array
##### inplace=False : remains same

In [287]:
s.dropna(inplace=False)

1    10.0
2    20.0
3    30.0
5    50.0
Name: Sample, dtype: float64

In [288]:
s.dropna(inplace=True)

In [289]:
s.to_frame()

   Sample
1    10.0
2    20.0
3    30.0
5    50.0

##### **how:** Controls WHEN to drop rows/columns based on NaN values
##### 'any'=(default)	Drop if ANY NaN is present, 'all'=Drop only if ALL values are NaN
##### how(ignored)-Not used in Series

In [292]:
s.dropna(how=any)

1    10.0
2    20.0
3    30.0
5    50.0
Name: Sample, dtype: float64

In [293]:
s.dropna(how=all)

1    10.0
2    20.0
3    30.0
5    50.0
Name: Sample, dtype: float64

##### **10.4 var_name.fillna()**
##### The NaN values are placed by specified value, Instead of NaN it will display specified value.
##### **Syntax : var_name.fillna(value=None, method=None, axis=None, inplace=False, limit=None)**
##### **Parameters**
##### value-scalar/dict	Replace NaN with value
##### method-'ffill' / 'bfill'	Forward / backward fill
##### inplace-True / False->Modify original
##### limit-int->Max consecutive fills

In [309]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14,np.nan,28,np.nan,16], index=np.arange(5),name='Sample')
s.to_frame()

   Sample
0    14.0
1     NaN
2    28.0
3     NaN
4    16.0

##### The NaN values are filled by specific value.

In [310]:
s.fillna(value=10)

0    14.0
1    10.0
2    28.0
3    10.0
4    16.0
Name: Sample, dtype: float64

##### ForwardFill It is used to fill the Null/NaN value by its top value.

In [311]:
s.fillna(method='ffill')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\1029756637.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method='ffill')

0    14.0
1    14.0
2    28.0
3    28.0
4    16.0
Name: Sample, dtype: float64

##### BackwardFill It is used to fill the Null/NaN value by its Bottom value.

In [312]:
s.fillna(method='bfill')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\1641295691.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method='bfill')

0    14.0
1    28.0
2    28.0
3    16.0
4    16.0
Name: Sample, dtype: float64

In [313]:
import pandas as pd
import numpy as np
s=pd.Series(data=[np.nan,14,28,16,np.nan], index=np.arange(5),name='Sample')
s.to_frame()

   Sample
0     NaN
1    14.0
2    28.0
3    16.0
4     NaN

##### ForwardFill It is used to fill the Null/NaN value by its top value. Here there is no top value hence it remains NaN.

In [314]:
s.fillna(method='ffill')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\1029756637.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method='ffill')

0     NaN
1    14.0
2    28.0
3    16.0
4    16.0
Name: Sample, dtype: float64

##### BackwardFill It is used to fill the Null/NaN value by its bottom value. Here there is no bottom value hence it remains NaN.

In [316]:
s.fillna(method='bfill')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\1641295691.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.fillna(method='bfill')

0    14.0
1    14.0
2    28.0
3    16.0
4     NaN
Name: Sample, dtype: float64

In [317]:
import pandas as pd
import numpy as np
s=pd.Series(data=[np.nan,14,28,16,np.nan], index=np.arange(5),name='Sample')
s.to_frame()

   Sample
0     NaN
1    14.0
2    28.0
3    16.0
4     NaN

In [318]:
s.fillna(value=10,axis=0)

0    10.0
1    14.0
2    28.0
3    16.0
4    10.0
Name: Sample, dtype: float64

In [319]:
s.fillna(value=10,inplace=False)

0    10.0
1    14.0
2    28.0
3    16.0
4    10.0
Name: Sample, dtype: float64

In [321]:
s.fillna(value=10,inplace=True)
s.to_frame()

   Sample
0    10.0
1    14.0
2    28.0
3    16.0
4    10.0

##### limit → maximum number of NaN values to fill

In [325]:
import pandas as pd
import numpy as np
s=pd.Series(data=[np.nan,14,28,16,np.nan], index=np.arange(5),name='Sample')
s.to_frame()

   Sample
0     NaN
1    14.0
2    28.0
3    16.0
4     NaN

##### Without limit, NaN filled with 0

In [326]:
s.fillna(0)

0     0.0
1    14.0
2    28.0
3    16.0
4     0.0
Name: Sample, dtype: float64

##### With limit, NaN filled with 0 but only one NaN value filled by 0

In [329]:
s.fillna(0,limit=1)

0     0.0
1    14.0
2    28.0
3    16.0
4     NaN
Name: Sample, dtype: float64

##### With limit, NaN filled with 0 by two NaN value filled by 0

In [330]:
s.fillna(0,limit=2)

0     0.0
1    14.0
2    28.0
3    16.0
4     0.0
Name: Sample, dtype: float64

##### **10.5 var_name.interpolate()**
##### Fills NaN using estimated values based on existing data
##### **Syntax : var_name.interpolate(method='linear', axis=0, limit=None, inplace=False, limit_direction=None)**
##### **Parameters**
##### method-'linear'->Fill using interpolation
##### limit-int->Max fills
##### limit_direction-'forward' / 'backward' / 'both'	Direction
##### inplace-True / False->Modify original

In [339]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[3,7,1,9,2],name='Sample')
s.to_frame()

   Sample
3    14.0
7     NaN
1    28.0
9     NaN
2    34.0

##### types of methods :
##### 1. linear (DEFAULT) = Uses straight-line calculation between values     
##### 2. index = Uses index values for interpolation   
##### 3. values = Similar to index, but uses actual numeric values 
##### 4. nearest = Fills with nearest known value 
##### 5. zero=Step-wise (constant value fill) 
##### 6. slinear, quadratic, cubic => slinear=linear spline, quadratic=degree 2 curve, cubic=degree 3 curve 
##### 7. pad / ffill=Same as forward fill 
##### 8. backfill / bfill=same as backword 
##### 9. time (for time index)=Works with datetime index

##### 1. linear (DEFAULT) = Uses straight-line calculation between values     
##### Example : [14,NaN,28,NaN,34]=> 14+28=42,42/2=21 The NaN=21, 28+34=62,62/2=31 The NaN=31

In [355]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1    14.0
2     NaN
3    28.0
4     NaN
5    34.0

In [340]:
s.interpolate(method='linear')

3    14.0
7    21.0
1    28.0
9    31.0
2    34.0
Name: Sample, dtype: float64

##### 2. index = Uses index values for interpolation   
##### Uses index spacing (not position)
##### **NOTE :** 
##### If we have NaN value between the two values then we have to do the sum of two values and that value is divide by 2 , whatever value we will get filled that value with NaN.
##### If we have NaN value Before the Integer Value , It will reamins as it is as NaN only.
##### If we have NaN value After the Integer value , It will filled the NaN value from its top values
##### Example : indexs=[2,7,1,9,3] sort it=[1,2,3,7,9]=>[28,14,34,NaN,NaN] hence the value which is last before NaN that value is filled by 34 to all NaN.

In [366]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[2,7,1,9,3],name='Sample')
s.to_frame()

   Sample
2    14.0
7     NaN
1    28.0
9     NaN
3    34.0

In [369]:
s.interpolate(method='index')

7    14.0
2    31.0
1    28.0
9    14.0
3    34.0
Name: Sample, dtype: float64

##### Example : indexs=[7,2,1,9,3] sort it=[1,2,3,7,9]=>[28,NaN,34,14,NaN] Here Between 28 and 34 We have NaN value, hence we need to calculate 28+34=62,62/2=31 So NaN filled by 31, then 14 NaN there is no another value hence directly filled by 14 itself.
##### hence the value which is last before NaN that value is filled by 14.

In [367]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[7,2,1,9,3],name='Sample')
s.to_frame()

   Sample
7    14.0
2     NaN
1    28.0
9     NaN
3    34.0

In [368]:
s.interpolate(method='index')

7    14.0
2    31.0
1    28.0
9    14.0
3    34.0
Name: Sample, dtype: float64

In [370]:
import pandas as pd
import numpy as np
s=pd.Series(data=[np.nan,14,28,np.nan,34], index=[1,7,2,9,3],name='Sample')
s.to_frame()

   Sample
1     NaN
7    14.0
2    28.0
9     NaN
3    34.0

##### Example : indexs=[1,7,2,9,3] sort it=[1,2,3,7,9]=>[NaN,28,34,14,NaN] Here we dont have NaN value between two integer values and one NaN value we have just before the 28 hence we can't fill by any value,It remains as it is NaN, 2nd NaN value is just after the value 14 hence that value is filled by 14

In [372]:
s.interpolate(method='index')

1     NaN
7    14.0
2    28.0
9    14.0
3    34.0
Name: Sample, dtype: float64

##### 3. values = Similar to index, but uses actual numeric values
##### What method='values' means : Uses the actual index VALUES (numeric) to calculate interpolation
##### It treats your Series like (x, y) points
##### x → index
##### y → values
##### For a missing value between two points: y = y1 + ( (x - x1) / (x2 - x1) ) * (y2 - y1)
##### Example : We want value at index 3
##### Known points:
##### x1 = 1 → y1 = 10
##### x2 = 5 → y2 = 30
##### x  = 3 → ?
##### Apply formula:
##### y = 10 + ((3 - 1) / (5 - 1)) * (30 - 10)
##### y = 10 + (2/4) * 20
##### y = 10 + 10
##### y = 20
##### ✅ Output
##### 1    10.0
##### 3    20.0
##### 5    30.0

In [377]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[7,2,1,9,3],name='Sample')
s.to_frame()

   Sample
7    14.0
2     NaN
1    28.0
9     NaN
3    34.0

In [378]:
s.interpolate(method='values')

7    14.0
2    31.0
1    28.0
9    14.0
3    34.0
Name: Sample, dtype: float64

##### 4. nearest = Fills with nearest known value 
##### Fill NaN using the nearest available value (based on index distance), Instead of calculating (like linear), it simply picks the closest value

In [383]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1    14.0
2     NaN
3    28.0
4     NaN
5    34.0

In [384]:
s.interpolate(method='nearest')

1    14.0
2    14.0
3    28.0
4    28.0
5    34.0
Name: Sample, dtype: float64

In [391]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[9,8,4,3,2],name='Sample')
s.to_frame()

   Sample
9    14.0
8     NaN
4    28.0
3     NaN
2    34.0

In [392]:
s.interpolate(method='nearest')

9    14.0
8    14.0
4    28.0
3    34.0
2    34.0
Name: Sample, dtype: float64

In [393]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[9,8,5,3,2],name='Sample')
s.to_frame()

   Sample
9    14.0
8     NaN
5    28.0
3     NaN
2    34.0

In [394]:
s.interpolate(method='nearest')

9    14.0
8    14.0
5    28.0
3    34.0
2    34.0
Name: Sample, dtype: float64

In [395]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[9,8,4,10,2],name='Sample')
s.to_frame()

    Sample
9     14.0
8      NaN
4     28.0
10     NaN
2     34.0

In [396]:
s.interpolate(method='nearest')

9     14.0
8     14.0
4     28.0
10     NaN
2     34.0
Name: Sample, dtype: float64

##### 5. zero=Step-wise (constant value fill) 
##### Zero-order interpolation (step function),It fills NaN with the previous known value,No calculation, no averaging.It is also works with index

In [399]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1    14.0
2     NaN
3    28.0
4     NaN
5    34.0

In [400]:
s.interpolate(method='zero')

1    14.0
2    14.0
3    28.0
4    28.0
5    34.0
Name: Sample, dtype: float64

In [401]:
import pandas as pd
import numpy as np
s=pd.Series(data=[14, np.nan,28,np.nan,34], index=[2,1,5,4,3],name='Sample')
s.to_frame()

   Sample
2    14.0
1     NaN
5    28.0
4     NaN
3    34.0

##### It is also works with index , First we need to sort based on index =[1,2,3,4,5]=>[NaN,14,34,NaN,28]==> NaN's Privious(Before any value to the NaN) is no values hence rremains as NaN, 2nd NaN's privious one is 34 , so it replace with 34

In [402]:
s.interpolate(method='zero')

2    14.0
1     NaN
5    28.0
4    34.0
3    34.0
Name: Sample, dtype: float64

##### 6. slinear, quadratic, cubic => slinear=linear spline, quadratic=degree 2 curve, cubic=degree 3 curve **works with index based**
##### These are polynomial / spline interpolation methods → They estimate values using curves instead of straight lines
##### i.sliner(spline linear) Piecewise linear interpolation (like linear but via spline system)=>Almost same result as linear, but internally uses spline
##### ii.quadratic (Degree 2 curve) = Needs at least 3 known points
##### iii.cubic (Degree 3 curve) => its a cubic curve (more flexible, smoother), Needs at least 4 known points

In [405]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,np.nan,30,40,50], index=[2,1,5,4,3],name='Sample')
s.to_frame()

   Sample
2    10.0
1     NaN
5    30.0
4    40.0
3    50.0

In [407]:
s.interpolate(method='slinear')

2    10.0
1     NaN
5    30.0
4    40.0
3    50.0
Name: Sample, dtype: float64

In [408]:
s.interpolate(method='quadratic')

2    10.0
1     NaN
5    30.0
4    40.0
3    50.0
Name: Sample, dtype: float64

In [409]:
s.interpolate(method='cubic')

2    10.0
1     NaN
5    30.0
4    40.0
3    50.0
Name: Sample, dtype: float64

In [447]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,np.nan,30,40,50], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1    10.0
2     NaN
3    30.0
4    40.0
5    50.0

In [448]:
s.interpolate(method='slinear')

1    10.0
2    20.0
3    30.0
4    40.0
5    50.0
Name: Sample, dtype: float64

In [427]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,np.nan,30,50,60], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1    10.0
2     NaN
3    30.0
4    50.0
5    60.0

In [428]:
s.interpolate(method='quadratic')

1    10.000000
2    15.789474
3    30.000000
4    50.000000
5    60.000000
Name: Sample, dtype: float64

In [429]:
s.interpolate(method='cubic')

1    10.0
2    12.5
3    30.0
4    50.0
5    60.0
Name: Sample, dtype: float64

##### 7. pad / ffill = Same as forward fill

In [434]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,np.nan,30,np.nan,60], index=[1,28,3,4,5],name='Sample')
s.to_frame()

    Sample
1     10.0
28     NaN
3     30.0
4      NaN
5     60.0

In [436]:
s.interpolate(method='pad')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\3001578042.py:1: FutureWarning: Series.interpolate with method=pad is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.interpolate(method='pad')

1     10.0
28    10.0
3     30.0
4     30.0
5     60.0
Name: Sample, dtype: float64

In [437]:
s.interpolate(method='ffill')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\3889917914.py:1: FutureWarning: Series.interpolate with method=ffill is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.interpolate(method='ffill')

1     10.0
28    10.0
3     30.0
4     30.0
5     60.0
Name: Sample, dtype: float64

##### 8. backfill / bfill=same as backword

In [438]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,np.nan,30,np.nan,60], index=[1,28,3,4,5],name='Sample')
s.to_frame()

    Sample
1     10.0
28     NaN
3     30.0
4      NaN
5     60.0

In [439]:
s.interpolate(method='bfill')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\1227612236.py:1: FutureWarning: Series.interpolate with method=bfill is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.interpolate(method='bfill')

1     10.0
28    30.0
3     30.0
4     60.0
5     60.0
Name: Sample, dtype: float64

In [352]:
s.interpolate(method='backfill')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\1569670219.py:1: FutureWarning: Series.interpolate with method=backfill is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  s.interpolate(method='backfill')

3    14.0
7    28.0
1    28.0
9    34.0
2    34.0
Name: Sample, dtype: float64

##### 9. time (for time index)=Works with datetime index
##### Uses TIME (datetime index) to interpolate missing values. It considers actual time gaps, not just position

In [443]:
import pandas as pd
import numpy as np
dates = pd.to_datetime(['2024-01-01', '2024-01-02', '2024-01-05'])
s = pd.Series([10, np.nan, 40], index=dates)
s.to_frame()

               0
2024-01-01  10.0
2024-01-02   NaN
2024-01-05  40.0

In [444]:
s.interpolate(method='time')

2024-01-01    10.0
2024-01-02    17.5
2024-01-05    40.0
dtype: float64

##### It is not works with String Characters

In [445]:
import pandas as pd
import numpy as np
s=pd.Series(data=['A',np.nan,'C',np.nan,'E'], index=[1,28,3,4,5],name='Sample')
s.to_frame()

   Sample
1       A
28    NaN
3       C
4     NaN
5       E

In [446]:
s.interpolate(method='linear')

C:\Users\User\AppData\Local\Temp\ipykernel_17204\788507699.py:1: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  s.interpolate(method='linear')

1       A
28    NaN
3       C
4     NaN
5       E
Name: Sample, dtype: object

In [455]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,np.nan,np.nan,np.nan,60], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1    10.0
2     NaN
3     NaN
4     NaN
5    60.0

##### **Limit** It is used to fill the NaN values by the given limit only If we mention 2 meand only 2 NaN values are filled
##### Example : we have values [10,NaN,NaN,NaN,60] => 10+60=70,70/2=35, 35 is placed Eaxctly between 10 and 60, 10,NaN,35 10+35=45,45/2=22.5,2nd NaN values placed as 22.5

In [456]:
s.interpolate(limit=2)

1    10.0
2    22.5
3    35.0
4     NaN
5    60.0
Name: Sample, dtype: float64

##### 35+60=95,95/2=47.5

In [457]:
s.interpolate(limit=3)

1    10.0
2    22.5
3    35.0
4    47.5
5    60.0
Name: Sample, dtype: float64

In [462]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,np.nan,np.nan,np.nan,60], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1    10.0
2     NaN
3     NaN
4     NaN
5    60.0

In [463]:
s.interpolate(inplace=False)

1    10.0
2    22.5
3    35.0
4    47.5
5    60.0
Name: Sample, dtype: float64

In [466]:
import pandas as pd
import numpy as np
s=pd.Series(data=[10,np.nan,np.nan,np.nan,60], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1    10.0
2     NaN
3     NaN
4     NaN
5    60.0

In [469]:
s.interpolate(inplace=True)

In [470]:
s.to_frame()

   Sample
1    10.0
2    22.5
3    35.0
4    47.5
5    60.0

In [487]:
import pandas as pd
import numpy as np
s=pd.Series(data=[np.nan,20,70,60,np.nan], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1     NaN
2    20.0
3    70.0
4    60.0
5     NaN

##### The NaN value is filled by downward direction

In [488]:
s.interpolate(limit_direction='forward')

1     NaN
2    20.0
3    70.0
4    60.0
5    60.0
Name: Sample, dtype: float64

##### The NaN value is filled by upward direction

In [489]:
s.interpolate(limit_direction='backward')

1    20.0
2    20.0
3    70.0
4    60.0
5     NaN
Name: Sample, dtype: float64

##### The NaN value is filled by both upward and downward direction

In [484]:
s.interpolate(limit_direction='both')

1    20.0
2    20.0
3    70.0
4    60.0
5    60.0
Name: Sample, dtype: float64

##### **11. Reshaping and Index Operation**
##### 11.1 var_name.rename()
##### 11.2 var_name.rename_axis()
##### 11.3 var_name.reset_index()
##### 11.4 var_name.set_axis()
##### 11.5 var_name.reindex()
##### 11.6 var_name.take()
##### 11.7 var_name.drop()

##### **11.1 var_name.rename()**
##### In series rename is used to rename the index not to rename the column and values.
##### **Syntax : var_name.rename(index=None, axis=None, copy=True, inplace=False, level=None)**
##### **Parameters**
##### index-Dict / function to rename index labels
##### inplace-True → modify original
##### level-used for MultiIndex series not for single normal series.
##### We can rename the sereis using three ways:
##### 1. Rename the index in series.
##### 2.Rename using function.
##### 3.Rename the series name.

##### 1. Rename the index in series.

In [15]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

In [16]:
s.rename(index={1:'001',2:'002',3:'003',4:'004',5:'005'})

001    82
002    20
003    70
004    60
005    28
Name: Sample, dtype: int64

In [17]:
s.rename(index={1:'001',2:'002',3:'003',4:'004',5:'005'},axis=0)

001    82
002    20
003    70
004    60
005    28
Name: Sample, dtype: int64

##### Even though Number of elements in the Series not equals to the number of indexes.Then it will considered by default the same indexes only.
##### **Note :** No matter how much elements are their that many elements need to be complete. If we want to rename the only one index also we can.

In [18]:
s.rename(index={1:'001',2:'002',3:'003'},axis=0)

001    82
002    20
003    70
4      60
5      28
Name: Sample, dtype: int64

##### If copy=True It will not directly modify the original data ,Where it will create a copy of the original data.

In [18]:
s1=s.rename(index={1:'001',2:'002',3:'003',4:'004',5:'005'},copy=True)

In [19]:
s1.to_frame()

     Sample
001      82
002      20
003      70
004      60
005      28

In [20]:
s1[1]=200
s1.to_frame()

C:\Users\User\AppData\Local\Temp\ipykernel_17724\3751358418.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s1[1]=200

     Sample
001      82
002     200
003      70
004      60
005      28

In [21]:
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

##### If copy=False It will directly modify the original data ,Where it will not create a copy of the original data.

In [22]:
s2=s.rename(index={1:'001',2:'002',3:'003',4:'004',5:'005'},copy=False)

In [23]:
s2.to_frame()

     Sample
001      82
002      20
003      70
004      60
005      28

In [24]:
s2[1]=200
s2.to_frame()

C:\Users\User\AppData\Local\Temp\ipykernel_17724\2378774351.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s2[1]=200

     Sample
001      82
002     200
003      70
004      60
005      28

In [25]:
s.to_frame()

   Sample
1      82
2     200
3      70
4      60
5      28

In [46]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

##### If we rename the serires without inplace=True, It will not modify the name of that series untill or unless its True.

In [47]:
s.rename(index={1:'001',2:'002',3:'003',4:'004',5:'005'},inplace=False)

001    82
002    20
003    70
004    60
005    28
Name: Sample, dtype: int64

In [48]:
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

##### If we rename the serires with inplace=True, It will modify the name of that series.

In [49]:
s.rename(index={1:'001',2:'002',3:'003',4:'004',5:'005'},inplace=True)

In [50]:
s.to_frame()

     Sample
001      82
002      20
003      70
004      60
005      28

##### 2.Rename using function.

In [35]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=['A','B','C','D','E'],name='Sample')
s.to_frame()

   Sample
A      82
B      20
C      70
D      60
E      28

##### If we rename the serires without inplace=True, It will not modify the name of that series untill or unless its True.

In [36]:
s.rename(index=str.lower)

a    82
b    20
c    70
d    60
e    28
Name: Sample, dtype: int64

In [42]:
s.to_frame()

   New_Samples
A           82
B           20
C           70
D           60
E           28

##### If we rename the serires with inplace=True, It will modify the name of that series.

In [43]:
s.rename(index=str.lower,inplace=True)

In [44]:
s.to_frame()

   New_Samples
a           82
b           20
c           70
d           60
e           28

##### 3.Rename the series name.

In [37]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=['A','B','C','D','E'],name='Sample')
s.to_frame()

   Sample
A      82
B      20
C      70
D      60
E      28

##### If we rename the serires without inplace=True, It will not modify the name of that series untill or unless its True.

In [38]:
s.rename(index='New_Samples')

A    82
B    20
C    70
D    60
E    28
Name: New_Samples, dtype: int64

In [39]:
s.to_frame()

   Sample
A      82
B      20
C      70
D      60
E      28

##### If we rename the serires with inplace=True, It will modify the name of that series.

In [40]:
s.rename(index='New_Samples',inplace=True)

A    82
B    20
C    70
D    60
E    28
Name: New_Samples, dtype: int64

In [41]:
s.to_frame()

   New_Samples
A           82
B           20
C           70
D           60
E           28

##### **11.2 var_name.rename_axis()**
##### Rename the index name (label of index)
##### **Syntax : var_name.rename_axis(mapper=None, inplace=False)**

In [5]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

In [4]:
s.rename_axis("ID")

ID
1    82
2    20
3    70
4    60
5    28
Name: Sample, dtype: int64

In [6]:
s.rename_axis("ID",inplace=False)

ID
1    82
2    20
3    70
4    60
5    28
Name: Sample, dtype: int64

In [7]:
s.rename_axis("ID",inplace=True)

In [8]:
s.to_frame()

    Sample
ID
1       82
2       20
3       70
4       60
5       28

##### **11.3 var_name.reset_index()**
##### Moves the index into a column and creates a new default index (0,1,2,...).
##### **Syntax : var_name.reset_index(level=None, drop=False, name=None, inplace=False)**
##### **Parameters**
##### drop-True → remove index, False → keep
##### name-Column name for Series values
##### inplace-Modify original

In [2]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

In [3]:
s.reset_index()

   index  Sample
0      1      82
1      2      20
2      3      70
3      4      60
4      5      28

##### Default → reset ALL index levels.

In [4]:
s.reset_index(level=0)

   index  Sample
0      1      82
1      2      20
2      3      70
3      4      60
4      5      28

##### Keep index as column

In [5]:
s.reset_index(drop=False)

   index  Sample
0      1      82
1      2      20
2      3      70
3      4      60
4      5      28

##### If drop=True the specified given index is dropped. Remove index completely (no column).

In [6]:
s.reset_index(drop=True)

0    82
1    20
2    70
3    60
4    28
Name: Sample, dtype: int64

##### Name of the value column (after reset)

In [7]:
s.reset_index(name="Score")

   index  Score
0      1     82
1      2     20
2      3     70
3      4     60
4      5     28

In [8]:
s.reset_index(name="Score",inplace=False)

   index  Score
0      1     82
1      2     20
2      3     70
3      4     60
4      5     28

##### Modifies original Series, Returns None, will give an error , Why? Cannot use 'name' with inplace=True. Because: name is used when returning a new DataFrame , inplace=True means no object is returned
##### What happens internally->inplace=True → modifies original → returns None  , name="Score" → tries to rename output column

In [9]:
s.reset_index(name="Score",inplace=True)

TypeError: Cannot reset_index inplace on a Series to create a DataFrame

##### **11.4 var_name.set_axis()**
##### Replaces the entire axis (index or columns) with new labels. It does NOT modify partially — it replaces everything
##### **Syntax : var_name.set_axis(labels, axis=0, inplace=False)**
##### **Parameters**
##### labels-New index labels
##### inplace-Modify original dataframe , not series.(no need of inplcae in series , instead reassign the same variable)

In [11]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

##### We need to replace entire index with some other indexes.

In [13]:
s.set_axis(labels=['a','b','c','d','e'])

a    82
b    20
c    70
d    60
e    28
Name: Sample, dtype: int64

##### Number of elements in the Series must and should be equals to the number of indexes.

In [14]:
s.set_axis(labels=['a','b','c'])

ValueError: Length mismatch: Expected axis has 5 elements, new values have 3 elements

In [19]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

In [20]:
s.set_axis(labels=['a','b','c','d','e'],axis=0)

a    82
b    20
c    70
d    60
e    28
Name: Sample, dtype: int64

In [22]:
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

##### For Series, set_axis() returns a new Series and does not support inplace=True; reassignment is required.”

In [21]:
s.set_axis(labels=['a','b','c','d','e'],inplace=False)

TypeError: Series.set_axis() got an unexpected keyword argument 'inplace'

##### If we want to change the original series we need to reassign the variable.

In [23]:
s=s.set_axis(labels=['a','b','c','d','e'])

In [24]:
s.to_frame()

   Sample
a      82
b      20
c      70
d      60
e      28

##### **11.5 var_name.reindex()**
##### reindex() matches labels, NOT positions 'a' in [1,2,3,4,5] not found , 'b' in [1,2,3,4,5] not found , No matching labels → all values = NaN
##### **Syntax : var_name.reindex(index=None, method=None, copy=True, fill_value=None, limit=None)**
##### **Parameters**
##### index-New index
##### method-'ffill' / 'bfill'.How to fill missing values when new labels are introduced
##### fill_value-Fill missing values
##### limit-Max fill

In [28]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[1,2,3,4,5],name='Sample')
s.to_frame()

   Sample
1      82
2      20
3      70
4      60
5      28

##### It matches the index and returns the value.

In [31]:
s.reindex(index=[1,2])

1    82
2    20
Name: Sample, dtype: int64

In [33]:
s.reindex(index=[1,'b','c',4,5])

1    82.0
b     NaN
c     NaN
4    60.0
5    28.0
Name: Sample, dtype: float64

In [36]:
s.reindex(index=[1,8,9,4,5])

1    82.0
8     NaN
9     NaN
4    60.0
5    28.0
Name: Sample, dtype: float64

##### If the indexes are not found then it will returns the NaN value, to replace NaN values we need to use method called ffill or bfill (forward fill or backwardfill).

In [39]:
s.reindex(index=[1,8,9,4,5],method='ffill')

1    82
8    28
9    28
4    60
5    28
Name: Sample, dtype: int64

##### “method='bfill' in reindex() requires a sorted index because it relies on positional ordering to fill missing values.” reindex(method='bfill') works ONLY using ORIGINAL index order, NOT the order you pass in reindex list

In [47]:
s.reindex(index=[1,4,5,8,9],method='bfill')

1    82.0
4    60.0
5    28.0
8     NaN
9     NaN
Name: Sample, dtype: float64

In [61]:
s.reindex(index=[1,8,4,5,9],method='nearest')

1    82
8    28
4    60
5    28
9    28
Name: Sample, dtype: int64

In [34]:
s.reindex(index=[1,'b','c',4,5],method='ffill')

TypeError: '<' not supported between instances of 'int' and 'str'

##### Copy=True It will not modifies the original Series Data.

In [48]:
s.reindex(index=[1,4,5,8,9],copy=True)

1    82.0
4    60.0
5    28.0
8     NaN
9     NaN
Name: Sample, dtype: float64

##### If we gives other index number which are not present, and that NaN values want to fill by other value means we can fill NaN value using fill_value attribute.

In [49]:
s.reindex(index=[1,4,5,8,9],fill_value=10)

1    82
4    60
5    28
8    10
9    10
Name: Sample, dtype: int64

##### limit is used to tell how many NaN value we can fill

##### **NOTE :** limit works ONLY with: ✔ ffill (pad) ✔ bfill (backfill) ✔ nearest : These are methods that actually fill values

##### **11.6 var_name.take()**
##### Selects elements by POSITION (integer index), NOT by label. Think: take → position-based selection
##### **Syntax : var_name.take(indices, axis=0)**
##### **Parameters**
##### indices-List of positions
##### axis-Always 0

In [70]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample')
s.to_frame()

   Sample
5      82
3      20
7      70
8      60
1      28

##### Selects elements by POSITION (integer index), NOT by label. Think: take → position-based selection

In [71]:
s.take(indices=[1,2])

3    20
7    70
Name: Sample, dtype: int64

In [73]:
s.take(indices=[4])

1    28
Name: Sample, dtype: int64

In [74]:
s.take(indices=[4,3,1],axis=0)

1    28
8    60
3    20
Name: Sample, dtype: int64

##### **11.7 var_name.drop()**
##### Drop is used to delete the row
##### **Syntax : var_name.drop(labels=None, axis=0, inplace=False, errors='raise')**
##### **Parameters**
##### labels-Index labels to remove
##### inplace-Modify original
##### errors-'raise' / 'ignore'

In [76]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample')
s.to_frame()

   Sample
5      82
3      20
7      70
8      60
1      28

In [79]:
s.drop(labels=[3])

5    82
7    70
8    60
1    28
Name: Sample, dtype: int64

In [80]:
s.drop(labels=[3],inplace=True)

In [81]:
s.to_frame()

   Sample
5      82
7      70
8      60
1      28

##### s.drop(labels=[5])-default, s.drop(labels=[5], errors='raise') - explicit

In [88]:
s.drop(labels=[7],errors='raise')

5    82
8    60
1    28
Name: Sample, dtype: int64

In [85]:
s.drop(labels=[9])

KeyError: '[9] not found in axis'

In [86]:
s.drop(labels=[9],errors='raise')

KeyError: '[9] not found in axis'

##### **12. Advance methods**
##### 12.1 var_name.clip()
##### 12.2 var_name.equals()
##### 12.3 var_name.shift()
##### 12.4 var_name.diff()
##### 12.5 var_name.pct_change()

##### **12.1 var_name.clip()**
##### Limits values within a range, clip → cut values outside boundary
##### **Syntax : var_name.clip(lower=None, upper=None, axis=None, inplace=False)**
##### **Parameters**
##### lower-scalar	Minimum limit
##### upper-scalar	Maximum limit
##### inplace-True / False	Modify original

In [89]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample')
s.to_frame()

   Sample
5      82
3      20
7      70
8      60
1      28

##### It will used to set the range between lower and upper, other than the range value it will not consider, and all values are filled with that range values only.

In [91]:
s.clip(lower=20,upper=70)

5    70
3    20
7    70
8    60
1    28
Name: Sample, dtype: int64

In [93]:
s.clip(lower=2,upper=30)

5    30
3    20
7    30
8    30
1    28
Name: Sample, dtype: int64

##### If given limits is not present in the series by default upper limit is used to fill all the values

In [92]:
s.clip(lower=2,upper=7)

5    7
3    7
7    7
8    7
1    7
Name: Sample, dtype: int64

In [94]:
s.clip(lower=2,upper=7,inplace=False)

5    7
3    7
7    7
8    7
1    7
Name: Sample, dtype: int64

In [95]:
s.to_frame()

   Sample
5      82
3      20
7      70
8      60
1      28

In [96]:
s.clip(lower=2,upper=7,inplace=True)

In [97]:
s.to_frame()

   Sample
5       7
3       7
7       7
8       7
1       7

##### **12.2 var_name.equals()**
##### Returns True if both Series are exactly equal (values + index)
##### **Syntax : var_name.equals(other)**

In [99]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample')
s2=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample')
s1.equals(s2)

True

In [100]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample1')
s2=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample2')
s1.equals(s2)

True

In [101]:
import pandas as pd
import numpy as np
s1=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample1')
s2=pd.Series(data=[82,20,70,60,28], index=[1,3,5,7,8],name='Sample2')
s1.equals(s2)

False

##### **12.3 var_name.shift()**
##### Moves (shifts) data up or down without changing the index, Think: shift → move values, keep index same
##### **Syntax : var_name.shift(periods=1, freq=None, axis=0, fill_value=None)**
##### **Parameters**
##### periods-+ve / -ve	Shift direction
##### fill_value-scalar->Fill empty values

In [104]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample')
s.to_frame()

   Sample
5      82
3      20
7      70
8      60
1      28

##### It will shift the NaN value by given shifts, if it is positive = shift from top, Negative=shift from negative.

In [105]:
s.shift(periods=2)

5     NaN
3     NaN
7    82.0
8    20.0
1    70.0
Name: Sample, dtype: float64

In [106]:
s.shift(periods=-2)

5    70.0
3    60.0
7    28.0
8     NaN
1     NaN
Name: Sample, dtype: float64

##### If NaN fill the value

In [108]:
s.shift(periods=2,fill_value=100)

5    100
3    100
7     82
8     20
1     70
Name: Sample, dtype: int64

In [107]:
s.shift(periods=-2,fill_value=100)

5     70
3     60
7     28
8    100
1    100
Name: Sample, dtype: int64

##### **12.4 var_name.diff()**
##### Difference between current and previous value
##### **Syntax : var_name.diff(periods=1)**
##### By defualt always periods=1

In [110]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample')
s.to_frame()

   Sample
5      82
3      20
7      70
8      60
1      28

##### The first value will always be NaN(hen periods=1) because no privious value before the first value in series.

In [111]:
s.diff(periods=1)

5     NaN
3   -62.0
7    50.0
8   -10.0
1   -32.0
Name: Sample, dtype: float64

In [115]:
s.diff(periods=2)

5     NaN
3     NaN
7   -12.0
8    40.0
1   -42.0
Name: Sample, dtype: float64

In [117]:
s.diff(periods=2,fill_value=100)

TypeError: Series.diff() got an unexpected keyword argument 'fill_value'

##### **12.5 var_name.pct_change()**
##### Calculates percentage change between current and previous value
##### **Formula :** pct_change → (current - previous) / previous
##### **Syntax : var_name.pct_change(periods=1, fill_value=None,fill_method='pad', limit=None)**
##### **Parameters**
##### periods-Number of shifts
##### fill_method-'pad' (ffill)
##### limit-Max fill
##### By defualt always periods=1

In [129]:
import pandas as pd
import numpy as np
s=pd.Series(data=[82,20,70,60,28], index=[5,3,7,8,1],name='Sample')
s.to_frame()

   Sample
5      82
3      20
7      70
8      60
1      28

In [113]:
s.pct_change(periods=1)

5         NaN
3   -0.756098
7    2.500000
8   -0.142857
1   -0.533333
Name: Sample, dtype: float64

In [114]:
s.pct_change(periods=2)

5         NaN
3         NaN
7   -0.146341
8    2.000000
1   -0.600000
Name: Sample, dtype: float64

In [116]:
s.pct_change(periods=1,fill_value=100)

5   -0.180000
3   -0.756098
7    2.500000
8   -0.142857
1   -0.533333
Name: Sample, dtype: float64

In [123]:
s.pct_change(periods=3,fill_method='ffill')

C:\Users\User\AppData\Local\Temp\ipykernel_16592\1716550316.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  s.pct_change(periods=3,fill_method='ffill')

5         NaN
3         NaN
7         NaN
8   -0.268293
1    0.400000
Name: Sample, dtype: float64

In [127]:
s.pct_change(periods=3,fill_value=100)

5   -0.180000
3   -0.800000
7   -0.300000
8   -0.268293
1    0.400000
Name: Sample, dtype: float64

In [128]:
s.pct_change(periods=3,fill_value=100,fill_method='ffill')

C:\Users\User\AppData\Local\Temp\ipykernel_16592\121574827.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  s.pct_change(periods=3,fill_value=100,fill_method='ffill')

5   -0.180000
3   -0.800000
7   -0.300000
8   -0.268293
1    0.400000
Name: Sample, dtype: float64

In [126]:
s.pct_change(periods=3,fill_value=100,fill_method='bfill')

C:\Users\User\AppData\Local\Temp\ipykernel_16592\2709300987.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  s.pct_change(periods=3,fill_value=100,fill_method='bfill')

5   -0.180000
3   -0.800000
7   -0.300000
8   -0.268293
1    0.400000
Name: Sample, dtype: float64

##### **13. String Methods (for text data)**
##### 13.1 s.str.lower()
##### 13.2 s.str.upper()
##### 13.3 s.str.strip()
##### 13.4 s.str.replace()
##### 13.5 s.str.contains()
##### 13.6 s.str.split()

In [144]:
import pandas as pd
import numpy as np
s = pd.Series(['Hello','Good','Fine','Better','Class'],index=np.arange(5),name='Sample')
s.to_frame()

   Sample
0   Hello
1    Good
2    Fine
3  Better
4   Class

In [145]:
s.str.lower()

0     hello
1      good
2      fine
3    better
4     class
Name: Sample, dtype: object

In [146]:
s.str.upper()

0     HELLO
1      GOOD
2      FINE
3    BETTER
4     CLASS
Name: Sample, dtype: object

In [147]:
s.str.strip()

0     Hello
1      Good
2      Fine
3    Better
4     Class
Name: Sample, dtype: object

In [148]:
s.str.replace('Hello','Banglore')

0    Banglore
1        Good
2        Fine
3      Better
4       Class
Name: Sample, dtype: object

In [149]:
s.str.contains('Good')

0    False
1     True
2    False
3    False
4    False
Name: Sample, dtype: bool

In [151]:
import pandas as pd
import numpy as np
s = pd.Series(['Hello','Good','Flower','Bottle','Classmoll'],index=np.arange(5),name='Sample')
s.to_frame()

      Sample
0      Hello
1       Good
2     Flower
3     Bottle
4  Classmoll

In [152]:
s.str.split('o')

0        [Hell, ]
1        [G, , d]
2       [Fl, wer]
3       [B, ttle]
4    [Classm, ll]
Name: Sample, dtype: object

##### **14. Datetime Methods**
##### 14.1 s.dt.year
##### 14.2 s.dt.month
##### 14.3 s.dt.day
##### 14.4 s.dt.strftime()

In [159]:
import pandas as pd
import numpy as np
s=pd.Series(pd.date_range('2026-01-01', periods=5),index=np.arange(5),name='SampleDates')
s.to_frame()

  SampleDates
0  2026-01-01
1  2026-01-02
2  2026-01-03
3  2026-01-04
4  2026-01-05

In [160]:
s.dt.year

0    2026
1    2026
2    2026
3    2026
4    2026
Name: SampleDates, dtype: int32

In [161]:
s.dt.month

0    1
1    1
2    1
3    1
4    1
Name: SampleDates, dtype: int32

In [162]:
s.dt.day

0    1
1    2
2    3
3    4
4    5
Name: SampleDates, dtype: int32

In [164]:
s.dt.strftime('%d-%m-%Y')

0    01-01-2026
1    02-01-2026
2    03-01-2026
3    04-01-2026
4    05-01-2026
Name: SampleDates, dtype: object