# **Pandas Library**
### **Accessing And Modifying Pandas DataFrame()**

#### **1.ACCESING DATA IN DATAFRAME:**
##### 1.1 Column Access
##### 1.2 Row Access : 
##### --> 1.2.1 Using loc (Label-based) 
##### --> 1.2.2 Using iloc (Position-based)
##### 1.3 Fast Access (Single Value)
##### 1.4 Conditional Filtering
##### 1.5 Boolean Methods
##### 1.6 Query (Advanced)
##### 1.7 Take (Position based)
##### 1.8 Sample Data

##### **1.1 Column Access :**
##### It is used to access one or more columns.
##### Syntax For single column (Series) - **df['col']**
##### Syntax For multiple columns (DataFrame) - **df[['col1','col2']]**

In [22]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### I need to access the Names column only (like series)
##### **To get single Column we uses df[column_name]**

In [23]:
df['Names']

1    Aftab
2    Smith
3    Scott
4      Bob
5     Jhon
Name: Names, dtype: object

##### I need to access the Multiple columns such as Names and Student_ID column only (like Pandas)
##### **To get Multiple Columns we uses df[['column_name1','column_name2']]**

In [26]:
df[['Names','Student_ID']]

   Names  Student_ID
1  Aftab         101
2  Smith         102
3  Scott         103
4    Bob         104
5   Jhon         105

##### **To Change the order of columns we uses df[['column_name3','column_name1','column_name2']]**

In [40]:
df[['Names','Marks2','Student_ID']]

   Names  Marks2  Student_ID
1  Aftab      50         101
2  Smith      55         102
3  Scott      60         103
4    Bob      65         104
5   Jhon      70         105

#### **1.2 Row Access :**

##### **1.2.1 Using loc (Label-based) :**
##### Uses index labels to get the rows
##### **Genral syntax :** df.loc[row_label]
##### **Slicing Syntax :** df.loc[start_row:end_row]                      
##### **Special Value Syntax :** df.loc[Row_index, 'col_name']           
##### **Accessing multiple Rows :** df.loc[row_index_start:row_index_end, ['col_name1','col_name2']]

In [27]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### If you want to get the particular row we need to use loc[] Where it works based on index label
##### **To get single row we uses df.loc[row_label]**
##### **Genral syntax :** df.loc[row_label]

In [30]:
df.loc[1]

Student_ID      101
Names         Aftab
Marks1           70
Marks2           50
Marks3           40
Marks4           75
Marks5           65
Marks6           70
Name: 1, dtype: object

##### If you want multiple rows we need to use nested list [[]] and separated each row label by comma.

##### **To get Multiple row we uses df.loc[['row_label1','row_label2','row_label3']]**

In [35]:
df.loc[[1,3,5]]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
3         103  Scott      80      60      50      85      75      80
5         105   Jhon      90      70      60      95      85      90

In [41]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### **Slicing Syntax :** df.loc[start_row_index:end_row_index]

In [43]:
df.loc[1:5]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### **Slicing Syntax :** df.loc[start_row_index:end_row_index:step_index]

In [44]:
df.loc[1:5:2]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
3         103  Scott      80      60      50      85      75      80
5         105   Jhon      90      70      60      95      85      90

##### **Special Value Syntax** : df.loc[Row_index, 'col_name']

In [46]:
df.loc[1,'Names']

'Aftab'

In [47]:
df.loc[[1,2],'Names']

1    Aftab
2    Smith
Name: Names, dtype: object

In [48]:
df.loc[[1,2],['Names','Student_ID']]

   Names  Student_ID
1  Aftab         101
2  Smith         102

##### **Accessing multiple Rows :** df.loc[row_index_start:row_index_end, ['col_name1','col_name2']]

In [49]:
df.loc[0:2,['Names']]

   Names
1  Aftab
2  Smith

In [50]:
df.loc[0:2,['Names','Marks1']]

   Names  Marks1
1  Aftab      70
2  Smith      75

In [51]:
df.loc[0:5:2,['Names','Marks1']]

   Names  Marks1
1  Aftab      70
3  Scott      80
5   Jhon      90

##### **1.2.2 Using iloc (Position-based) :**
##### Uses integer positions
##### **Genral Syntax :** df.iloc[row_index] 
##### **Slicing Syntax :** df.iloc[row_index_start:row_index_end]
##### **Slicing Syntax :** df.iloc[row_index_start:row_index_end:step_index]
##### **Multiple rows access :** df.iloc[row_index, col_index]
##### **Slicing with multiple rows :** df.iloc[row_index_start:row_index_end, col_index_start:col_index_end]

In [37]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### If you want to get the particular row we need to use iloc[] Where it works based on index(no matter what index label you given)
##### **Genral Syntax :** df.iloc[row_index]

In [38]:
df.iloc[0]

Student_ID      101
Names         Aftab
Marks1           70
Marks2           50
Marks3           40
Marks4           75
Marks5           65
Marks6           70
Name: 1, dtype: object

##### If you want multiple rows we need to use nested list [[]] and separated each row label by comma.

In [39]:
df.iloc[[0,2,4]]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
3         103  Scott      80      60      50      85      75      80
5         105   Jhon      90      70      60      95      85      90

##### **Slicing Syntax :** df.iloc[row_index_start:row_index_end]

In [54]:
df.iloc[0:5]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### **Slicing Syntax :** df.iloc[row_index_start:row_index_end:step_index]

In [55]:
df.iloc[0:5:2]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
3         103  Scott      80      60      50      85      75      80
5         105   Jhon      90      70      60      95      85      90

##### **Multiple rows access :** df.iloc[row_index, col_index]

In [57]:
df.iloc[0:2,1]

1    Aftab
2    Smith
Name: Names, dtype: object

##### **Slicing with multiple rows :** df.iloc[row_index_start:row_index_end, col_index_start:col_index_end]

In [60]:
df.iloc[0:2,1:8]

   Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1  Aftab      70      50      40      75      65      70
2  Smith      75      55      45      80      70      75

In [61]:
df.iloc[0:2,1:8:2]

   Names  Marks2  Marks4  Marks6
1  Aftab      50      75      70
2  Smith      55      80      75

In [62]:
df.iloc[0:5:2,1:8:2]

   Names  Marks2  Marks4  Marks6
1  Aftab      50      75      70
3  Scott      60      85      80
5   Jhon      70      95      90

##### **1.3 Fast Access (Single Value) :**
##### It is used to access row data Faster than loc/iloc. It is used to access single element data.
##### **General Synatx for at:** df.at[row_label, col]
##### **General Syntax for iat:** df.iat[row_position, col_position]

In [63]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### **General Synatx for at:** df.at[row_label, col]

In [65]:
df.at[1,'Names']

'Aftab'

In [69]:
df.at[4,'Names']

'Bob'

##### **General Syntax for iat:** df.iat[row_position, col_position]

In [75]:
df.iat[1,1]

'Smith'

In [74]:
df.iat[4,1]

'Jhon'

##### **1.4 Conditional Filtering :**
##### It is used to acess the data by condition.
##### **General Syntax :** df[condition]
##### **Example 1 :** df[(df['Age'] > 20) & (df['Salary'] > 3000)]
##### **Example 2 :** df[df['Name'] == 'A']

In [76]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [77]:
df[df['Marks1']>80]

   Student_ID Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
4         104   Bob      85      65      55      90      80      85
5         105  Jhon      90      70      60      95      85      90

In [81]:
df[(df['Marks1']>70) & (df['Marks1']<90)]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85

In [82]:
df[(df['Marks1']>70) | (df['Marks1']<90)]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [83]:
df[~(df['Marks1']<90)]

   Student_ID Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
5         105  Jhon      90      70      60      95      85      90

In [85]:
df[(df['Names']=='Scott')]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
3         103  Scott      80      60      50      85      75      80

In [84]:
df[~(df['Names']=='Scott')]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [86]:
df[(df['Names']=='Aftab') | (df['Marks1']<90)]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85

In [87]:
df[(df['Names']=='Aftab') | (df['Marks1']>80)]

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### **1.5 Query (Advanced) :**
##### It is used to aceess the data by
##### df.query("Age > 25 and Salary > 3000")

In [90]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [91]:
df.query("Marks1>70 and Marks1<90")

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85

In [95]:
df.query("Marks1>70 & Marks1<90")

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85

In [92]:
df.query("Marks1>70 or Marks1<90")

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [96]:
df.query("Marks1>70 | Marks1<90")

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [93]:
df.query("not Marks1>70")

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70

In [94]:
df.query("~(Marks1>70)")

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70

##### **1.6 Take (Position based) :**
##### It is used to access the data by row index position.
##### df.take([row_index])
##### df.take([row_index1,row_index2])

In [97]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [98]:
df.take([1,2])

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80

In [100]:
df.take([2,4,0])

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
3         103  Scott      80      60      50      85      75      80
5         105   Jhon      90      70      60      95      85      90
1         101  Aftab      70      50      40      75      65      70

##### **1.7 Sample Data :**
##### It is used to get the sample data based on n value and each record will get by randomly.
##### **Syntax :** df.sample(n=1)

In [1]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [5]:
df.sample()

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70

In [6]:
df.sample(n=2)

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
4         104    Bob      85      65      55      90      80      85
3         103  Scott      80      60      50      85      75      80

In [7]:
df.sample(n=4)

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
3         103  Scott      80      60      50      85      75      80
5         105   Jhon      90      70      60      95      85      90
4         104    Bob      85      65      55      90      80      85
1         101  Aftab      70      50      40      75      65      70

#### **2. MODIFYING DATAFRAME (WRITING DATA) :**
##### 2.1 Add New Column
##### 2.2 Update Existing Column
##### 2.3 Modify Specific Value
##### 2.4 Conditional Update
##### 2.5 Apply Function
##### 2.6 Map (Column-wise)
##### 2.7 Replace Values
##### 2.8 Rename Columns
##### 2.9 Change Index
##### 2.10 Insert Column
##### 2.11 Drop Column / Row
##### 2.12 Delete Column
##### 2.13 Where and Mask

##### **2.1 Add New Column :**
##### **Syntax :** df['new_col'] = value

In [111]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [112]:
df['State']=['Karnataka','Maharashtra','Kolkatta','Karnataka','Karnataka']

In [113]:
df

,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,State
1,101,Aftab,70,50,40,75,65,70,Karnataka
2,102,Smith,75,55,45,80,70,75,Maharashtra
3,103,Scott,80,60,50,85,75,80,Kolkatta
4,104,Bob,85,65,55,90,80,85,Karnataka
5,105,Jhon,90,70,60,95,85,90,Karnataka

In [114]:
df['Age']=[23,21,24,23,26]

In [115]:
df

,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,State,Age
1,101,Aftab,70,50,40,75,65,70,Karnataka,23
2,102,Smith,75,55,45,80,70,75,Maharashtra,21
3,103,Scott,80,60,50,85,75,80,Kolkatta,24
4,104,Bob,85,65,55,90,80,85,Karnataka,23
5,105,Jhon,90,70,60,95,85,90,Karnataka,26

##### **2.2 Update Existing Column**
##### **Syntax :** df['col_name'] = df['col_name'] + 1any_value

In [8]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [9]:
df['Total Marks']=df['Marks1']+df['Marks2']+df['Marks3']+df['Marks4']+df['Marks5']+df['Marks6']

In [10]:
df

,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,Total Marks
1,101,Aftab,70,50,40,75,65,70,370
2,102,Smith,75,55,45,80,70,75,400
3,103,Scott,80,60,50,85,75,80,430
4,104,Bob,85,65,55,90,80,85,460
5,105,Jhon,90,70,60,95,85,90,490

In [11]:
df['Grace Marks']=df['Marks1']+df['Marks2']+df['Marks3']+df['Marks4']+df['Marks5']+df['Marks6']+10

In [12]:
df

,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,Total Marks,Grace Marks
1,101,Aftab,70,50,40,75,65,70,370,380
2,102,Smith,75,55,45,80,70,75,400,410
3,103,Scott,80,60,50,85,75,80,430,440
4,104,Bob,85,65,55,90,80,85,460,470
5,105,Jhon,90,70,60,95,85,90,490,500

##### **2.3 Modify Specific Value**
##### **Syntax :** df.loc[row_index, 'col_name'] = new_value
##### **Syntax :** df.iloc[row_index1,row_index2] = new_value
##### **Syntax :** df.at[row_index,'col_name'] = new_value
##### **Syntax :** df.iat[row_index1,row_index2] = new_value

In [119]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [122]:
df.loc[1,'Names']='Alice'

In [123]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Alice      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [124]:
df.loc[[1,5],'Names']='Alice','Jolly'

In [125]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Alice      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105  Jolly      90      70      60      95      85      90

In [126]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [129]:
df.iloc[1,2]=60

In [130]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      60      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [132]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [133]:
df.at[1,'Names']='Alice'

In [134]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Alice      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [136]:
df.at[5,'Names']='Jolly'

In [137]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Alice      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105  Jolly      90      70      60      95      85      90

In [138]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [139]:
df.iat[0,1]='Aftab Khan'

In [140]:
df

   Student_ID       Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab Khan      70      50      40      75      65      70
2         102       Smith      75      55      45      80      70      75
3         103       Scott      80      60      50      85      75      80
4         104         Bob      85      65      55      90      80      85
5         105        Jhon      90      70      60      95      85      90

##### **2.4 Conditional Update**
##### **Syntax :** df.loc[condition] = value

In [141]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [144]:
df.loc[df['Marks1']>70,'Salary']=12000

In [145]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6   Salary
1         101  Aftab      70      50      40      75      65      70      NaN
2         102  Smith      75      55      45      80      70      75  12000.0
3         103  Scott      80      60      50      85      75      80  12000.0
4         104    Bob      85      65      55      90      80      85  12000.0
5         105   Jhon      90      70      60      95      85      90  12000.0

##### **2.5 Apply Function**
##### **Syntax :** df['col_name'] = df['col_name'].apply(function) - functions-lambda

In [147]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [148]:
df['Salary']=df['Marks1'].apply(lambda x : x*1200)

In [149]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Salary
1         101  Aftab      70      50      40      75      65      70   84000
2         102  Smith      75      55      45      80      70      75   90000
3         103  Scott      80      60      50      85      75      80   96000
4         104    Bob      85      65      55      90      80      85  102000
5         105   Jhon      90      70      60      95      85      90  108000

##### **2.6 Map (Column-wise)**
##### **Syntax :** df['col_name'] = df['col_name'].map(funct) - function-lambda

In [150]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [151]:
df['Salary']=df['Marks6'].map(lambda x:x*2)

In [152]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Salary
1         101  Aftab      70      50      40      75      65      70     140
2         102  Smith      75      55      45      80      70      75     150
3         103  Scott      80      60      50      85      75      80     160
4         104    Bob      85      65      55      90      80      85     170
5         105   Jhon      90      70      60      95      85      90     180

##### **2.7 Replace Values**
##### **Syntax :** df.replace(old_value(row), new_value)
##### **Syntax :** df.replace({'key_row_label':'value'})

In [153]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [155]:
df.replace(101,1001)

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1        1001  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [157]:
df.replace({101:1001,102:1002,103:1003,104:1004,105:1005})

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1        1001  Aftab      70      50      40      75      65      70
2        1002  Smith      75      55      45      80      70      75
3        1003  Scott      80      60      50      85      75      80
4        1004    Bob      85      65      55      90      80      85
5        1005   Jhon      90      70      60      95      85      90

##### **2.8 Rename Columns**
##### **Syntax :** df.rename(columns={'old_col_name':'new_col_name'}, inplace=True)

In [158]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [159]:
df.rename(columns={'Marks1':'Subject1'})

   Student_ID  Names  Subject1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab        70      50      40      75      65      70
2         102  Smith        75      55      45      80      70      75
3         103  Scott        80      60      50      85      75      80
4         104    Bob        85      65      55      90      80      85
5         105   Jhon        90      70      60      95      85      90

In [160]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [161]:
df.rename(columns={'Marks1':'Subject1'},inplace=True)

In [162]:
df

   Student_ID  Names  Subject1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab        70      50      40      75      65      70
2         102  Smith        75      55      45      80      70      75
3         103  Scott        80      60      50      85      75      80
4         104    Bob        85      65      55      90      80      85
5         105   Jhon        90      70      60      95      85      90

##### **2.9 Change Index**
##### **Syntax :** df.set_index('col')
##### **Syntax :** df.reset_index()

In [17]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [18]:
df.set_index('Names')

       Student_ID  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
Names
Aftab         101      70      50      40      75      65      70
Smith         102      75      55      45      80      70      75
Scott         103      80      60      50      85      75      80
Bob           104      85      65      55      90      80      85
Jhon          105      90      70      60      95      85      90

In [21]:
df.reset_index()

   index  Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
0      1         101  Aftab      70      50      40      75      65      70
1      2         102  Smith      75      55      45      80      70      75
2      3         103  Scott      80      60      50      85      75      80
3      4         104    Bob      85      65      55      90      80      85
4      5         105   Jhon      90      70      60      95      85      90

##### **2.10 Insert Column**
##### **Syntax :** df.insert(col_index, 'new_col', new_value)

In [165]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [166]:
df.insert(1,'Salary',10000)

In [167]:
df

   Student_ID  Salary  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101   10000  Aftab      70      50      40      75      65      70
2         102   10000  Smith      75      55      45      80      70      75
3         103   10000  Scott      80      60      50      85      75      80
4         104   10000    Bob      85      65      55      90      80      85
5         105   10000   Jhon      90      70      60      95      85      90

In [169]:
df.insert(9,'Age',23)

In [170]:
df

,Student_ID,Salary,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,Age
1,101,10000,Aftab,70,50,40,75,65,70,23
2,102,10000,Smith,75,55,45,80,70,75,23
3,103,10000,Scott,80,60,50,85,75,80,23
4,104,10000,Bob,85,65,55,90,80,85,23
5,105,10000,Jhon,90,70,60,95,85,90,23

##### **2.11 Drop Column / Row**
##### **Syntax :** df.drop('col', axis=1)
##### **Syntax :** df.drop(row, axis=0)

In [171]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [173]:
df.drop('Marks6',axis=1)

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5
1         101  Aftab      70      50      40      75      65
2         102  Smith      75      55      45      80      70
3         103  Scott      80      60      50      85      75
4         104    Bob      85      65      55      90      80
5         105   Jhon      90      70      60      95      85

In [176]:
df.drop(5,axis=0)

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85

##### **2.12 Delete Column**
##### **Syntax :** del df['col']
##### **Syntax :** df.pop('col')

In [177]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [178]:
del df['Marks6']

In [179]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5
1         101  Aftab      70      50      40      75      65
2         102  Smith      75      55      45      80      70
3         103  Scott      80      60      50      85      75
4         104    Bob      85      65      55      90      80
5         105   Jhon      90      70      60      95      85

In [180]:
df.pop('Marks5')

1    65
2    70
3    75
4    80
5    85
Name: Marks5, dtype: int64

In [181]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4
1         101  Aftab      70      50      40      75
2         102  Smith      75      55      45      80
3         103  Scott      80      60      50      85
4         104    Bob      85      65      55      90
5         105   Jhon      90      70      60      95

##### **2.13 Where and Mask**
##### **Syntax :** df.where(condition, value)
##### **Syntax :** df.mask(condition, value)

In [187]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [188]:
df.where(df['Marks1']>80,100)

   Student_ID Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         100   100     100     100     100     100     100     100
2         100   100     100     100     100     100     100     100
3         100   100     100     100     100     100     100     100
4         104   Bob      85      65      55      90      80      85
5         105  Jhon      90      70      60      95      85      90

In [189]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [190]:
df.mask(df['Marks1']>80,100)

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         100    100     100     100     100     100     100     100
5         100    100     100     100     100     100     100     100