# **Pandas Library**
### **Conversion Methods in Pandas DataFrame()**

#### **WHAT ARE CONVERSION METHODS?**
##### Methods used to **convert a DataFrame into another format, structure, or data type**
##### 1. STRUCTURE CONVERSIONS (DataFrame → other pandas objects)
##### 2. FILE CONVERSIONS (DataFrame → external formats)
##### 3. TYPE CONVERSIONS (Data types)
##### 4. INDEX / AXIS CONVERSIONS
##### 5. SHAPE / FORMAT CONVERSIONS
##### 6. COPY / DUPLICATION

#### **1. STRUCTURE CONVERSIONS (DataFrame → other pandas objects)**
##### 1. df.to_numpy() : Convert DataFrame → NumPy array
##### 2. df.values(older) : Same as to_numpy()
##### 3. df.squeeze() : Convert DataFrame → Series (if possible)
##### 4. df.to_dict() : Convert DataFrame → dictionary
##### 5. df.to_records() : Convert → structured NumPy array
##### 6. df.to_string() : Convert → string format

#### **2. FILE CONVERSIONS (DataFrame → external formats)**
##### 7. df.to_csv() : df.to_csv(path, index=True), Save as CSV
##### 8. df.to_excel() : df.to_excel(path)
##### 9. df.to_json() : df.to_json(path_or_buf=None, orient=None)
##### 10. df.to_html() : Convert → HTML table
##### 11. df.to_sql() : df.to_sql(name, con), Store in database
##### 12. df.to_markdown() : Convert → markdown table

#### **3. TYPE CONVERSIONS (Data types)**
##### 13. df.astype() : Convert column data types, df.astype(dtype)
##### 14. df.convert_dtypes() : Automatically convert to best dtype
##### 15. pd.to_numeric() : pd.to_numeric(df['col'])
##### 16. pd.to_datetime() : pd.to_datetime(df['date'])

#### **4. INDEX / AXIS CONVERSIONS**
##### 18. df.reset_index() : Convert index → column
##### 19. df.set_index() : Convert column → index
##### 20. df.rename_axis() : Convert axis labels

#### **5. SHAPE / FORMAT CONVERSIONS**
##### 21. df.stack() : Columns → rows
##### 22. df.unstack() : Rows → columns
##### 23. df.melt() : Wide → long format
##### 24. df.pivot() : Long → wide format

#### **6. COPY / DUPLICATION**
##### 26. df.copy() : Create copy

##### **1. STRUCTURE CONVERSIONS (DataFrame → other pandas objects)**

##### **1. df.to_numpy() :** Convert DataFrame → NumPy array
##### **Syntax : df.to_numpy(dtype=None, copy=False)**

In [51]:
import pandas as pd
import numpy as np
df=pd.DataFrame(data={'Student_ID':[101,102,103,104,105],'Names':['Aftab','Smith','Scott','Bob','Jhon'],'Marks1':np.arange(70,95,5),
                      'Marks2':np.arange(50,75,5),'Marks3':np.arange(40,65,5),'Marks4':np.arange(75,100,5),'Marks5':np.arange(65,90,5),
                      'Marks6':np.arange(70,95,5)},index=np.arange(1,6))
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [121]:
df.to_numpy()

array([[101, 'Aftab', 70, 50, 40, 75, 65, 70],
       [102, 'Smith', 75, 55, 45, 80, 70, 75],
       [103, 'Scott', 80, 60, 50, 85, 75, 80],
       [104, 'Bob', 85, 65, 55, 90, 80, 85],
       [105, 'Jhon', 90, 70, 60, 95, 85, 90]], dtype=object)

##### IF we want to change the type of data we can change by using dtype attribute.

In [53]:
df.to_numpy(dtype='int')

ValueError: invalid literal for int() with base 10: 'Aftab'

##### Note : We can't change the string into int, we can change int to str

In [54]:
df.to_numpy(dtype='str')

array([['101', 'Aftab', '70', '50', '40', '75', '65', '70'],
       ['102', 'Smith', '75', '55', '45', '80', '70', '75'],
       ['103', 'Scott', '80', '60', '50', '85', '75', '80'],
       ['104', 'Bob', '85', '65', '55', '90', '80', '85'],
       ['105', 'Jhon', '90', '70', '60', '95', '85', '90']], dtype='<U5')

In [70]:
arr2=df.to_numpy(copy=True)

In [71]:
arr2

array([[101, 'Aftab', 70, 50, 40, 75, 65, 70],
       [102, 'Smith', 75, 55, 45, 80, 70, 75],
       [103, 'Scott', 80, 60, 50, 85, 75, 80],
       [104, 'Bob', 85, 65, 55, 90, 80, 85],
       [105, 'Jhon', 90, 70, 60, 95, 85, 90]], dtype=object)

In [62]:
arr2[0,0]=100

In [63]:
arr2

array([[100, 'Aftab', 70, 50, 40, 75, 65, 70],
       [102, 'Smith', 75, 55, 45, 80, 70, 75],
       [103, 'Scott', 80, 60, 50, 85, 75, 80],
       [104, 'Bob', 85, 65, 55, 90, 80, 85],
       [105, 'Jhon', 90, 70, 60, 95, 85, 90]], dtype=object)

In [64]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### **2. df.values(older) :** Same as to_numpy()

In [74]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [72]:
df.values

array([[101, 'Aftab', 70, 50, 40, 75, 65, 70],
       [102, 'Smith', 75, 55, 45, 80, 70, 75],
       [103, 'Scott', 80, 60, 50, 85, 75, 80],
       [104, 'Bob', 85, 65, 55, 90, 80, 85],
       [105, 'Jhon', 90, 70, 60, 95, 85, 90]], dtype=object)

##### **3. df.squeeze() :** Convert DataFrame → Series (if possible) Intenrally its converting
##### **Syntax : df.squeeze(axis=None)**

In [73]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [75]:
df.squeeze()

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [77]:
df.squeeze(axis=0)

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [78]:
df.squeeze(axis=1)

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

##### **4. df.to_dict() :** Convert DataFrame → dictionary
##### **Syntax : df.to_dict(orient='dict')**
##### **Orient types :** dict, list, series, split, records, index

In [79]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [80]:
df.to_dict()

{'Student_ID': {1: 101, 2: 102, 3: 103, 4: 104, 5: 105},
 'Names': {1: 'Aftab', 2: 'Smith', 3: 'Scott', 4: 'Bob', 5: 'Jhon'},
 'Marks1': {1: 70, 2: 75, 3: 80, 4: 85, 5: 90},
 'Marks2': {1: 50, 2: 55, 3: 60, 4: 65, 5: 70},
 'Marks3': {1: 40, 2: 45, 3: 50, 4: 55, 5: 60},
 'Marks4': {1: 75, 2: 80, 3: 85, 4: 90, 5: 95},
 'Marks5': {1: 65, 2: 70, 3: 75, 4: 80, 5: 85},
 'Marks6': {1: 70, 2: 75, 3: 80, 4: 85, 5: 90}}

In [81]:
df.to_dict(orient='dict')

{'Student_ID': {1: 101, 2: 102, 3: 103, 4: 104, 5: 105},
 'Names': {1: 'Aftab', 2: 'Smith', 3: 'Scott', 4: 'Bob', 5: 'Jhon'},
 'Marks1': {1: 70, 2: 75, 3: 80, 4: 85, 5: 90},
 'Marks2': {1: 50, 2: 55, 3: 60, 4: 65, 5: 70},
 'Marks3': {1: 40, 2: 45, 3: 50, 4: 55, 5: 60},
 'Marks4': {1: 75, 2: 80, 3: 85, 4: 90, 5: 95},
 'Marks5': {1: 65, 2: 70, 3: 75, 4: 80, 5: 85},
 'Marks6': {1: 70, 2: 75, 3: 80, 4: 85, 5: 90}}

In [82]:
df.to_dict(orient='list')

{'Student_ID': [101, 102, 103, 104, 105],
 'Names': ['Aftab', 'Smith', 'Scott', 'Bob', 'Jhon'],
 'Marks1': [70, 75, 80, 85, 90],
 'Marks2': [50, 55, 60, 65, 70],
 'Marks3': [40, 45, 50, 55, 60],
 'Marks4': [75, 80, 85, 90, 95],
 'Marks5': [65, 70, 75, 80, 85],
 'Marks6': [70, 75, 80, 85, 90]}

In [84]:
df.to_dict(orient='series')

{'Student_ID': 1    101
 2    102
 3    103
 4    104
 5    105
 Name: Student_ID, dtype: int64,
 'Names': 1    Aftab
 2    Smith
 3    Scott
 4      Bob
 5     Jhon
 Name: Names, dtype: object,
 'Marks1': 1    70
 2    75
 3    80
 4    85
 5    90
 Name: Marks1, dtype: int64,
 'Marks2': 1    50
 2    55
 3    60
 4    65
 5    70
 Name: Marks2, dtype: int64,
 'Marks3': 1    40
 2    45
 3    50
 4    55
 5    60
 Name: Marks3, dtype: int64,
 'Marks4': 1    75
 2    80
 3    85
 4    90
 5    95
 Name: Marks4, dtype: int64,
 'Marks5': 1    65
 2    70
 3    75
 4    80
 5    85
 Name: Marks5, dtype: int64,
 'Marks6': 1    70
 2    75
 3    80
 4    85
 5    90
 Name: Marks6, dtype: int64}

In [85]:
df.to_dict(orient='records')

[{'Student_ID': 101,
  'Names': 'Aftab',
  'Marks1': 70,
  'Marks2': 50,
  'Marks3': 40,
  'Marks4': 75,
  'Marks5': 65,
  'Marks6': 70},
 {'Student_ID': 102,
  'Names': 'Smith',
  'Marks1': 75,
  'Marks2': 55,
  'Marks3': 45,
  'Marks4': 80,
  'Marks5': 70,
  'Marks6': 75},
 {'Student_ID': 103,
  'Names': 'Scott',
  'Marks1': 80,
  'Marks2': 60,
  'Marks3': 50,
  'Marks4': 85,
  'Marks5': 75,
  'Marks6': 80},
 {'Student_ID': 104,
  'Names': 'Bob',
  'Marks1': 85,
  'Marks2': 65,
  'Marks3': 55,
  'Marks4': 90,
  'Marks5': 80,
  'Marks6': 85},
 {'Student_ID': 105,
  'Names': 'Jhon',
  'Marks1': 90,
  'Marks2': 70,
  'Marks3': 60,
  'Marks4': 95,
  'Marks5': 85,
  'Marks6': 90}]

In [87]:
df.to_dict(orient='index')

{1: {'Student_ID': 101,
  'Names': 'Aftab',
  'Marks1': 70,
  'Marks2': 50,
  'Marks3': 40,
  'Marks4': 75,
  'Marks5': 65,
  'Marks6': 70},
 2: {'Student_ID': 102,
  'Names': 'Smith',
  'Marks1': 75,
  'Marks2': 55,
  'Marks3': 45,
  'Marks4': 80,
  'Marks5': 70,
  'Marks6': 75},
 3: {'Student_ID': 103,
  'Names': 'Scott',
  'Marks1': 80,
  'Marks2': 60,
  'Marks3': 50,
  'Marks4': 85,
  'Marks5': 75,
  'Marks6': 80},
 4: {'Student_ID': 104,
  'Names': 'Bob',
  'Marks1': 85,
  'Marks2': 65,
  'Marks3': 55,
  'Marks4': 90,
  'Marks5': 80,
  'Marks6': 85},
 5: {'Student_ID': 105,
  'Names': 'Jhon',
  'Marks1': 90,
  'Marks2': 70,
  'Marks3': 60,
  'Marks4': 95,
  'Marks5': 85,
  'Marks6': 90}}

In [88]:
df.to_dict(orient='split')

{'index': [1, 2, 3, 4, 5],
 'columns': ['Student_ID',
  'Names',
  'Marks1',
  'Marks2',
  'Marks3',
  'Marks4',
  'Marks5',
  'Marks6'],
 'data': [[101, 'Aftab', 70, 50, 40, 75, 65, 70],
  [102, 'Smith', 75, 55, 45, 80, 70, 75],
  [103, 'Scott', 80, 60, 50, 85, 75, 80],
  [104, 'Bob', 85, 65, 55, 90, 80, 85],
  [105, 'Jhon', 90, 70, 60, 95, 85, 90]]}

##### **5. df.to_records() :** Convert → structured NumPy array(ro records)
##### **Syntax : df.to_records(index=True)**

In [89]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [90]:
df.to_records()

rec.array([(1, 101, 'Aftab', 70, 50, 40, 75, 65, 70),
           (2, 102, 'Smith', 75, 55, 45, 80, 70, 75),
           (3, 103, 'Scott', 80, 60, 50, 85, 75, 80),
           (4, 104, 'Bob', 85, 65, 55, 90, 80, 85),
           (5, 105, 'Jhon', 90, 70, 60, 95, 85, 90)],
          dtype=[('index', '<i8'), ('Student_ID', '<i8'), ('Names', 'O'), ('Marks1', '<i8'), ('Marks2', '<i8'), ('Marks3', '<i8'), ('Marks4', '<i8'), ('Marks5', '<i8'), ('Marks6', '<i8')])

In [91]:
df.to_records(index=True)

rec.array([(1, 101, 'Aftab', 70, 50, 40, 75, 65, 70),
           (2, 102, 'Smith', 75, 55, 45, 80, 70, 75),
           (3, 103, 'Scott', 80, 60, 50, 85, 75, 80),
           (4, 104, 'Bob', 85, 65, 55, 90, 80, 85),
           (5, 105, 'Jhon', 90, 70, 60, 95, 85, 90)],
          dtype=[('index', '<i8'), ('Student_ID', '<i8'), ('Names', 'O'), ('Marks1', '<i8'), ('Marks2', '<i8'), ('Marks3', '<i8'), ('Marks4', '<i8'), ('Marks5', '<i8'), ('Marks6', '<i8')])

In [92]:
df.to_records(index=False)

rec.array([(101, 'Aftab', 70, 50, 40, 75, 65, 70),
           (102, 'Smith', 75, 55, 45, 80, 70, 75),
           (103, 'Scott', 80, 60, 50, 85, 75, 80),
           (104, 'Bob', 85, 65, 55, 90, 80, 85),
           (105, 'Jhon', 90, 70, 60, 95, 85, 90)],
          dtype=[('Student_ID', '<i8'), ('Names', 'O'), ('Marks1', '<i8'), ('Marks2', '<i8'), ('Marks3', '<i8'), ('Marks4', '<i8'), ('Marks5', '<i8'), ('Marks6', '<i8')])

##### **6. df.to_string() :** Convert → string format

In [93]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [94]:
df.to_string()

'   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6\n1         101  Aftab      70      50      40      75      65      70\n2         102  Smith      75      55      45      80      70      75\n3         103  Scott      80      60      50      85      75      80\n4         104    Bob      85      65      55      90      80      85\n5         105   Jhon      90      70      60      95      85      90'

#### **2. FILE CONVERSIONS (DataFrame → external formats)**

##### **7. df.to_csv() :** Save as CSV
##### **Syntax : df.to_csv(path, index=True)**

In [95]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [96]:
df.to_csv()

',Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6\r\n1,101,Aftab,70,50,40,75,65,70\r\n2,102,Smith,75,55,45,80,70,75\r\n3,103,Scott,80,60,50,85,75,80\r\n4,104,Bob,85,65,55,90,80,85\r\n5,105,Jhon,90,70,60,95,85,90\r\n'

##### It saving the data into new CSV Files

In [98]:
df.to_csv('New_Data.csv')

In [99]:
df.to_csv('New_Data1.csv',index=True)

In [100]:
df.to_csv('New_Data2.csv',index=False)

##### **8. df.to_excel() :** Saves data into excel
##### **Syntax : df.to_excel(path)**

In [101]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [107]:
df.to_excel('New_Excel.xlsx')

##### **9. df.to_json() :** Saves data into json file format 
##### **Syntax : df.to_json(path_or_buf=None, orient=None)**

In [108]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [109]:
df.to_json()

'{"Student_ID":{"1":101,"2":102,"3":103,"4":104,"5":105},"Names":{"1":"Aftab","2":"Smith","3":"Scott","4":"Bob","5":"Jhon"},"Marks1":{"1":70,"2":75,"3":80,"4":85,"5":90},"Marks2":{"1":50,"2":55,"3":60,"4":65,"5":70},"Marks3":{"1":40,"2":45,"3":50,"4":55,"5":60},"Marks4":{"1":75,"2":80,"3":85,"4":90,"5":95},"Marks5":{"1":65,"2":70,"3":75,"4":80,"5":85},"Marks6":{"1":70,"2":75,"3":80,"4":85,"5":90}}'

In [110]:
df.to_json('New_JSON.json')

##### **10. df.to_html() :** Convert → HTML table

In [111]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [112]:
df.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Student_ID</th>\n      <th>Names</th>\n      <th>Marks1</th>\n      <th>Marks2</th>\n      <th>Marks3</th>\n      <th>Marks4</th>\n      <th>Marks5</th>\n      <th>Marks6</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>101</td>\n      <td>Aftab</td>\n      <td>70</td>\n      <td>50</td>\n      <td>40</td>\n      <td>75</td>\n      <td>65</td>\n      <td>70</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>102</td>\n      <td>Smith</td>\n      <td>75</td>\n      <td>55</td>\n      <td>45</td>\n      <td>80</td>\n      <td>70</td>\n      <td>75</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>103</td>\n      <td>Scott</td>\n      <td>80</td>\n      <td>60</td>\n      <td>50</td>\n      <td>85</td>\n      <td>75</td>\n      <td>80</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>104</td>\n      <td>Bob</td>\n      <td>85</td>\n      <td>65</td>\n      <td>55</td>\n      <td>90</td>\n      <td>80</td>\n      <td>85</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>105</td>\n      <td>Jhon</td>\n      <td>90</td>\n      <td>70</td>\n      <td>60</td>\n      <td>95</td>\n      <td>85</td>\n      <td>90</td>\n    </tr>\n  </tbody>\n</table>'

##### **11. df.to_sql() :** Store in database
##### **Syntax : df.to_sql(name, con)**

In [123]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [118]:
import sqlite3
conn=sqlite3.connect('student.db')
df.to_sql('student',conn,if_exists='replace',index=False)
print('Data Inserted')
query='SELECT * FROM student'
df.to_sql(query,conn)

Data Inserted

5

##### 12. df.to_markdown() : Convert → markdown table

In [119]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [122]:
df.to_markdown()

'|    |   Student_ID | Names   |   Marks1 |   Marks2 |   Marks3 |   Marks4 |   Marks5 |   Marks6 |\n|---:|-------------:|:--------|---------:|---------:|---------:|---------:|---------:|---------:|\n|  1 |          101 | Aftab   |       70 |       50 |       40 |       75 |       65 |       70 |\n|  2 |          102 | Smith   |       75 |       55 |       45 |       80 |       70 |       75 |\n|  3 |          103 | Scott   |       80 |       60 |       50 |       85 |       75 |       80 |\n|  4 |          104 | Bob     |       85 |       65 |       55 |       90 |       80 |       85 |\n|  5 |          105 | Jhon    |       90 |       70 |       60 |       95 |       85 |       90 |'

#### **3. TYPE CONVERSIONS (Data types)**

##### **13. df.astype() :** Convert column data types
##### **Syntax : df.astype(dtype)**

In [124]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6
1         101  Aftab      70      50      40      75      65      70
2         102  Smith      75      55      45      80      70      75
3         103  Scott      80      60      50      85      75      80
4         104    Bob      85      65      55      90      80      85
5         105   Jhon      90      70      60      95      85      90

In [126]:
df.astype('str')

  Student_ID  Names Marks1 Marks2 Marks3 Marks4 Marks5 Marks6
1        101  Aftab     70     50     40     75     65     70
2        102  Smith     75     55     45     80     70     75
3        103  Scott     80     60     50     85     75     80
4        104    Bob     85     65     55     90     80     85
5        105   Jhon     90     70     60     95     85     90

In [127]:
df['Makrs6'] = df['Marks6'].astype(float)

In [128]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

##### **14. df.convert_dtypes() :** Automatically convert to best dtype

In [129]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [130]:
df.convert_dtypes()

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70      70
2         102  Smith      75      55      45      80      70      75      75
3         103  Scott      80      60      50      85      75      80      80
4         104    Bob      85      65      55      90      80      85      85
5         105   Jhon      90      70      60      95      85      90      90

##### **15. pd.to_numeric() :** Converts to numeric data
##### **Syntax : pd.to_numeric(df['col'])**

In [131]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [132]:
pd.to_numeric(df['Makrs6'])

1    70.0
2    75.0
3    80.0
4    85.0
5    90.0
Name: Makrs6, dtype: float64

##### **16. pd.to_datetime() :** 
##### **Syntax : pd.to_datetime(df['date'])**

In [133]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [134]:
pd.to_datetime(df['Marks6'])

1   1970-01-01 00:00:00.000000070
2   1970-01-01 00:00:00.000000075
3   1970-01-01 00:00:00.000000080
4   1970-01-01 00:00:00.000000085
5   1970-01-01 00:00:00.000000090
Name: Marks6, dtype: datetime64[ns]

#### **4. INDEX / AXIS CONVERSIONS**

##### **18. df.reset_index() :** Convert index → column

In [137]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [140]:
df.reset_index()

,index,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,Makrs6
0,1,101,Aftab,70,50,40,75,65,70,70.0
1,2,102,Smith,75,55,45,80,70,75,75.0
2,3,103,Scott,80,60,50,85,75,80,80.0
3,4,104,Bob,85,65,55,90,80,85,85.0
4,5,105,Jhon,90,70,60,95,85,90,90.0

##### **19. df.set_index() :** Convert column → index

In [141]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [146]:
df.set_index('Marks1')

        Student_ID  Names  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
Marks1
70             101  Aftab      50      40      75      65      70    70.0
75             102  Smith      55      45      80      70      75    75.0
80             103  Scott      60      50      85      75      80    80.0
85             104    Bob      65      55      90      80      85    85.0
90             105   Jhon      70      60      95      85      90    90.0

##### **20. df.rename_axis(index=None,columns=None) :** Convert axis labels

In [147]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [148]:
df.rename_axis()

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [149]:
df.rename_axis('STUDENT_ID')

,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,Makrs6
STUDENT_ID,,,,,,,,,
1,101,Aftab,70,50,40,75,65,70,70.0
2,102,Smith,75,55,45,80,70,75,75.0
3,103,Scott,80,60,50,85,75,80,80.0
4,104,Bob,85,65,55,90,80,85,85.0
5,105,Jhon,90,70,60,95,85,90,90.0

In [152]:
df.rename_axis(columns='STUDENT_NUMBER')

STUDENT_NUMBER,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,Makrs6
1,101,Aftab,70,50,40,75,65,70,70.0
2,102,Smith,75,55,45,80,70,75,75.0
3,103,Scott,80,60,50,85,75,80,80.0
4,104,Bob,85,65,55,90,80,85,85.0
5,105,Jhon,90,70,60,95,85,90,90.0

In [153]:
df.rename_axis(index='Marks',columns='STUDENT_NUMBER')

STUDENT_NUMBER,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,Makrs6
Marks,,,,,,,,,
1,101,Aftab,70,50,40,75,65,70,70.0
2,102,Smith,75,55,45,80,70,75,75.0
3,103,Scott,80,60,50,85,75,80,80.0
4,104,Bob,85,65,55,90,80,85,85.0
5,105,Jhon,90,70,60,95,85,90,90.0

#### **5. SHAPE / FORMAT CONVERSIONS**

##### **21. df.stack() :** Columns → rows

In [154]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [155]:
df.stack()

1  Student_ID      101
   Names         Aftab
   Marks1           70
   Marks2           50
   Marks3           40
   Marks4           75
   Marks5           65
   Marks6           70
   Makrs6         70.0
2  Student_ID      102
   Names         Smith
   Marks1           75
   Marks2           55
   Marks3           45
   Marks4           80
   Marks5           70
   Marks6           75
   Makrs6         75.0
3  Student_ID      103
   Names         Scott
   Marks1           80
   Marks2           60
   Marks3           50
   Marks4           85
   Marks5           75
   Marks6           80
   Makrs6         80.0
4  Student_ID      104
   Names           Bob
   Marks1           85
   Marks2           65
   Marks3           55
   Marks4           90
   Marks5           80
   Marks6           85
   Makrs6         85.0
5  Student_ID      105
   Names          Jhon
   Marks1           90
   Marks2           70
   Marks3           60
   Marks4           95
   Marks5           85
   Marks6           90
   Makrs6         90.0
dtype: object

##### **22. df.unstack() :** Rows → columns

In [157]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [158]:
df.stack()

1  Student_ID      101
   Names         Aftab
   Marks1           70
   Marks2           50
   Marks3           40
   Marks4           75
   Marks5           65
   Marks6           70
   Makrs6         70.0
2  Student_ID      102
   Names         Smith
   Marks1           75
   Marks2           55
   Marks3           45
   Marks4           80
   Marks5           70
   Marks6           75
   Makrs6         75.0
3  Student_ID      103
   Names         Scott
   Marks1           80
   Marks2           60
   Marks3           50
   Marks4           85
   Marks5           75
   Marks6           80
   Makrs6         80.0
4  Student_ID      104
   Names           Bob
   Marks1           85
   Marks2           65
   Marks3           55
   Marks4           90
   Marks5           80
   Marks6           85
   Makrs6         85.0
5  Student_ID      105
   Names          Jhon
   Marks1           90
   Marks2           70
   Marks3           60
   Marks4           95
   Marks5           85
   Marks6           90
   Makrs6         90.0
dtype: object

In [159]:
df.unstack()

Student_ID  1      101
            2      102
            3      103
            4      104
            5      105
Names       1    Aftab
            2    Smith
            3    Scott
            4      Bob
            5     Jhon
Marks1      1       70
            2       75
            3       80
            4       85
            5       90
Marks2      1       50
            2       55
            3       60
            4       65
            5       70
Marks3      1       40
            2       45
            3       50
            4       55
            5       60
Marks4      1       75
            2       80
            3       85
            4       90
            5       95
Marks5      1       65
            2       70
            3       75
            4       80
            5       85
Marks6      1       70
            2       75
            3       80
            4       85
            5       90
Makrs6      1     70.0
            2     75.0
            3     80.0
            4     85.0
            5     90.0
dtype: object

##### **23. df.melt() :** Wide → long format

In [160]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [161]:
df.melt()

      variable  value
0   Student_ID    101
1   Student_ID    102
2   Student_ID    103
3   Student_ID    104
4   Student_ID    105
5        Names  Aftab
6        Names  Smith
7        Names  Scott
8        Names    Bob
9        Names   Jhon
10      Marks1     70
11      Marks1     75
12      Marks1     80
13      Marks1     85
14      Marks1     90
15      Marks2     50
16      Marks2     55
17      Marks2     60
18      Marks2     65
19      Marks2     70
20      Marks3     40
21      Marks3     45
22      Marks3     50
23      Marks3     55
24      Marks3     60
25      Marks4     75
26      Marks4     80
27      Marks4     85
28      Marks4     90
29      Marks4     95
30      Marks5     65
31      Marks5     70
32      Marks5     75
33      Marks5     80
34      Marks5     85
35      Marks6     70
36      Marks6     75
37      Marks6     80
38      Marks6     85
39      Marks6     90
40      Makrs6   70.0
41      Makrs6   75.0
42      Makrs6   80.0
43      Makrs6   85.0
44      Makrs6   90.0

##### **24. df.pivot() :** Long → wide format

In [162]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [167]:
df.pivot(columns=['Student_ID'])

            Names                          Marks1                          \
Student_ID    101    102    103  104   105    101   102   103   104   105
1           Aftab    NaN    NaN  NaN   NaN   70.0   NaN   NaN   NaN   NaN
2             NaN  Smith    NaN  NaN   NaN    NaN  75.0   NaN   NaN   NaN
3             NaN    NaN  Scott  NaN   NaN    NaN   NaN  80.0   NaN   NaN
4             NaN    NaN    NaN  Bob   NaN    NaN   NaN   NaN  85.0   NaN
5             NaN    NaN    NaN  NaN  Jhon    NaN   NaN   NaN   NaN  90.0

            ... Marks6                         Makrs6
Student_ID  ...    101   102   103   104   105    101   102   103   104   105
1           ...   70.0   NaN   NaN   NaN   NaN   70.0   NaN   NaN   NaN   NaN
2           ...    NaN  75.0   NaN   NaN   NaN    NaN  75.0   NaN   NaN   NaN
3           ...    NaN   NaN  80.0   NaN   NaN    NaN   NaN  80.0   NaN   NaN
4           ...    NaN   NaN   NaN  85.0   NaN    NaN   NaN   NaN  85.0   NaN
5           ...    NaN   NaN   NaN   NaN  90.0    NaN   NaN   NaN   NaN  90.0

[5 rows x 40 columns]

#### **6. COPY / DUPLICATION**

##### **26. df.copy() :** Create copy

In [170]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [172]:
df1=df.copy()

In [173]:
df1

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0

In [174]:
df1[0,0]=100

In [175]:
df1

,Student_ID,Names,Marks1,Marks2,Marks3,Marks4,Marks5,Marks6,Makrs6,"(0, 0)"
1,101,Aftab,70,50,40,75,65,70,70.0,100
2,102,Smith,75,55,45,80,70,75,75.0,100
3,103,Scott,80,60,50,85,75,80,80.0,100
4,104,Bob,85,65,55,90,80,85,85.0,100
5,105,Jhon,90,70,60,95,85,90,90.0,100

In [176]:
df

   Student_ID  Names  Marks1  Marks2  Marks3  Marks4  Marks5  Marks6  Makrs6
1         101  Aftab      70      50      40      75      65      70    70.0
2         102  Smith      75      55      45      80      70      75    75.0
3         103  Scott      80      60      50      85      75      80    80.0
4         104    Bob      85      65      55      90      80      85    85.0
5         105   Jhon      90      70      60      95      85      90    90.0